### ISSUE TITLE
Add nuget sources option

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnx#1113]
Currently trying to list the available NuGet sources using kpm blows up with an exception:

```
C:\Users\danroth27\Documents\Visual Studio 14\Projects\WebApplication7\src\WebApplication7>kpm sources
Specify --help for a list of available options and commands.
System.Exception: TODO: Error: unrecognized argument 'sources'
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
```

**Comment by davidfowl** [comment]
Yess!!! :smile:

**Comment by alfkonee** [comment]
Yes yes I think this should be a very top priority cus new nuget sources for aspvext are popping up in the project causing some dependencies to fail installation
It would be nice to be able to edit the list of sources for kpm
