### ISSUE TITLE
`kpm restore` fails when it cannot parse a NuGet package source URI

### ISSUE THREAD

**Issue by conniey** [aspnet/dnx#1150]
I had a scenario where I had a NuGet.config in D:\src *and* D:\src\Roxel\MyLibrary.  When I did a kpm restore, it just told me that the URI could not be determined.  It turned out that `D:\src\NuGet.config` had a relative path, `.\Tools\My Packages` and it was trying to resolve it as `D:\src\.\Tools\My Packages`.

[PackageSourceUtils.cs:32](https://github.com/aspnet/XRE/blob/dev/src/Microsoft.Framework.PackageManager/Utils/PackageSourceUtils.cs#L32) is where the error occurs because `new Uri(source.Source)` is assumed to always work.
 
```
D:\src\Roxel\MyLibrary [master]> kpm restore
Restoring packages for D:\src\Roxel\MyLibrary\project.json
----------
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.Framework.PackageManager.RestoreCommand.AddRemoteProvidersFromSources(List`1 remoteProviders, List`1 eff
ectiveSources)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__1.MoveNext()
----------
Restore failed
Invalid URI: The format of the URI could not be determined.
```

**Comment by conniey** [comment]
I expect it to at least behave like the official (NuGet config file)[http://docs.nuget.org/consume/nuget-config-file] when it fails by ignoring the invalid NuGet.config file and then moving onwards.

Instead, this one doesn't bother restoring packages if the NuGet.config settings in the current directory is correct but the ones further up are not.

**Comment by muratg** [comment]
@anurse please have a look as part of the current work.
