### ISSUE TITLE
PathTooLongException when packing

### ISSUE THREAD

**Issue by fsbahman** [aspnet/dnx#1173]
Hi,
My project structure is not very long but I guess its Api limitation that path couldn't exceed 260 characters.

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/XRE/issues/1008 and/or https://github.com/aspnet/XRE/issues/944 ?

**Comment by Praburaj** [comment]
@fsbahman meanwhile you could set the pack output to something as small as `c:\test`.

**Comment by fsbahman** [comment]
@Eilon root cause is same but it occurs when using "kpm pack" 
@Praburaj indeed it will be a temporary solution, but I willl have even longer path.

**Comment by stimms** [comment]
Incidentally the command for this is 

    kpm bundle --out c:\test --runtime  dnx-clr-win-x86.1.0.0-beta3

Obviously replace the runtime with whatever you're using.

**Comment by codespare** [comment]
Happens trying to build MusicStore with build.cmd during dnu restore as well. It gets lost recursing down node_modules directories I think:
```
PS [dev] C:\User\Dev\ext\Universe\MusicStore>.\build.cmd
Attempting to gather dependencies information for package 'KoreBuild.0.2.1-rc1-15542' with respect to project 'packages', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'KoreBuild.0.2.1-rc1-15542' with DependencyBehavior 'Lowest'
Resolving actions to install package 'KoreBuild.0.2.1-rc1-15542'
Resolved actions to install package 'KoreBuild.0.2.1-rc1-15542'
Adding package 'KoreBuild.0.2.1-rc1-15542' to folder 'packages'
Added package 'KoreBuild.0.2.1-rc1-15542' to folder 'packages'
Successfully installed 'KoreBuild 0.2.1-rc1-15542' to packages
Attempting to gather dependencies information for package 'Sake.0.2.2' with respect to project 'packages', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'Sake.0.2.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Sake.0.2.2'
Resolved actions to install package 'Sake.0.2.2'
Adding package 'Sake.0.2.2' to folder 'packages'
Added package 'Sake.0.2.2' to folder 'packages'
Successfully installed 'Sake 0.2.2' to packages
Determining latest version
'dnx-clr-win-x86.1.0.0-rc1-15844' is already installed in c:\Users\User\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15844.
Adding c:\Users\User\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15844\bin to process PATH
Adding c:\Users\User\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15844\bin to user PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-rc1-15844'
'dnx-coreclr-win-x86.1.0.0-rc1-15844' is already installed in c:\Users\User\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-15844.
Adding c:\Users\User\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-15844\bin to process PATH
'dnx-clr-win-x64.1.0.0-rc1-15844' is already installed in c:\Users\User\.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-15844.
Adding c:\Users\User\.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-15844\bin to process PATH
'dnx-coreclr-win-x64.1.0.0-rc1-15844' is already installed in c:\Users\User\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-15844.
Adding c:\Users\User\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-15844\bin to process PATH
Adding c:\Users\User\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15844\bin to process PATH
info: Build v2: False
info: Exec
info:   program: cmd
info:   commandline: /C dnu restore --parallel
info:   workingdir: C:\User\Dev\ext\Universe\MusicStore
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-15844

----------
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.Find(String restoreDirectory, IEnumerable`1& projectJsonFiles)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
fail: Exit code 1 from cmd
fail: Stack trace:
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__9f() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 8837
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.StartingTarget(String name) in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 1937
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__5e() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3112
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.StartingTarget(String name) in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 1937
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__5f() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3129
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.StartingTarget(String name) in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 1937
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__60() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3146
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.StartingTarget(String name) in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 1937
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__61() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3163
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__59() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3019
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```

**Comment by stajs** [comment]
We've also hit this due to deep nesting of `node_modules` folders. We got around this by updating to NPM v3 (latest at time of writing is v3.3.10, but the change you need came in at [v3.0.0](https://github.com/npm/npm/releases/tag/v3.0.0)):

> ### Flat, flat, flat!
>
> Your dependencies will now be installed _maximally flat_. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's `node_modules` folder with no nesting. You'll only see modules nested underneath one another when two (or more) modules have conflicting dependencies.

Then it's a matter of telling VS2015 to use these updated bits. Credit to this guy (but replicated here in case URL goes down):

http://jameschambers.com/2015/09/upgrading-npm-in-visual-studio-2015/

Update `Tools > Options > Projects and Solutions > External Web Tools` and add a path to your system installed NPM v3, and make sure it is above the VS bits.

![image](https://cloud.githubusercontent.com/assets/2253814/10809025/11ee97e2-7e57-11e5-9281-58cc1f7e424b.png)

BTW, I really wish VS didn't ship with it's own versions of these, or at least default to using system installed versions first.

**Comment by davidfowl** [comment]
Closing this out as I'm sure there's nothing else we can do here
