### ISSUE TITLE
Avoid conflicts between parallel `kpm restore` operations

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#1190]
Builds now (since commit https://github.com/aspnet/XRE/commit/7144ddcb0b43da44b6d18f0ed76244387b512f14) fail fairly frequently due to conflicts between threads attempting to restore the same packages.

@pranavkm let me know reverting that commit solve everything due to potential conflicts when (e.g. on a CI machine) multiple processes execute `kpm restore` at the same time.  We could configure CI machines to use per-build packages directories but that's fairly ugly.

Sample stack trace is
```
----------
System.IO.IOException: Access to the path 'C:\Users\dougbu\.k\packages\System.ObjectModel\4.0.10-beta-22610\..\qxrqrbct.bcn' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Microsoft.Framework.PackageManager.NuGetPackageUtils.<>c__DisplayClass0_0.<<InstallFromStream>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.ConcurrencyUtilities.<ExecuteWithFileLocked>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.NuGetPackageUtils.<InstallFromStream>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<InstallPackages>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass61_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass71_0`1.<<ForEachAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__61.MoveNext()
----------
Restore failed
Access to the path 'C:\Users\dougbu\.k\packages\System.ObjectModel\4.0.10-beta-22610\..\qxrqrbct.bcn' is denied.
warn: Exit code 1 from cmd
verbose: Stack trace:
   at Viewcadcba61f4d94e58b66ea6142d3f40e7.<RenderViewLevel0>b__57() in c:\Users\dougbu\AppData\Local\Temp\b256297c02d24385b290912870cc436f-1.cs:line 6197
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewcadcba61f4d94e58b66ea6142d3f40e7.<RenderViewLevel0>b__42() in c:\Users\dougbu\AppData\Local\Temp\b256297c02d24385b290912870cc436f-1.cs:line 1259
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewcadcba61f4d94e58b66ea6142d3f40e7.<RenderViewLevel0>b__43() in c:\Users\dougbu\AppData\Local\Temp\b256297c02d24385b290912870cc436f-1.cs:line 1276
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewcadcba61f4d94e58b66ea6142d3f40e7.<RenderViewLevel0>b__44() in c:\Users\dougbu\AppData\Local\Temp\b256297c02d24385b290912870cc436f-1.cs:line 1293
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewcadcba61f4d94e58b66ea6142d3f40e7.<RenderViewLevel0>b__45() in c:\Users\dougbu\AppData\Local\Temp\b256297c02d24385b290912870cc436f-1.cs:line 1310
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Viewcadcba61f4d94e58b66ea6142d3f40e7.<RenderViewLevel0>b__3d() in c:\Users\dougbu\AppData\Local\Temp\b256297c02d24385b290912870cc436f-1.cs:line 1166
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```

**Comment by muratg** [comment]
@pranavkm do you have a repro for this issue?

**Comment by dougbu** [comment]
@muratg easiest way to repro is to delete your packages directory, clean, and then run `.\build.cmd --quiet default` or `kpm restore --quiet` in an MVC repo.  deleting packages directory just increases opportunities for a conflict -- doesn't cause the problem here.

**Comment by muratg** [comment]
Looks like we might need to identify packages which are already is being downloaded by someone else, and skip.  @pranavkm what do you think?  I expect more folks to hit this.

**Comment by muratg** [comment]
@pranavkm are you looking at this for beta4? (i guess there are 3 or so bugs tracking this.. we should leave only one and close the others as dups)

**Comment by muratg** [comment]
@pranavkm Were you able to look into this?

**Comment by pranavkm** [comment]
Not as yet. I might be able to spend some time with it today - however if this is critical for beta4, we should undo this feature and revisit this in beta5.

**Comment by muratg** [comment]
@pranavkm beta4 or beta5?

**Comment by pranavkm** [comment]
We don't have parallel restores on by default as part of beta4. The fix would be for beta5.

**Comment by muratg** [comment]
Checked with @pranavkm.  This was fixed.
