### ISSUE TITLE
DTH throws exception: The design time host build failed with the following error: Could not load file or assembly 'Microsoft.Framework.Runtime.Roslyn' or one of its dependencies

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#1298]
Repro:

1. Create new ASP.NET 50 Console App
2. Add a new project to the solution (another console app)
3. Add reference to App1 to App2, right click Add Reference dialog etc
4. build everything
5. Close solution
6. Reopen solution and modify program.cs in App1
7. build

Actual result:
Error		The design time host build failed with the following error: Could not load file or assembly '4cc62e12-20ac-4af6-be57-b141504376f8$Microsoft.Framework.Runtime.Roslyn' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))	ConsoleApp6	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets	135

Then when i build again  i see:
Error		The design time host build failed with the following error: Could not load file or assembly '4cc62e12-20ac-4af6-be57-b141504376f8$Microsoft.Framework.Runtime.Roslyn' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))	ConsoleApp6	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets	135

Expeted: No exceptions, build OK

**Comment by davidfowl** [comment]
This is a dupe

**Comment by davidfowl** [comment]
I also couldn't repro it with those steps. Is it consistent for you?

**Comment by abpiskunov** [comment]
I was trying to find a good repro for a while, and with those steps it worked 2 times in a raw ...

**Comment by davidfowl** [comment]
Does it repro with the latest bits?

**Comment by abpiskunov** [comment]
My machines were updated on last Monday and Tuesday, I will try it again when update my machines next time on next week

**Comment by yhax** [comment]
@abpiskunov any update?

**Comment by abpiskunov** [comment]
Does not repro any more, we can close it

**Comment by muratg** [comment]
@david does this still repro?

**Comment by davidfowl** [comment]
No that I'm aware of

**Comment by CarlosFreire** [comment]
Please Help, error in VS 2015 RTM, MVC 6 beta 7

System.IO.FileLoadException
Could not load file or assembly 'Cross2Business.Administrador' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef) 
at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList<String> diagnosticMessages) 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup() 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices() 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.get_ApplicationServices() 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.ApplicationStart(IHttpApplication application) 
at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.InvokeApplicationStart(IHttpApplication application)

**Comment by muratg** [comment]
@CarlosFreire what's the dnx version that you're using? Can you try a build newer than 12265?
