### ISSUE TITLE
project.json is being used by another process

### ISSUE THREAD

**Issue by davidfowl** [aspnet/DNX#1374]
```
Information: [LoaderContainer]: Load name=Microsoft.Framework.PackageManager
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.PackageManager in 97ms
Restoring packages for C:\Users\davifowl\Documents\Visual Studio 14\Projects\WebApplication10\src\WebApplication10\project.json
Information: [LoaderContainer]: Load name=Microsoft.Framework.PackageManager
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Reflection'
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.PackageManager in 74ms
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Reflection'
Restoring packages for C:\Users\davifowl\Documents\Visual Studio 14\Projects\WebApplication10\src\WebApplication10\project.json
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.IO'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Reflection'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.IO'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Reflection'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Threading.Tasks'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.IO'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Threading.Tasks'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.IO'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Runtime'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Threading.Tasks'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Threading.Tasks'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Globalization'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Runtime'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Globalization'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Collections'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Globalization'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Collections'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Globalization'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Runtime.InteropServices'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Collections'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime.InteropServices'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Collections'
----------
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='System.Runtime.InteropServices'
System.IO.IOException: The process cannot access the file 'C:\Users\davifowl\Documents\Visual Studio 14\Projects\WebApplication10\src\WebApplication10\project.json' because it is being used by another process.
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime.InteropServices'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
Writing lock file C:\Users\davifowl\Documents\Visual Studio 14\Projects\WebApplication10\src\WebApplication10\project.lock.json
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at TempRepack.Engine.Model.RuntimeFileFormatter.ReadRuntimeFile(String filePath) in C:\dev\git\ProjectK\KRuntime\src\Microsoft.Framework.PackageManager\Restore\RuntimeModel\RuntimeFormatter.cs:line 14
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__79.MoveNext() in C:\dev\git\ProjectK\KRuntime\src\Microsoft.Framework.PackageManager\Restore\RestoreCommand.cs:line 433
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass77_0.<<ExecuteCommand>b__0>d.MoveNext() in C:\dev\git\ProjectK\KRuntime\src\Microsoft.Framework.PackageManager\Restore\RestoreCommand.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass95_0`1.<<ForEachAsync>b__0>d.MoveNext() in C:\dev\git\ProjectK\KRuntime\src\Microsoft.Framework.PackageManager\Restore\RestoreCommand.cs:line 932
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__77.MoveNext() in C:\dev\git\ProjectK\KRuntime\src\Microsoft.Framework.PackageManager\Restore\RestoreCommand.cs:line 131
----------
Restore failed
The process cannot access the file 'C:\Users\davifowl\Documents\Visual Studio 14\Projects\WebApplication10\src\WebApplication10\project.json' because it is being used by another process.
Loaded Module: dnx.clr.dll
Found DLL Export: CallApplicationMain
Restore complete, 1187ms elapsed
Loaded Module: dnx.clr.dll
Found DLL Export: CallApplicationMain
```

/cc @PradeepKadubandi @ChengTian

**Comment by ChengTian** [comment]
Dup of https://github.com/aspnet/DNX/issues/1378
