### ISSUE TITLE
kpm restore fails when project.json is readonly

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/DNX#1378]
I am using the new dnx drop after rename : dnx-clr-win-x86.1.0.0-beta4-11235

Create a new console app and running 'kpm restore' from the app's folder works.

After that make 'project.json' file read only (attrib +R project.json) and then run 'kpm restore' and it fails saying UnauthorizedException.

**Comment by PradeepKadubandi** [comment]
Here's the stack trace:

Restoring packages for C:\Users\pradeek\Documents\Visual Studio 2015\Projects\TestConsoleApp\src\TestConsoleApp\project.json
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.IO'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.IO'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Text.Encoding'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Text.Encoding'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Threading.Tasks'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Threading.Tasks'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime'
----------
System.UnauthorizedAccessException: Access to the path 'C:\Users\pradeek\Documents\Visual Studio 2015\Projects\TestConsoleApp\src\TestConsoleApp\proje
ct.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, Fil
eOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath
, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at TempRepack.Engine.Model.RuntimeFileFormatter.ReadRuntimeFile(String filePath)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass77_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass95_0`1.<<ForEachAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__77.MoveNext()
----------
Restore failed
Access to the path 'C:\Users\pradeek\Documents\Visual Studio 2015\Projects\TestConsoleApp\src\TestConsoleApp\project.json' is denied.
