### ISSUE TITLE
Restore failed as lock file is accessed by another process

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnx#1393]
While saving the `project.json` file from VS I ran into this issue. I cannot reproduce this issue consistently, but filing a bug to just see if others run into this as well. 

I was using this XRE while I ran into this: 
```
 *    1.0.0-beta4-11268 clr     x86          C:\Users\user\.dnx\runtimes default
```

```
While trying to save a project.json I encountered this error. Is this the one that you talked about in the stand up? 

Writing lock file D:\K\Session\test\Microsoft.AspNet.Session.Tests\project.lock.json
Writing lock file D:\K\Session\src\Microsoft.AspNet.Session\project.lock.json
----------
System.IO.IOException: The process cannot access the file 'd:\K\Session\test\Microsoft.AspNet.Session.Tests\project.lock.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.Write(String filePath, LockFile lockFile)
   at Microsoft.Framework.PackageManager.RestoreCommand.WriteLockFile(String projectLockFilePath, Project project, List`1 graphItems, PackageRepository repository, IEnumerable`1 frameworks)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass77_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass95_0`1.<<ForEachAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__77.MoveNext()
----------
Restore failed
The process cannot access the file 'd:\K\Session\test\Microsoft.AspNet.Session.Tests\project.lock.json' because it is being used by another process.
Restore complete, 1528ms elapsed
Restore complete, 1531ms elapsed
Restore complete, 1540ms elapsed
Total time 1748ms
```

**Comment by muratg** [comment]
@Praburaj were you running kpm restore while saving the file or was that kicked off by VS?

**Comment by Praburaj** [comment]
I just saved project.json in VS and there was no `kpm restore` running from command line at that time. But as I said I can't reproduce this consistently. It just happened once.

**Comment by glennc** [comment]
So for this to occur you need to be running restore and then kick off a restore in VS and have them happen to hit the same projects lock file at the same time. Seems rare, and the error message for it doesn't seem terrible. We could perhaps catch the error and retry, but I'm not sure that's any better.

Closing unless this hits someones main flow consistently, or commonly. I'm not against the retry in principle, but I don't think we should worry about it right now.

**Comment by dougbu** [comment]
see also aspnet/DNX#1190.  it only takes one process and a large-ish repo for problems to occur at least some of the time.

**Comment by Praburaj** [comment]
I ran into this today again on a different repo. 

```
----------
System.IO.IOException: The process cannot access the file 'D:\K\HttpAbstractions\src\Microsoft.AspNet.WebUtilities\project.lock.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.Write(String filePath, LockFile lockFile)
   at Microsoft.Framework.PackageManager.RestoreCommand.WriteLockFile(String projectLockFilePath, Project project, List`1 graphItems, PackageRepository repository, IEnumerable`1 frameworks)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass77_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass95_0`1.<<ForEachAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__77.MoveNext()
----------
Restore failed
The process cannot access the file 'D:\K\HttpAbstractions\src\Microsoft.AspNet.WebUtilities\project.lock.json' because it is being used by another process.
Loaded Module: dnx.clr.dll
```

**Comment by Praburaj** [comment]
I'm seeing this often now. Reopening.

**Comment by Praburaj** [comment]
I'm not seeing this issue these days. Closing it.
