### ISSUE TITLE
ArgumentException can be thrown on KPM restore due to duplicate properties

### ISSUE THREAD

**Issue by MattGal** [aspnet/DNX#1395]
I have gotten into the habit of deleting project.lock.json whenever anything goes wrong during package restore or after updating runtime, but in this case it does not work.  

The error mode is this.  Regardless of how I got there (I have preserved the package cache folder and project folder for inspection by the team), this is a very poor error experience:

Writing lock file C:\GIT\...\project.lock.json
System.ArgumentException: Can not add property EntityFramework.Relational to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WritePackageDependencySet(PackageDependencySet item)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteLibrary(LockFileLibrary library)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.WriteLockFile(LockFile lockFile)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.Write(Stream stream, LockFile lockFile)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.Write(String filePath, LockFile lockFile)
   at Microsoft.Framework.PackageManager.RestoreCommand.WriteLockFile(String projectLockFilePath, List`1 graphItems, PackageRepository repository)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass77_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass89_0`1.<<ForEachAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__77.MoveNext()
Restore failed
Can not add property EntityFramework.Relational to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Home/issues/368
