### ISSUE TITLE
cl.exe crash on DNX solution build

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/dnx#1417]
Environment: Windows Server 2012 CTP6 Azure Visual Studio template 

I have done a clean pull/clone, and the build.cmd fails with the following dialogue:

![untitled](https://cloud.githubusercontent.com/assets/10151920/6663437/85a3f2f0-cbbe-11e4-8ce2-ffcc7ee84209.png)

The crash happens on attempting to build the DNX project.

Time elapsed 00:00:02.3209329
info: Copying dnx.coreclr.managed.1.0.0-t150316091642.nupkg
info: Copying dnx.coreclr.managed.1.0.0-t150316091642.symbols.nupkg
info: Copying dnxcore50\dnx.coreclr.managed.dll
info: Copying dnxcore50\dnx.coreclr.managed.pdb
info: Copying dnxcore50\dnx.coreclr.managed.xml
info: Target build-mono-entrypoint
info: Using compiler :C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe for Mono Entry point executor
info: Exec
info:   program: C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe
info:   commandline: /target:exe /nologo /unsafe /out:"C:\Git\DNX\artifacts\build\dnx.mono.managed\dnx.mono.managed.dll" /r:"C:\Git\DNX\artifacts\build\dnx.host\dnx451\dn
x.host.dll" /define:DNX451 src\dnx.mono.managed\EntryPoint.cs src\Microsoft.Framework.CommandLineUtils\CommandLine\CommandArgument.cs src\Microsoft.Framework.CommandLineU
tils\CommandLine\CommandLineApplication.cs src\Microsoft.Framework.CommandLineUtils\CommandLine\CommandOption.cs src\Microsoft.Framework.CommandLineUtils\CommandLine\Comm
andOptionType.cs src\Microsoft.Framework.Runtime.Common\Impl\EnvironmentNames.cs src\Microsoft.Framework.Runtime.Common\Impl\Constants.cs
info:   workingdir: C:\Git\DNX
info: Target build-compile
info: Target update-rc-files
info: Target build-native-bootstrapper
info: Exec
info:   program: C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
info:   commandline: C:\Git\DNX\src\dnx\dnx.vcxproj /p:Configuration=Debug;Platform=Win32;TargetFramework=dnx451;RuntimeType=CLR
info:   workingdir: C:\Git\DNX
Microsoft (R) Build Engine version 14.0.22609.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/16/2015 9:20:23 AM.
The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (60,11)" d
oes not exist in the project, and will be ignored.
The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (108,11)"
does not exist in the project, and will be ignored.
Project "C:\Git\DNX\src\dnx\dnx.vcxproj" on node 1 (default targets).
InitializeBuildStatus:
  Touching "bin\Win32\Debug\dnx451\dnx.tlog\unsuccessfulbuild".
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /ZI /nologo /W3 /WX- /sdl /Od /Oy- /D WIN32 /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm /EHsc
   /RTC1 /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yc"stdafx.h" /Fp"bin\Win32\Debug\dnx451\dnx.pch" /Fo"bin\Win32\Debug\dnx451\\" /Fd"bin\Win32\Debug\dnx4
  51\vc140.pdb" /Gd /TP /analyze- /errorReport:queue stdafx.cpp
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(266,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Git\DNX\src\dnx\dnx.
vcxproj]
Done Building Project "C:\Git\DNX\src\dnx\dnx.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Git\DNX\src\dnx\dnx.vcxproj" (default target) (1) ->
(ClCompile target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(266,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Git\DNX\src\dnx\dn
x.vcxproj]

0 Warning(s)
1 Error(s)

Time Elapsed 00:03:51.29
warn: Exit code 1 from C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
verbose: Stack trace:
   at Viewcef08c43f8f44264bce0fdc456c2103c.Exec(String program, String commandline) in c:\Users\tdu\AppData\Local\Temp\2\fd5fac24e4c44811a905de2e7891fc2f-1.cs:line 751
   at Viewcef08c43f8f44264bce0fdc456c2103c.<>c__DisplayClasscb.<RenderViewLevel0>b__8f() in c:\Users\tdu\AppData\Local\Temp\2\fd5fac24e4c44811a905de2e7891fc2f-1.cs:line 1
1333
   at Sake.Engine.Builder.BuilderBase1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase1.StartingTarget(String name)
   at Viewcef08c43f8f44264bce0fdc456c2103c.<RenderViewLevel0>b__8b() in c:\Users\tdu\AppData\Local\Temp\2\fd5fac24e4c44811a905de2e7891fc2f-1.cs:line 10419
   at Sake.Engine.Builder.BuilderBase1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase1.StartingTarget(String name)
   at Viewcef08c43f8f44264bce0fdc456c2103c.<RenderViewLevel0>b__66() in c:\Users\tdu\AppData\Local\Temp\2\fd5fac24e4c44811a905de2e7891fc2f-1.cs:line 1766
   at Sake.Engine.Builder.BuilderBase1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase1.StartingTarget(String name)
   at Viewcef08c43f8f44264bce0fdc456c2103c.<RenderViewLevel0>b__67() in c:\Users\tdu\AppData\Local\Temp\2\fd5fac24e4c44811a905de2e7891fc2f-1.cs:line 1783
   at Sake.Engine.Builder.BuilderBase1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase1.StartingTarget(String name)
   at Viewcef08c43f8f44264bce0fdc456c2103c.<RenderViewLevel0>b__68() in c:\Users\tdu\AppData\Local\Temp\2\fd5fac24e4c44811a905de2e7891fc2f-1.cs:line 1800
   at Sake.Engine.Builder.BuilderBase1.CallTarget(String name)
   at Viewcef08c43f8f44264bce0fdc456c2103c.<RenderViewLevel0>b__60() in c:\Users\tdu\AppData\Local\Temp\2\fd5fac24e4c44811a905de2e7891fc2f-1.cs:line 1656
   at Sake.Engine.Builder.BuilderBase1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
   
Let me know if it is something I need to change on my environment.

**Comment by jsacapdev** [comment]
UPDATE:

FYI - the following are installed:

Microsoft Visual C 2015 CTP Redistributable (x64) - 14.0.22609
Microsoft Visual C 2015 CTP Redistributable (x86) - 14.0.22609
