### ISSUE TITLE
--debug passes argument on, resulting in unrecognized option

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnx#1418]
After attaching debugger get the below error message.

Waiting for the debugger to attach...
Debugger attached.
Specify --help for a list of available options and commands.
System.Exception: TODO: Error: unrecognized option '--debug' 
at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)

**Comment by BrennanConroy** [comment]
I made a fix for this just now

**Comment by victorhurdugaci** [comment]
@anurse said he will address this as part of the work he's doing to dnx

**Comment by anurse** [comment]
I'm not actually working on the dnx native code right now, so feel free to push that change @BrennanConroy
