### ISSUE TITLE
In CoreClr, Type.GetType() throws exception with 'throwOnError' set to 'false'

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#1449]
Repro:
- Set your DNX to use CoreClr.
- Create a new DNX console app.
- Paste the following code
```C#
public class Program
{
    public void Main(string[] args)
    {
        try
        {
            var type = Type.GetType(
                "System.DBNull, System.Data.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", 
                throwOnError: false);
            Console.WriteLine("Did not throw. Found type?: {0}", (type != null));
        }
        catch (Exception ex)
        {
            Console.WriteLine("Exception occurred:");
            Console.WriteLine(ex.ToString());
        }
    }
}
```
- Do a `k run`
- You should see the following exception:
```
System.IO.FileLoadException: Could not load file or assembly 'System.Data.Common, Version=0.0.0.0, Culture=neutral, Publ
icKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Could not find or load a specific file. (Exception from HRESULT
: 0x80131621)
File name: 'System.Data.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileLo
adException: Could not load the specified file.
File name: 'System.Data.Common'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOn
ly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOn
ly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, Stac
kCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at DCSIssueReproCode.Program.Main(String[] args) in C:\Users\kichalla\Documents\Visual Studio Next\Projects\DCSIssueR
eproCode\src\DCSIssueReproCode\Program.cs:line 16
```

Note that this exception is not thrown if `System.Data.Common` package is referenced in project.json, but I think this api shouldn't be throwing when `throwOnError` is set to `false` irrespective of whether the package is referenced or not

@davidfowl @danroth27 @rynowak

**Comment by kichalla** [comment]
Looks like this issue is in CoreCLR: https://github.com/dotnet/coreclr/pull/516
