### ISSUE TITLE
Regression with latest dnx

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1476]
File new project in visual studio shows this error in DTH:

```
Information: [ConnectionContext]: Creating new application context for 1
Information: [ApplicationContext]: Set DTH protocol version to 1.
Information: [ApplicationContext]: Received Initialize
Information: [ApplicationContext]: Set DTH protocol version to 1.
Error: [ApplicationContext]: Error occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.<>c__DisplayClass56_0.<GetApplicationHostContext>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Framework.Runtime.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.GetApplicationHostContext(Project project, String configuration, FrameworkName frameworkName, Boolean useRuntimeLoadContextFactory)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.<>c__DisplayClass58_0.<ResolveProjectDepencies>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Framework.Runtime.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.ResolveProjectDepencies(Project project, String configuration, FrameworkName frameworkName)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.DoInitialWork(String appPath, String configuration, Boolean triggerBuildOutputs, Boolean triggerDependencies)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.ResolveDependencies()
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.DoProcessLoop()
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.ProcessLoop(Object state)
Information: [ProcessingQueue]: Send((699289443fc84c81924c59405e3f0e85, Error, 1) -> {
  "Message": "Object reference not set to an instance of an object.",
  "Path": null,
  "Line": 0,
  "Column": 0
})

```

Haven't debugged it yet but it's either @troydai 's change or @ChengTian 's change is my guess.

**Comment by ChengTian** [comment]
It's introduced by this change: https://github.com/aspnet/dnx/commit/7ea973d046f07b3d0bea018f86d07a286aa43961

I'll fix it
