### ISSUE TITLE
kpm bundle fail for project contains long path

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#1500]
Move from https://github.com/aspnet/dnx/issues/1067

@DamianEdwards reports:

>This is reproing again. See repro project at https://github.com/DamianEdwards/BundleExcludeLongPaths
>Clone that and try to dnu publish --out C:\o it from the command line.
>If you do dnu publish without specifying an --out arg, it fails in a different way as it tries to pack the output into itself (!!!) due to \bin not being excluded properly by default.

Exception details:

```
Using Project dependency BundleExcludeLongPaths 1.0.0 for DNX,Version=v4.5.1
  Copying source code from Project dependency BundleExcludeLongPaths
    Source C:\src\GitHub\DamianEdwards\BundleExcludeLongPaths\src\BundleExcludeLongPaths\project.json
    Target C:\src\GitHub\DamianEdwards\BundleExcludeLongPaths\src\BundleExcludeLongPaths\bin\output\approot\src\BundleEx
cludeLongPaths
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must
be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at System.IO.FileInfo.get_DirectoryName()
   at System.IO.FileInfo.get_Directory()
   at Microsoft.Framework.FileSystemGlobbing.Abstractions.FileInfoWrapper.get_ParentDirectory()
   at Microsoft.Framework.FileSystemGlobbing.Internal.PatternContexts.PatternContextRagged.TestMatchingGroup(FileSystemI
nfoBase value)
   at Microsoft.Framework.FileSystemGlobbing.Internal.PatternContexts.PatternContextRaggedInclude.Test(FileInfoBase file)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.<>c.<Match>b__10_1(IPatternContext pattern, FileInfoBase file)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.MatchPatternContexts[TFileInfoBase](TFileInfoBase fileinfo, Func`3 test)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Execute()
   at Microsoft.Framework.FileSystemGlobbing.Matcher.Execute(DirectoryInfoBase directoryInfo)
   at Microsoft.Framework.FileSystemGlobbing.MatcherExtensions.GetResultsInFullPath(Matcher matcher, String directoryPath)
   at Microsoft.Framework.Runtime.PatternGroup.SearchFiles(String rootPath)
   at Microsoft.Framework.PackageManager.Bundle.BundleProject.CopyProject(BundleRoot root, Project project, String targetPath, Boolean includeSource)
   at Microsoft.Framework.PackageManager.Bundle.BundleProject.EmitSource(BundleRoot root)
   at Microsoft.Framework.PackageManager.Bundle.BundleProject.Emit(BundleRoot root)
   at Microsoft.Framework.PackageManager.Bundle.BundleRoot.Emit()
   at Microsoft.Framework.PackageManager.Bundle.BundleManager.Bundle()
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_2.<Main>b__4()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
```

**Comment by troydai** [comment]
Fixed on both release and dev branch.
