### ISSUE TITLE
Failed publish/bundle returns 0 for exit code

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1527]
```
Error occurred while restoring NuGet packages: The method or operation is not implemented.
1>------ Build started: Project: WebApplication32, Configuration: Release Any CPU ------
Environment variables:
Path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\extensions\microsoft\web tools\external;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries/x86;C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\nodejs\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\Microsoft ASP.NET 5\Kvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\;C:\Users\davifowl\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta5-11400\bin;C:\Users\davifowl\.dnx\bin;C:\Users\davifowl\.k\runtimes\kre-clr-win-x86.1.0.0-beta4-11203\bin;C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Git\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\nodejs\;C:\Program Files\TortoiseGit\bin;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\;C:\Users\davifowl\AppData\Roaming\npm;C:\dev\tools\CLRProfiler\Binaries\32;C:\dev\tools\CLRProfiler\Binaries\64;C:\dev\tools\ILSpy;C:\dev\tools\Reflector;C:\dev\tools\VMMap;C:\Users\davifowl\AppData\Local\GitHub\PortableGit_015aa71ef18c047ce8509ffb2f9e4bb0e3e73f13\cmd;C:\Users\davifowl\AppData\Local\GitHub\PortableGit_015aa71ef18c047ce8509ffb2f9e4bb0e3e73f13\bin;C:\Users\davifowl\AppData\Local\GitHub\PortableGit_015aa71ef18c047ce8509ffb2f9e4bb0e3e73f13\mingw\bin;C:\Users\davifowl\AppData\Local\Apps\2.0\QCN913CD.PP0\QALOYVAL.KTB\gith..tion_317444273a93ac29_0001.0000_1d3d5ba77dd15d14;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Chocolatey\bin;C:\Python27;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\extensions\microsoft\web tools\external\.git
C:\Users\davifowl\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11400\bin\dnu.cmd publish "C:\Users\davifowl\Documents\Visual Studio 14\Projects\WebApplication32\src\WebApplication32" --out "C:\Users\davifowl\Documents\Visual Studio 14\Projects\WebApplication32\artifacts\obj\WebApplication32\Publish" --configuration Release --no-source --runtime dnx-clr-win-x86.1.0.0-beta5-11400 --wwwroot-out "wwwroot" --quiet
Information: [LoaderContainer]: Load name=Microsoft.Framework.PackageManager
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.PackageManager in 154ms
Information: [DependencyWalker]: Walking dependency graph for 'WebApplication32 DNX,Version=v4.5.1'.
Information: [WalkContext]: Graph walk stage 1 took in 46ms
Information: [DependencyWalker]: Graph walk took 54ms.
Information: [Breadcrumbs] Breadcrumbs for servicing will not be written because the breadcrumbs folder (C:\ProgramData\Microsoft DNX\BreadcrumbStore) does not exist.
Information: [ServicingIndex]: Servicing index not found at C:\Program Files (x86)\DNX\Servicing\index.txt
Information: [WalkContext]: Populate took 26ms
Information: [DependencyWalker]: Resolved dependencies for WebApplication32 in 84ms
Loaded Module: dnx.clr.dll
Found DLL Export: CallApplicationMain
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error : System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error :    at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error :    at System.IO.Path.GetDirectoryName(String path)
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error :    at Microsoft.Framework.PackageManager.Bundle.BundlePackage.Emit(BundleRoot root, IEnumerable`1 assemblies)
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error :    at Microsoft.Framework.PackageManager.Bundle.BundlePackage.Emit(BundleRoot root)
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error :    at Microsoft.Framework.PackageManager.Bundle.BundleRoot.Emit()
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error :    at Microsoft.Framework.PackageManager.Bundle.BundleManager.Bundle()
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error :    at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_3.<Main>b__6()
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error :    at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(137,5): Error :    at Microsoft.Framework.PackageManager.Program.Main(String[] args)

1>
1>  Build succeeded.
1>           0 Warning(s).
1>           0 Error(s).
1>
1>  Time elapsed 00:00:02.2134097
1>
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
```

**Comment by kirthik** [comment]
:+1:  Saw the same issue today on beta4 release bits. This is blocking publish scenario in VS if project is created at default path that VS suggests.

**Comment by davidfowl** [comment]
@muratg We need to fix this

**Comment by muratg** [comment]
@troydai it's OK to move this to beta7 if it doesn't fit

**Comment by troydai** [comment]
I'll look into the issue and estimate the size of the fix.

**Comment by troydai** [comment]
`11400` is a very old build, the code path shown above doesn't exist. I can't repo this with either latest `beta6` build or final `beta5` build. In both case the exit code is indeed 1.

Plus, VS's behavior is updated to. When VS publish it creates a temp folder instead of the artifact folder under current project folder which mitigate the long path issue.

**Comment by troydai** [comment]
@davidfowl @kirthik can you double check if you still can see this issue?

**Comment by kirthik** [comment]
Works for me.

**Comment by davidfowl** [comment]
Try 2 scenarios:
- introduce an exception in the publish code path and see what happens
- test dnu publish --no-source

**Comment by muratg** [comment]
I couldn't reproduce with dnu publish --no-source with the current bits either. I'll be testing with the final bits and close. Assigning to myself.

**Comment by jasonwilliams200OK** [comment]
Since 1.0.0-beta6 has been shipped, should the milestone of this issue be pushed to beta7 or beta8?

And regarding https://github.com/aspnet/dnx/milestones, please [close the ended milestones](https://github.com/blog/1536-simpler-milestone-workflow):

<img src="https://camo.githubusercontent.com/eb7aa68af0013f7104e5c7aaa76f82123ed80332/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f36392f3637313035342f62303836333736612d643835312d313165322d383439382d6434626538306133626535302e6a7067" />
