### ISSUE TITLE
What does this DNU exception mean?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/dnx#1665]
I ran into this exception trying to jockey my runtimes to only have only the CoreCLR x64 runtime installed on my Win7 box. Calling `dnu restore` triggers this.
```
Unable to find an entry point named 'GetVersion' in DLL 'api-ms-win-core-sysinfo-l1-2-1'.
at Microsoft.Framework.Runtime.NativeMethods.GetVersion_ApiSet()
at Microsoft.Framework.Runtime.NativeMethods.GetVersion()
at Microsoft.Framework.Runtime.NativeMethods.get_OSVersion()
at Microsoft.Framework.Runtime.RuntimeEnvironment...ctor()
at dnx.host.Bootstrapper.RunAsync(List`1 args)
at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

**Comment by davidfowl** [comment]
Means @victorhurdugaci caused a regression

**Comment by victorhurdugaci** [comment]
Ugh... that's my change from yesterday. I'll take a look

**Comment by victorhurdugaci** [comment]
Sent a PR with a fix
