### ISSUE TITLE
OS X - AnsiConsole threw an exception - does not support current color.

### ISSUE THREAD

**Issue by iamthemovie** [aspnet/dnx#1751]
I'm going to assume this is a CoreCLR issue with the PAL so I will post it here and also in the CoreCLR repo just in case.

Running ```dnu restore```  on my Mac with ```CoreCLR 1.0.0-beta5-11657``` and a basic blank ASP 5 application produces:

![screen shot 2015-04-30 at 16 01 05](https://cloud.githubusercontent.com/assets/369020/7415630/230ffbcc-ef52-11e4-9f1d-2f3a7c6584fb.png)

System.TypeInitializationException: The type initializer for 'Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole' threw an exception. ---> System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Framework.PackageManager.Program.CreateReports(Boolean verbose, Boolean quiet)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_1.<<Main>b__2>d.MoveNext()
System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()

**Comment by iamthemovie** [comment]
Looks like this has already been reported and closed and there are conversations in the CoreCLR repo discussing the issue. https://github.com/dotnet/coreclr/issues/882

**Comment by BrennanConroy** [comment]
Follow: #1724
