### ISSUE TITLE
dnu restore exception on osx yosemite

### ISSUE THREAD

**Issue by robertmircea** [aspnet/dnx#1768]
I am trying to run a `dnu restore` on Mac for a very simple dnxcore50 project. When executing the command at prompt in the project directory, I receive the following exception:

```bash
dnu restore
System.TypeInitializationException: The type initializer for 'Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole' threw an exception. ---> System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Framework.PackageManager.Program.CreateReports(Boolean verbose, Boolean quiet)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_1.<<Main>b__2>d.MoveNext()
System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
```

The project is configured under the following runtime:

```bash
dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta5-11682    coreclr x64  ~/.dnx/runtimes
       1.0.0-beta4          mono         ~/.dnx/runtimes      default
```

Any suggestion on how to do the package restore?

Thanks,
Robert

**Comment by davidfowl** [comment]
Dnu isn't supported on coreclr xplat yet. Use the mono  dnu

**Comment by robertmircea** [comment]
When I switched to mono, dnu restore did its job, but when I ran the app:

```bash
dnx . run
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   test 1.0.0

Searched Locations:
  /Users/robert/dev/{name}/project.json
  /Users/robert/.dnx/packages/{name}/{version}/{name}.nuspec
  /usr/local/Cellar/mono/4.0.1/lib/mono/4.5/{name}.dll
  /usr/local/Cellar/mono/4.0.1/lib/mono/4.5/Facades/{name}.dll

Try running 'dnu restore'.

  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
```

My `project.json` looks like this:

```bash
{
    "version": "1.0.0-*",
    "code": ["**/*.cs"],
    
	"frameworks" : {
        "dnxcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-22716"
            }
        }
    }
}
```

I just want to demo a simple app using `coreclr` on a Mac. Is this an option for the moment?

Regards,
Robert

**Comment by davidfowl** [comment]
Yes you almost got it working. Switch to mono run restore then switch back to coreclr to run. You'll probably run into other bugs but give it a try

**Comment by robertmircea** [comment]
David, I did this too. Sadly, it does not work either. It says I need to run again dnu restore which does not work.

When in CoreClr will be RTM, do I need to `dnx . run` even for a console app (will I be able to call the binary directly)? How can I distribute my app without the source code and still be able to run it on another computer?

One of my goals would be to build a Linux daemon (headless) app running with .Net coreclr. Also, in order to be a true Linux citizen, it would have to respond to Unix signals.

Is this type of apps subject to first .net coreclr version release?

**Comment by davidfowl** [comment]
Sometime before we ship. I don't have dates for you. We're no where near the release date as this is the first preview. I suggest you follow along with github.com/dotnet/coreclr and github.com/aspnet/dnx.

**Comment by davidfowl** [comment]
I missed some of your questions:

> David, I did this too. Sadly, it does not work either. It says I need to run again dnu restore which does not work.

If you get the same error you missed something. Show me the exact error you get when you ran it on coreclr.

> When in CoreClr will be RTM, do I need to dnx . run even for a console app (will I be able to call the binary directly)? How can I distribute my app without the source code and still be able to run it on another computer?

> Run dnu publish --no-source to get a self contained image. That will make a cmd file for windows and an executable script for *nix (this is similar to how node runs npm for example).

> One of my goals would be to build a Linux daemon (headless) app running with .Net coreclr. Also, in order to be a true Linux citizen, it would have to respond to Unix signals.

Unix signals are just APIs. If you want specific APIs then you should file issues on https://github.com/dotnet/corefx.

**Comment by robertmircea** [comment]
Regarding dnu restore issue on coreclr, here is the full output:

```bash
─robert at octo in ~/dev/test using
╰─○ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta5-11682    coreclr x64  ~/.dnx/runtimes
       1.0.0-beta4          mono         ~/.dnx/runtimes      default

╭─robert at octo in ~/dev/test using
╰─○ dnu restore
System.TypeInitializationException: The type initializer for 'Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole' threw an exception. ---> System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Framework.PackageManager.Program.CreateReports(Boolean verbose, Boolean quiet)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_1.<<Main>b__2>d.MoveNext()
System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()

╭─robert at octo in ~/dev/test using
╰─○ dnx . run
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNXCore,Version=v5.0':
   System.Console 4.0.0-beta-22716

Searched Locations:
  /Users/robert/dev/{name}/project.json

Try running 'dnu restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

`project.json` content is already on this thread above.

**Comment by davidfowl** [comment]
OK that's not what I said, try these exact commands:

```
dnvm install 1.0.0-beta5-11682 -u
dnu restore
dnvm use 1.0.0-beta5-11682 -r coreclr
dnx . run
```

**Comment by robertmircea** [comment]
```bash
╭─robert at octo in ~/dev/test using
╰─○ dnvm install 1.0.0-beta5-11682 -u
Downloading dnx-mono.1.0.0-beta5-11682 from https://www.myget.org/F/aspnetvnext/api/v2
Download: https://www.myget.org/F/aspnetvnext/api/v2/package/dnx-mono/1.0.0-beta5-11682
######################################################################## 100.0%
Installing to /Users/robert/.dnx/runtimes/dnx-mono.1.0.0-beta5-11682
Adding /Users/robert/.dnx/runtimes/dnx-mono.1.0.0-beta5-11682/bin to process PATH

─robert at octo in ~/dev/test using
╰─○ dnu restore
Restoring packages for /Users/robert/dev/test/project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Console'.
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Console' 1057ms
Writing lock file /Users/robert/dev/test/project.lock.json
Restore complete, 1285ms elapsed
╭─robert at octo in ~/dev/test using
╰─○ dnvm use 1.0.0-beta5-11682 -r coreclr
Adding /Users/robert/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta5-11682/bin to process PATH
╭─robert at octo in ~/dev/test using
╰─○ dnx . run
System.IO.FileLoadException: Resource string id=0x1A88
File name: 'test, Culture=neutral, PublicKeyToken=null' ---> System.TypeInitializationException: The type initializer for 'Roslyn.Utilities.SHA1CryptoServiceProvider' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Roslyn.Utilities.HashAlgorithm' threw an exception. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Roslyn.Utilities.HashAlgorithm..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.HashAlgorithm.LoadAlgorithmCreate(String name)
   at Roslyn.Utilities.SHA1CryptoServiceProvider..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.SHA1CryptoServiceProvider..ctor()
   at Microsoft.CodeAnalysis.CryptographicHashProvider.TryGetAlgorithm(SourceHashAlgorithm algorithmId)
   at Microsoft.CodeAnalysis.Text.SourceText.CalculateChecksum(Stream stream, SourceHashAlgorithm algorithmId)
   at Microsoft.CodeAnalysis.Text.SourceText.From(Stream stream, Encoding encoding, SourceHashAlgorithm checksumAlgorithm, Boolean throwIfBinaryDetected)
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.<>c__DisplayClass14_0.<CreateSyntaxTree>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.CreateSyntaxTree(String sourcePath, CSharpParseOptions parseOptions)
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.GetSyntaxTrees(ICompilationProject project, IEnumerable`1 sourceFiles, IEnumerable`1 sourceReferences, CSharpParseOptions parseOptions, Boolean isMainAspect)
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.CompileProject(ICompilationProject project, ILibraryKey target, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver)
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectCompiler.CompileProject(ICompilationProject project, ILibraryKey target, Func`1 referenceResolver, Func`1 resourcesResolver)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.<>c__DisplayClass5_0.<GetLibraryExport>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.<>c__DisplayClass2_0.<GetLibraryExport>b__0(ILibraryExportProvider r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.LibraryManager.GetLibraryExport(String name, String aspect)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(String name, IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(String name)
   at dnx.host.LoaderContainer.Load(String name)
   at dnx.host.DefaultLoadContext.LoadAssembly(String name)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(String name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
System.TypeInitializationException: The type initializer for 'Roslyn.Utilities.SHA1CryptoServiceProvider' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Roslyn.Utilities.HashAlgorithm' threw an exception. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Roslyn.Utilities.HashAlgorithm..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.HashAlgorithm.LoadAlgorithmCreate(String name)
   at Roslyn.Utilities.SHA1CryptoServiceProvider..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.SHA1CryptoServiceProvider..ctor()
   at Microsoft.CodeAnalysis.CryptographicHashProvider.TryGetAlgorithm(SourceHashAlgorithm algorithmId)
   at Microsoft.CodeAnalysis.Text.SourceText.CalculateChecksum(Stream stream, SourceHashAlgorithm algorithmId)
   at Microsoft.CodeAnalysis.Text.SourceText.From(Stream stream, Encoding encoding, SourceHashAlgorithm checksumAlgorithm, Boolean throwIfBinaryDetected)
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.<>c__DisplayClass14_0.<CreateSyntaxTree>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.CreateSyntaxTree(String sourcePath, CSharpParseOptions parseOptions)
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.GetSyntaxTrees(ICompilationProject project, IEnumerable`1 sourceFiles, IEnumerable`1 sourceReferences, CSharpParseOptions parseOptions, Boolean isMainAspect)
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.CompileProject(ICompilationProject project, ILibraryKey target, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver)
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectCompiler.CompileProject(ICompilationProject project, ILibraryKey target, Func`1 referenceResolver, Func`1 resourcesResolver)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.<>c__DisplayClass5_0.<GetLibraryExport>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.<>c__DisplayClass2_0.<GetLibraryExport>b__0(ILibraryExportProvider r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.LibraryManager.GetLibraryExport(String name, String aspect)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(String name, IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(String name)
   at dnx.host.LoaderContainer.Load(String name)
   at dnx.host.DefaultLoadContext.LoadAssembly(String name)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(String name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.TypeInitializationException: The type initializer for 'Roslyn.Utilities.HashAlgorithm' threw an exception. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Roslyn.Utilities.HashAlgorithm..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.HashAlgorithm.LoadAlgorithmCreate(String name)
   at Roslyn.Utilities.SHA1CryptoServiceProvider..cctor()
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Roslyn.Utilities.HashAlgorithm..cctor()
╭─robert at octo in ~/dev/test using
╰─○ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta5-11682    coreclr x64  ~/.dnx/runtimes
       1.0.0-beta4          mono         ~/.dnx/runtimes      default
       1.0.0-beta5-11682    mono         ~/.dnx/runtimes

```

**Comment by rkeithhill** [comment]
I'm running into a similar issue on Ubuntu trying to get a three line hello world console app to run on dnxcore50.  Except my stack trace complains that the "type initializer for 'libcrypto' threw an exception.".  But there are a number of references to SHA1 methods in the stack.

**Comment by robertmircea** [comment]
I've upgraded to the latest version (on OSX), the message for `dnu restore` has changed into this:

```bash
dnvm install latest -r coreclr -u
Determining latest version
Latest version is 1.0.0-beta5-11744
dnx-coreclr-darwin-x64.1.0.0-beta5-11744 already installed.
Adding /Users/robert/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta5-11744/bin to process PATH
╭─robert at octo in ~/dev/test using
╰─○ dnu restore
----------
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at NuGet.Settings.LoadDefaultSettings(IFileSystem fileSystem, String configFileName, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.SettingsUtils.ReadSettings(String solutionDir, String nugetConfigFile, IFileSystem fileSystem, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.RestoreCommand.ReadSettings(String solutionDirectory)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__68.MoveNext()
----------
Restore failed
Value cannot be null.
Parameter name: path1
```

**Comment by rkeithhill** [comment]
I'm on 11744 on Ubuntu and I still had to use mono to do the package restore.  That should work though.  However, running my console app under coreclr beta5 11744 did not work.

**Comment by nickserv** [comment]
Try running it through the artifacts generated by `dnu publish`.
