### ISSUE TITLE
dnu restore on core clr using linux fails on getting the console color

### ISSUE THREAD

**Issue by vlesierse** [aspnet/dnx#1785]
While adjusting the CI tests for the Docker image I encountered a problem with `dnu restore` on the Core CLR version of dnx using Linux.

See PR: https://github.com/aspnet/aspnet-docker/pull/57

```
System.TypeInitializationException: The type initializer for 'Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole' threw an exception. ---> System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Framework.PackageManager.Program.CreateReports(Boolean verbose, Boolean quiet)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_1.<<Main>b__2>d.MoveNext()
System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
```

**Comment by davidfowl** [comment]
Yea dnu doesn't work on core clr. You need mono. It'll be a while before it works.

**Comment by natemcmaster** [comment]
Why not just die gracefully here?

**Comment by natemcmaster** [comment]
nvm -- we will work around this in ef.
