### ISSUE TITLE
ArgumentException when there are quotes in comments in global.json

### ISSUE THREAD

**Issue by dsplaisted** [aspnet/dnx#1788]
Create a new DNX app project.  Put the following in global.json

```
{
    "projects": [
        "src",
        //"
        "test"
    ]
}
```

Build the project (ie `dnu build`).

**EXPECTED:** Build is successful
**ACTUAL:** Build fails with "System.ArgumentException: Illegal characters in path."  Also note that the exception doesn't have any context to help you figure out what file this is coming from so you could work around this.

```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Framework.Runtime.ProjectResolver.Initialize(String projectPath, String rootPath)
   at Microsoft.Framework.Runtime.ProjectResolver..ctor(String projectPath, String rootPath)
   at Microsoft.Framework.Runtime.ApplicationHostContext..ctor(IServiceProvider serviceProvider, String projectDirectory, String packagesDirectory, String configuration, FrameworkName targetFramework, ICache cache, ICacheContextAccessor cacheContextAccessor, INamedCacheDependencyProvider namedCacheDependencyProvider, IAssemblyLoadContextFactory loadContextFactory, Boolean skipLockFileValidation)
   at Microsoft.Framework.PackageManager.BuildContext.GetRuntimeLoadContextFactory(Project project)
   at Microsoft.Framework.PackageManager.BuildContext.<>c__DisplayClass16_0.<GetApplicationHostContext>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Framework.Runtime.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.PackageManager.BuildContext.GetApplicationHostContext(Project project, FrameworkName targetFramework, String configuration)
   at Microsoft.Framework.PackageManager.BuildContext..ctor(IServiceProvider hostServices, IApplicationEnvironment appEnv, ICache cache, ICacheContextAccessor cacheContextAccessor, Project project, FrameworkName targetFramework, String configuration, String outputPath)
   at Microsoft.Framework.PackageManager.BuildManager.Build()
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_4.<Main>b__8()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
```

**Comment by ChengTian** [comment]
Thanks for reporting this. We are removing support for comments in our JSON parser: https://github.com/aspnet/dnx/issues/1816

 and this issue will become invalid after we finish it.

**Comment by muratg** [comment]
Dup: https://github.com/aspnet/dnx/issues/1816
