### ISSUE TITLE
dnu restore throws ArgumentNullException on Coreclr on a Mac

### ISSUE THREAD

**Issue by akamud** [aspnet/dnx#1790]
I am trying to run `dnu restore` from a terminal client with 1.0.0-beta5-11706 coreclr x64 on a Mac, but I get an error every time.

```
----------
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at NuGet.Settings.LoadDefaultSettings(IFileSystem fileSystem, String configFileName, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.SettingsUtils.ReadSettings(String solutionDir, String nugetConfigFile, IFileSystem fileSystem, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.RestoreCommand.ReadSettings(String solutionDirectory)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__68.MoveNext()
----------
Restore failed
Value cannot be null.
Parameter name: path1
```
I am running the HelloMvc application sample.
If I run `dnu restore` on mono it restores the packages successfully.

**Comment by BrennanConroy** [comment]
Most, if not all, dnu related commands are not going to work on Non-Windows CoreCLR. This is a known issue and we are working on getting them ready.

**Comment by akamud** [comment]
I see, I just realized the coreclr documentation says you should switch to mono before running `restore`.
Maybe we could put some more information or emphasis on this info?

**Comment by BrennanConroy** [comment]
Closing, this is being tracked by #1793
