### ISSUE TITLE
dnu commands install secretmanager - null value passed to path.combine

### ISSUE THREAD

**Issue by timmydo** [aspnet/dnx#1808]
```
> dnu --version
1.0.0-beta5-11596

PS C:\users\timmy\Source\Repos\GearUp> dnu commands uninstall user-secret
user-secret command has been uninstalled
PS C:\users\timmy\Source\Repos\GearUp> dnu commands install secretmanager
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='secretmanager'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='secretmanager'.
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='secretmanager' 386ms
  OK https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='secretmanager' 1083ms
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Framework.PackageManager.InstallGlobalCommand.CreateTemporaryProject(String installFolder, String packag
eName, String packageVersion)
   at Microsoft.Framework.PackageManager.InstallGlobalCommand.<Execute>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass4_12.<<Main>b__24>d.MoveNext()

**Comment by BrennanConroy** [comment]
fixed with: 7b8e7bc5e723f704e9e1950ba2ecfcd814b49b3b
