### ISSUE TITLE
Dnu publish generates non runnable bundle

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1839]
1. Clone MusicStore or clean it if it is already on your machine then sync to the latest
2. Install the following 2 runtimes, both CoreCLR/x64:
    - `1.0.0-beta5-11706`
    - `1.0.0-beta5-11749`
3. Start with `11706` and do the following:
4. `dnu restore` in MusicStore root
5. Go to `test\MusicStore.Test`
6. Run `dnu publish --runtime active`
7. Go to `bin\output` and run `test.cmd`
8. Result: everything works
9. Switch to runtime `11749` and repeat steps 4-7
10. Result:

```
System.InvalidOperationException: Unable to load application or execute command 'xunit.runner.aspnet'. Available command
s: test. ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT:
0x80070003)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String
niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.Framework.Runtime.Loader.NuGetAssemblyLoader.Load(String name, IAssemblyLoadContext loadContext)
   at dnx.host.LoaderContainer.Load(String name)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(String name, Func`2 factory)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

   --- End of inner exception stack trace ---
   at Microsoft.Framework.ApplicationHost.Program.ThrowEntryPointNotfoundException(DefaultHost host, String applicationN
ame, Exception innerException)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String
niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.Framework.Runtime.Loader.NuGetAssemblyLoader.Load(String name, IAssemblyLoadContext loadContext)
   at dnx.host.LoaderContainer.Load(String name)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(String name, Func`2 factory)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

It seems that one of the checkins between those two build broke the `publish` command.
The Nano server automation caught this bug and now it is blocked by it.

**Comment by victorhurdugaci** [comment]
cc @ChengTian

**Comment by davidfowl** [comment]
This has to do with my changes to publish. Does it run when you publish a simpler app?

**Comment by victorhurdugaci** [comment]
Nope. For the empty web application I get:

```
System.InvalidOperationException: Unable to load application or execute command 'Microsoft.AspNet.Hosting'. Available co
mmands: web. ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESU
LT: 0x80070003)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String
niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.Framework.Runtime.Loader.NuGetAssemblyLoader.Load(String name, IAssemblyLoadContext loadContext)
   at dnx.host.LoaderContainer.Load(String name)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(String name, Func`2 factory)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

   --- End of inner exception stack trace ---
   at Microsoft.Framework.ApplicationHost.Program.ThrowEntryPointNotfoundException(DefaultHost host, String applicationN
ame, Exception innerException)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String
niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.Framework.Runtime.Loader.NuGetAssemblyLoader.Load(String name, IAssemblyLoadContext loadContext)
   at dnx.host.LoaderContainer.Load(String name)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(String name, Func`2 factory)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

**Comment by victorhurdugaci** [comment]
@davidfowl is you fixed supposed to fix the publish bug? I'm still seeing the failure: https://xplat-ci.asp.net/viewLog.html?buildId=511&buildTypeId=XPlat_Windows_WinNanoServer_MusicStore&tab=buildLog
