### ISSUE TITLE
CommandLineUtils: ShowHelp throws NRE

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#1859]
(Originally opened in the EF repo: https://github.com/aspnet/EntityFramework/issues/2178)

`dnx . ef help add`

throws

```
                     _/\__
               ---==/    \\
         ___  ___   |.    \|\
        | __|| __|  |  )   \\\
        | _| | _|   \_/ |  //|\\
        |___||_|       /   \\\/\\

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.ShowHelp(String commandName)
   at Microsoft.Data.Entity.Commands.Program.ShowHelp(String command)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_8.<Main>b__19()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
```
on
     *    1.0.0-beta4 clr     x86

**Comment by bricelam** [comment]
Same bug is manifest if you do `dnu help blah`.

**Comment by muratg** [comment]
@victorhurdugaci

**Comment by victorhurdugaci** [comment]
Oh no, the unicorn null refs :smile:

**Comment by moozzyk** [comment]
@victorhurdugaci only the head of the unicorn we don't know about the rest of it...
