### ISSUE TITLE
Can't get hello world console app running on Ubuntu, CoreCLR latest

### ISSUE THREAD

**Issue by rkeithhill** [aspnet/dnx#1861]
I should be able to get this simple little console app to run on Linux, right?

```c#
public class App {
    public static void Main() {
        System.Console.WriteLine("Hello World");
    }
}
```
with this project.json file:
```json
{
  "version": "1.0.0-*",
  "dependencies": {},
  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "System.Console": "4.0.0-*"
      }
    }
  }
}
```
I'm running version 1.0.0-beta5-11760 coreclr x64 (that's my default alias).  I have installed mono-complete so that I can run dnu restore which works.  It pulls down System.Console 4.0.0-beta-22911.  However when I switch back to 1.0.0-beta5-11760 coreclr x64, and execute dnx . run from my project.json folder I get this error:

```
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNXCore, Version=v5.0':
    System.Console 4.0.0

Search Locations:
  /home/hillr/src/{name}/project.json

Try running 'dnu restore'.

  at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
  ...
```

I managed to get this same project running on Windows 10 with .NET CoreClr.  

BTW where is corerun and how do you use it.  I saw Habib use this in his session at Build but I don't see this file anywhere in the .dnx folder or perhaps I'm just using find/grep wrong. :-)

**Comment by davidfowl** [comment]
@rkeithhill The fact that searched locations doesn't have the packages folder location makes me feel like it's something to do with the lock file version. Our error handling for this scenario is quite bad (https://github.com/aspnet/dnx/issues/1469). What's the version in the `project.lock.json` file?

**Comment by rkeithhill** [comment]
Here's the entire project.lock.json file:

```json
{
  "locked": false,
  "version": -9998,
  "projectFileDependencyGroups": {
    "": [],
    "DNXCore,Version=v5.0": [
      "System.Console >= 4.0.0-*"
    ]
  },
  "libraries": {
    "System.Console/4.0.0-beta-22911": {
      "serviceable": false,
      "sha": "aIc52VdBLL/iFsrMoVCnWHTi6aFHidNA5yvuczfd1GEP2GcPIXUUY0gL9g5DKPceKCjDbIx8Mklcs+JR/GhJzg==",
      "frameworks": {
        "DNXCore,Version=v5.0": {
          "dependencies": {
            "System.IO": "4.0.0-beta-22911",
            "System.Runtime": "4.0.0-beta-22911"
          },
          "frameworkAssemblies": [],
          "runtimeAssemblies": [
            "lib/aspnetcore50/System.Console.dll"
          ],
          "compileAssemblies": [
            "lib/contract/System.Console.dll"
          ]
        }
      },
      "files": [
        "License.rtf",
        "System.Console.4.0.0-beta-22911.nupkg",
        "System.Console.4.0.0-beta-22911.nupkg.sha512",
        "System.Console.nuspec",
        "lib/aspnetcore50/System.Console.dll",
        "lib/contract/System.Console.dll",
        "lib/net45/System.Console.dll",
        "lib/portable-wpa81+wp80+win80+net45+aspnetcore50/System.Console.dll"
      ]
    },
    "System.IO/4.0.10-beta-22516": {
      "serviceable": false,
      "sha": "MUI4VYWN15a1P4/3TS8IWZL5sJFHtZtegpQqWIXFn7mYIwAE+G5yR4Zi8wNeHU6f2yniX/SVm3+s5Is5ro2C6Q==",
      "frameworks": {
        "DNXCore,Version=v5.0": {
          "dependencies": {
            "System.Runtime": "4.0.20-beta-22516",
            "System.Text.Encoding": "4.0.0-beta-22516",
            "System.Threading.Tasks": "4.0.0-beta-22516"
          },
          "frameworkAssemblies": [],
          "runtimeAssemblies": [
            "lib/aspnetcore50/System.IO.dll"
          ],
          "compileAssemblies": [
            "lib/contract/System.IO.dll"
          ]
        }
      },
      "files": [
        "License.rtf",
        "System.IO.4.0.10-beta-22516.nupkg",
        "System.IO.4.0.10-beta-22516.nupkg.sha512",
        "System.IO.nuspec",
        "lib/aspnetcore50/System.IO.dll",
        "lib/contract/System.IO.dll",
        "lib/net45/System.IO.dll",
        "lib/portable-wpa81+wp80+win80+net45+aspnetcore50/System.IO.dll"
      ]
    },
    "System.Runtime/4.0.20-beta-22516": {
      "serviceable": false,
      "sha": "hcvKEB39EXyVhx9U6F2+FdOmca1OtOcmadLJmqWoUWbF8ltOVNR252GXxTKY2TICNAxwFJT2JW3EfvICgOHJ7w==",
      "frameworks": {
        "DNXCore,Version=v5.0": {
          "dependencies": {},
          "frameworkAssemblies": [],
          "runtimeAssemblies": [
            "lib/aspnetcore50/System.Runtime.dll"
          ],
          "compileAssemblies": [
            "lib/contract/System.Runtime.dll"
          ]
        }
      },
      "files": [
        "License.rtf",
        "System.Runtime.4.0.20-beta-22516.nupkg",
        "System.Runtime.4.0.20-beta-22516.nupkg.sha512",
        "System.Runtime.nuspec",
        "lib/aspnetcore50/System.Runtime.dll",
        "lib/contract/System.Runtime.dll",
        "lib/net45/System.Runtime.dll",
        "lib/portable-wpa81+wp80+win80+net45+aspnetcore50/System.Runtime.dll"
      ]
    },
    "System.Text.Encoding/4.0.10-beta-22516": {
      "serviceable": false,
      "sha": "7f3KissSbO9xM1gwSdwMDmG53TYgHG9dNG4zFrkLrRP3ioQe7c+t7wkwPVA1ihiEvEVTLeKW9JnDS+L5PQ144Q==",
      "frameworks": {
        "DNXCore,Version=v5.0": {
          "dependencies": {
            "System.Runtime": "4.0.0-beta-22516"
          },
          "frameworkAssemblies": [],
          "runtimeAssemblies": [
            "lib/aspnetcore50/System.Text.Encoding.dll"
          ],
          "compileAssemblies": [
            "lib/contract/System.Text.Encoding.dll"
          ]
        }
      },
      "files": [
        "License.rtf",
        "System.Text.Encoding.4.0.10-beta-22516.nupkg",
        "System.Text.Encoding.4.0.10-beta-22516.nupkg.sha512",
        "System.Text.Encoding.nuspec",
        "lib/aspnetcore50/System.Text.Encoding.dll",
        "lib/contract/System.Text.Encoding.dll",
        "lib/net45/System.Text.Encoding.dll",
        "lib/portable-wpa81+wp80+win80+net45+aspnetcore50/System.Text.Encoding.dll"
      ]
    },
    "System.Threading.Tasks/4.0.10-beta-22516": {
      "serviceable": false,
      "sha": "y+sIpjPvqOODL6fmU8ABrQAvcvc8z6Itt59DrKAdxRtndz7rCaYyReri9IpueQoxkovfxe/tbBQA/lGr2yPlpg==",
      "frameworks": {
        "DNXCore,Version=v5.0": {
          "dependencies": {
            "System.Runtime": "4.0.0-beta-22516"
          },
          "frameworkAssemblies": [],
          "runtimeAssemblies": [
            "lib/aspnetcore50/System.Threading.Tasks.dll"
          ],
          "compileAssemblies": [
            "lib/contract/System.Threading.Tasks.dll"
          ]
        }
      },
      "files": [
        "License.rtf",
        "System.Threading.Tasks.4.0.10-beta-22516.nupkg",
        "System.Threading.Tasks.4.0.10-beta-22516.nupkg.sha512",
        "System.Threading.Tasks.nuspec",
        "lib/aspnetcore50/System.Threading.Tasks.dll",
        "lib/contract/System.Threading.Tasks.dll",
        "lib/net45/System.Threading.Tasks.dll",
        "lib/portable-wpa81+wp80+win80+net45+aspnetcore50/System.Threading.Tasks.dll"
      ]
    }
  }
}
```

**Comment by davidfowl** [comment]
That's indeed the problem. You are restoring with a very very old version of dnu restore on mono. You said this:

> I have installed mono-complete so that I can run dnu restore which work.

Make sure you use the same version, in this case `dnx-mono.1.0.0-beta5-11760`

**Comment by rkeithhill** [comment]
Well, now I get a different error.  I guess that is progress. :-)

```
hillr@hillr1-vm-ubu64:~/src/hello$ dnx . run
System.IO.FileLoadException: 1A88
File name: 'hello, Culture=neutral, PublicKeyToken=null' ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'libcrypto' threw an exception. ---> System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Interop.libcrypto..cctor()
...
```

**Comment by rkeithhill** [comment]
Hmm, seems I need to into libssl-dev.  Off to figure out how to do that.

**Comment by rkeithhill** [comment]
OK got libssl-dev installed and I no longer get the libcrpto errors.  However now I get:

'hello' does not contain a static 'Main' method suitable for an entry point

I suspect my program.cs file is not being found and consequently not compiled.  Do I need to specify cs files in the project.json file?  I tried "code": "**/*.cs", but that didnt' help.

**Comment by davidfowl** [comment]
Take a look at the samples on the home repository and copy them verbatim

**Comment by rkeithhill** [comment]
OK, that does work - finally!  Thanks. Now I need to figure out what it was about my original project.json file that was a bit off.
