### ISSUE TITLE
Uninstall Package from ASP.NET Class Library Fail

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/dnx#1910]
reported by @csharpfritz on March 18, 2015 https://github.com/NuGet/Home/issues/248

Added a package to a Project K Class library, immediately attempted to uninstall and errors.

Steps to reproduce:

Create ASP.NET Class Library project
Using NuGet UI add NUnit to project
Without closing UI, immediately attempt to remove NUnit
Project.json file still contains a dependency entry for NUnit.

Errors reported:
System.ArgumentException: Package 'NUnit' to be uninstalled could not be found in project 'ClassLibrary1'
at NuGet.PackageManagement.NuGetPackageManager.d__cd.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.UI.UIActionEngine.d__2f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.UI.UIActionEngine.d__0.MoveNext()
========== Finished ==========

**Comment by davidfowl** [comment]
Should be filed on tooling.

**Comment by yishaigalatzer** [comment]
Github needs a move this issue feature :)
