### ISSUE TITLE
dnu restore fails when source not reachable

### ISSUE THREAD

**Issue by TanukiSharp** [aspnet/dnx#1952]
### dnu restore fails when source not reachable

`dnu restore` reports an error and thus stops the restore process when a local package source from a `NuGet.config` file is not reachable.

If a `NuGet.config` file contains a package source defined as a shared folder and that folder is not reachable at the moment (for example, a VPN connection not active) a `FileNotFoundException` is displayed and the process stops.
### Functional impact

The packages restore process is interupted too early.
### Minimal repro steps
- 1) Add a correctly formatted inexistant shared folder package source to `%AppData%\NuGet\NuGet.config`, such as:
  
  ```
  <?xml version="1.0" encoding="utf-8"?>
  <configuration>
      <packageRestore>
          <add key="enabled" value="True" />
          <add key="automatic" value="True" />
      </packageRestore>
      <packageSources>
          <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
          <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2/" />
  
          <!-- The problem happens here -->
          <add key="My Custom Feed" value="\\company-server\not\available" />
  
      </packageSources>
      <activePackageSource>
          <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
      </activePackageSource>
  </configuration>
  ```
- 2) Run `dnu restore` pretty much any where there is a valid project.json file.
### Expected result

The `dnu restore` tool should output a warning instead of an error and keep going the process.  
### Actual result

The `dnu restore` process is interupted, whereas it should (because it could) go on.

Hereafter is the full output:

```
C:\Users\Sebastien\AspNetSampleApp03>dnu restore
Restoring packages for C:\Users\Sebastien\AspNetSampleApp03\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Console'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Console'
Error: FindPackagesById: System.Console
  The local package source \\wrong-server\wrong\path doesn't exist
----------
System.IO.FileNotFoundException: The local package source \\wrong-server\wrong\path doesn't exist
File name: '\\wrong-server\wrong\path'
   at Microsoft.Framework.PackageManager.Restore.NuGet.PackageFolder.FindPackagesByIdAsync(String id)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass73_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__73.MoveNext()
----------
Restore failed
The local package source \\wrong-server\wrong\path doesn't exist
```
### Fix proposals
1. Output a warning instead of an error.
2. Ignore the package source is unavailable. (probably a not so good idea)
3. Add a `skipIfUnavailable="true"` attribute to the `add` element of the `packageSources` element of the `NuGet.config` file.
4. Add a `--ignore-source <key>` option to the `restore` action of `dnu`. This would completly skip the `<key>` package source.
5. Add a `--ignore-unavailable-source <key>` option to the `restore` action of `dnu`. This would skip the `key` package source if it does not respond.
6. Add a `--ignore-unavailable-sources` option to the `restore` action of `dnu`. This would skip any package source that does not respond.

**Comment by BrennanConroy** [comment]
We have ```--ignore-failed-sources```, did you try that?

**Comment by muratg** [comment]
@TanukiSharp (6) is actually available (see @BrennanConroy's comment above).  

(1) and (2)  -- bad idea, because based on the state of the sources, you may end up getting different versions of the packages and never know it.  

Let us know if you have issues after using that command line switch.

**Comment by TanukiSharp** [comment]
Yes `--ignore-failed-sources` works perfectly, and I actually found it out after through `dnu help restore`.
Sorry for the troubles.

**Comment by shaneholder** [comment]
I just ran into this also.  It might be nice if dnu printed that option on this error.  I have a work repository configured in my Nuget.config file and was just starting to work with dnx and ran into this issue on a hello world project which would never have pulled any assemblies from that repo.

**Comment by muratg** [comment]
@shaneholder Would you rather not fix your nuget.config?  Or did you mean just displaying the error, and also giving a helpful suggestion of using this option?

**Comment by shaneholder** [comment]
The nuget.config I was looking at is scoped to my user, not the project (I set  it in VS2015) %AppData%\Roaming\Nuget.config.  So, IMHO there is nothing to "fix" but I meant to display the error and give a helpful suggestion.

**Comment by muratg** [comment]
Reactivating based on @shaneholder's suggestion to give a helpful suggestion when there's a problem with one of the package sources in nuget.config, and adding it to the list of bugs that can be potentially moved to nuget.

cc @yishaigalatzer @emgarten
