### ISSUE TITLE
building succeeds but running fails on os x

### ISSUE THREAD

**Issue by cnblogs-dudu** [aspnet/dnx#1955]
Building dnx succeeds on os x.Then get dnx-mono and dnx-coreclr-darwin-x64 in artifacts/build.
Run HelloDnx sample .NET Console App with dnx-mono.
```
/Git/dotnet/dnx/artifacts/build/dnx-mono/bin/dnx . run
```
It succeeds.
But run with dnx-coreclr-darwin-x64.
```
/Git/dotnet/dnx/artifacts/build/dnx-coreclr-darwin-x64/bin/dnx . run
```
It fails.
```
Resource string id=0x17FC System.DllNotFoundException: Resource string id=0x170B
   at Interop.mincore.GetStdHandle(Int32 nStdHandle)
   at System.Console.<>c__DisplayClass0.<get_Error>b__5()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at dnx.host.RuntimeBootstrapper.PrintErrors(Exception ex)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
   at DomainManager.Execute(Int32 argc, Char** argv)
```
Program.cs in HelloDnx:
```csharp
using System;

public class Program
{
    public static void Main()
    {
        Console.WriteLine("Hello from DNX!");
    }
}
```
project.json in HelloDnx:
```
{
    "dependencies":{
    },
    "frameworks":{
        "dnx451":{},
        "dnxcore50":{}
    }
}
```

**Comment by BrennanConroy** [comment]
There is an issue with the latest CoreCLR bits on cross-plat CoreCLR, if you want a temporary solution use CoreCLR 1.0.0-beta5-10405 instead of 10407
