### ISSUE TITLE
Package restore is broken in CoreClr/1.0.0-beta6-12005 on Linux

### ISSUE THREAD

**Issue by kasthack** [aspnet/dnx#2037]
```
kasthack@kashack-desktop:~/Home/samples/ConsoleApp$ dnx . run
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNXCore,Version=v5.0':
   System.Console 4.0.0-beta-22605

Searched Locations:
  /root/Home/samples/{name}/project.json
  /root/.dnx/packages/{name}/{version}/{name}.nuspec

Try running 'dnu restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
kasthack@kashack-desktop:~/Home/samples/ConsoleApp$ dnu restore
Microsoft .NET Development Utility CoreCLR-x64-1.0.0-beta6-12005

----------
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at NuGet.Settings.LoadDefaultSettings(IFileSystem fileSystem, String configFileName, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.SettingsUtils.ReadSettings(String solutionDir, String nugetConfigFile, IFileSystem fileSystem, IMachineWideSettings
   at Microsoft.Framework.PackageManager.RestoreCommand.ReadSettings(String solutionDirectory)
   at Microsoft.Framework.PackageManager.RestoreCommand.<Execute>d__76.MoveNext()
----------
Restore failed
Value cannot be null.
Parameter name: path1
```

DNX [tries](https://github.com/aspnet/dnx/blob/e937e25ab3453ea86bda13c1297c41011dfda9de/src/Microsoft.Framework.PackageManager/NuGet/Core/Configuration/Settings.cs#L107
) to get APPDATA environment variable. It's null by default.

After setting APPDATA:

```
kasthack@kashack-desktop:~/Home/samples/ConsoleApp$ export APPDATA='/root/.config'
kasthack@kashack-desktop:~/Home/samples/ConsoleApp$ dnu -v restore
Microsoft .NET Development Utility CoreCLR-x64-1.0.0-beta6-12005

----------
System.ArgumentNullException: Value cannot be null.
Parameter name: root
   at NuGet.PhysicalFileSystem..ctor(String root)
   at NuGet.CommandLineMachineWideSettings.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at NuGet.CommandLineMachineWideSettings.get_Settings()
   at NuGet.Settings.LoadDefaultSettings(IFileSystem fileSystem, String configFileName, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.SettingsUtils.ReadSettings(String solutionDir, String nugetConfigFile, IFileSystem fileSystem, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.RestoreCommand.ReadSettings(String solutionDirectory)
   at Microsoft.Framework.PackageManager.RestoreCommand.<Execute>d__76.MoveNext()
----------
Restore failed
Value cannot be null.
Parameter name: root

```

Works fine with mono as runtime.

**Comment by davidfowl** [comment]
Package restore does not work on linux on coreclr see https://github.com/aspnet/dnx/issues/1793

**Comment by kasthack** [comment]
```
kasthack@kashack-desktop:~/Home/samples/ConsoleApp$ dnvm use 1.0.0-beta6-12005 -r mono

Adding /root/.dnx/runtimes/dnx-mono.1.0.0-beta6-12005/bin to process PATH

kasthack@kashack-desktop:~/Home/samples/ConsoleApp$ dnu restore

Microsoft .NET Development Utility Mono-x64-1.0.0-beta6-12005

Restoring packages for /root/Home/samples/ConsoleApp/project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console'.
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console' 1923ms
  GET https://www.nuget.org/api/v2/package/System.Console/4.0.0-beta-22816.
  OK https://www.nuget.org/api/v2/package/System.Console/4.0.0-beta-22816 1279ms
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO'
  GET https://www.nuget.org/api/v2/package/System.IO/4.0.10-beta-22816.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://www.nuget.org/api/v2/package/System.Runtime/4.0.20-beta-22816.
  OK https://www.nuget.org/api/v2/package/System.IO/4.0.10-beta-22816 329ms
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding'
  GET https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.10-beta-22816.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks'
  GET https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.10-beta-22816.
  OK https://www.nuget.org/api/v2/package/System.Runtime/4.0.20-beta-22816 586ms
  OK https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.10-beta-22816 377ms
  OK https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.10-beta-22816 590ms
Installing System.Console.4.0.0-beta-22816
Installing System.Runtime.4.0.20-beta-22816
Installing System.IO.4.0.10-beta-22816
Installing System.Text.Encoding.4.0.10-beta-22816
Installing System.Threading.Tasks.4.0.10-beta-22816
Writing lock file /root/Home/samples/ConsoleApp/project.lock.json
Restore complete, 6003ms elapsed

kasthack@kashack-desktop:~/Home/samples/ConsoleApp$ dnvm use 1.0.0-beta6-12005 -r coreclr

Adding /root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta6-12005/bin to process PATH
root@morg-linux-hosting:~/Home/samples/ConsoleApp# dnx . run
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNXCore,Version=v5.0':
   System.Console 4.0.0-beta-22816

Searched Locations:
  /root/Home/samples/{name}/project.json
  /root/.dnx/packages/{name}/{version}/{name}.nuspec

Try running 'dnu restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```
