### ISSUE TITLE
"dnu restore" doesn't support authenticated feeds

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2056]
For example, the feed you can access when you are domain-joined.

**Comment by bencyoung** [comment]
Effects us too:

  Response status code does not indicate success: 401 (Unauthorized).
  GET http://adpbuildsrv:81/nuget/Internal/FindPackagesById()?id=...
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

**Comment by pranavkm** [comment]
Might also want to port over federated auth support (https://github.com/NuGet/NuGet3/blob/dev/src/NuGet.Protocol.Core.v3/RemoteRepositories/STSAuthHelper.cs) that NuGet supports. The APIs to work with these don't exist in CoreCLR though.

**Comment by Kieranties** [comment]
Any news on when this issue may move forward?  It's not assigned to a milestone at the moment.

**Comment by nuevoalex** [comment]
This is more or less blocking adoption of DNX for the project I'm currently working on so some response to this would be great.

**Comment by slaneyrw** [comment]
This isn't just a NuGet bug, there is also a problem in your NuGetv2Feed class not handling the 401 exception

    System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
       at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
       at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource.<GetAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at Microsoft.Dnx.Tooling.Restore.NuGet.NuGetv2Feed.<FindPackagesByIdAsyncCore>d__25.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Dnx.Tooling.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()

    <snip>

**Comment by StenPetrov** [comment]
Why is this still open 2 years later? What's the advised work-around?

**Comment by davidfowl** [comment]
Please open an issue on nuget, dnx has been dead for over a year now.
