### ISSUE TITLE
dnu commands install possibly doesn't resolve correct dependency versions

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/dnx#2149]
I am seeing this issue on Windows 8.1, I didn't try on any other platform.

Even if I fix the versions on my project.json, `dnu commands install` doesn't ensure that it resolves the correct versions. It could be doing something wrong but it still seems odd to me. This is the source code where I see the issue: https://github.com/tugberkugurlu/k-http/tree/0.1.0-beta-003

Repro steps: 

 - ensure that you are on dnx v`1.0.0-beta5-11611`
 - run: `dnu commands install k-http --source "https://www.myget.org/F/aspnetvnext/api/v2" --source "https://nuget.org/api/v2/"`
 - run `k-http`

What I am getting is the below error:

````
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Fram
ework.ConfigurationModel.Abstractions, Version=1.0.0.0, Culture=neutral, PublicK
eyToken=null' or one of its dependencies. The system cannot find the file specif
ied.
File name: 'Microsoft.Framework.ConfigurationModel.Abstractions, Version=1.0.0.0
, Culture=neutral, PublicKeyToken=null' ---> System.IO.FileNotFoundException: Co
uld not load file or assembly 'Microsoft.Framework.ConfigurationModel.Abstractio
ns' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Framework.ConfigurationModel.Abstractions'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String cod
eBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&
stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntro
spection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String code
Base, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& s
tackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntros
pection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName as
semblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIn
trospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evid
ence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolea
n forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evid
ence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Load(String name)
   at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly(Object send
er, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String a
ssemblyFullName)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\M
icrosoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure lo
gging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fus
ion!EnableLog].

   at KHttp.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly ass
embly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly ass
embly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)


System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Fram
ework.ConfigurationModel.Abstractions' or one of its dependencies. The system ca
nnot find the file specified.
File name: 'Microsoft.Framework.ConfigurationModel.Abstractions'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String cod
eBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&
stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntro
spection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String code
Base, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& s
tackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntros
pection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName as
semblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIn
trospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evid
ence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolea
n forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evid
ence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Load(String name)
   at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly(Object send
er, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String a
ssemblyFullName)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\M
icrosoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure lo
gging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fus
ion!EnableLog].
```

**Comment by tugberkugurlu** [comment]
I ran `dnu list` under `C:\Users\Tugberk\.dnx\bin\packages\k-http\0.1.0-beta-003\app` and got this output:

```
Listing dependencies for app (C:\Users\Tugberk\.dnx\bin\packages\k-http\0.1.0-be
ta-003\app\project.json)

[Target framework DNX,Version=v4.5.1 (dnx451)]

Framework references:
  framework/Microsoft.CSharp 4.0.0.0
  framework/mscorlib 4.0.0.0
  framework/System 4.0.0.0
  framework/System.Collections.Concurrent 4.0.0.0
  framework/System.Core 4.0.0.0

Package references:
* k-http 0.1.0-beta-003
  Microsoft.AspNet.FeatureModel 1.0.0-beta6-11563
  Microsoft.AspNet.FileProviders.Abstractions 1.0.0-beta6-11461
  Microsoft.AspNet.FileProviders.Physical 1.0.0-beta5-11366
  Microsoft.AspNet.Hosting 1.0.0-beta5-11785
  Microsoft.AspNet.Hosting.Abstractions 1.0.0-beta6-11920
  Microsoft.AspNet.Hosting.Server.Abstractions 1.0.0-beta6-11920
  Microsoft.AspNet.Http 1.0.0-beta5-11469
  Microsoft.AspNet.Http.Abstractions 1.0.0-beta6-11563
  Microsoft.AspNet.Http.Extensions 1.0.0-beta6-11563
  Microsoft.AspNet.Http.Features 1.0.0-beta6-11563
  Microsoft.AspNet.Server.WebListener 1.0.0-beta6-12244
  Microsoft.AspNet.StaticFiles 1.0.0-beta6-11995
  Microsoft.AspNet.WebUtilities 1.0.0-beta5-11469
  Microsoft.Framework.Caching.Abstractions 1.0.0-beta6-11433
  Microsoft.Framework.Configuration 1.0.0-beta6-11405
  Microsoft.Framework.Configuration.Abstractions 1.0.0-beta6-11405
  Microsoft.Framework.Configuration.Binder 1.0.0-beta6-11405
  Microsoft.Framework.ConfigurationModel 1.0.0-beta5-11240
  Microsoft.Framework.ConfigurationModel.Interfaces 1.0.0-beta5-11240
  Microsoft.Framework.DependencyInjection 1.0.0-beta5-11269
  Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-beta6-11434
  Microsoft.Framework.DependencyInjection.Interfaces 1.0.0-beta5-11269
  Microsoft.Framework.Logging 1.0.0-beta5-11335
  Microsoft.Framework.Logging.Abstractions 1.0.0-beta6-11426
  Microsoft.Framework.Logging.Console 1.0.0-beta6-11426
  Microsoft.Framework.OptionsModel 1.0.0-beta6-11403
  Microsoft.Framework.Runtime.Abstractions 1.0.0-beta5-11739
  Microsoft.Framework.Runtime.Interfaces 1.0.0-beta5-11611
  Microsoft.Framework.WebEncoders 1.0.0-beta6-11563
  Microsoft.Framework.WebEncoders.Core 1.0.0-beta6-11563
  Microsoft.Net.Http.Headers 1.0.0-beta6-11563
  Microsoft.Net.Http.Server 1.0.0-beta6-12244
  Microsoft.Net.WebSockets 1.0.0-beta6-12244
  Newtonsoft.Json 6.0.6
```

As you can see, some dependencies are being resolved to `beta6` packages.

**Comment by tugberkugurlu** [comment]
Hmm, looking inside the NuGet package, the `project.lock.json` file hasn't been packed. Is it possible that I am seeing this issue as the dependency I use can have a dependency with a relative version and it's being resolved on the fly?

**Comment by muratg** [comment]
@victorhurdugaci

**Comment by muratg** [comment]
@victorhurdugaci can we investigate? not necessarily fix in beta 6 (that we can move to beta 7 based on the investigation)

**Comment by victorhurdugaci** [comment]
I did some investigations and it turns out that the issue is by design. Here's what happens:

Your package references "1.0.0-beta5-11672" (https://github.com/tugberkugurlu/k-http/blob/0.1.0-beta-003/src/k-http/project.json#L9). That package doesn't exist on any of the two feeds that you are passing as sources. So, our code looks for the closest package to that one.

Since `1.0.0-beta5 < 1.0.0-beta5-11672 < 1.0.0-beta6-<number>` we're going to pick the `beta6-<number>`.

This is actually an issue with our build numbers. We release `beta5` (no numbers) as a newer version than `beta5-<number>`.

**Comment by tugberkugurlu** [comment]
I am curious: if the versions were locked (I am not sure if this is possible with the project.lock.json file but let's say it is), would I see the same behavior or would it fail during install?

**Comment by victorhurdugaci** [comment]
It would fail because the package doesn't exist

**Comment by tugberkugurlu** [comment]
Awesome, that's way better than failing on runtime IMO.

Do you guys consider eventually adding the feature to pack the commands with lock file? I am not sure if there are going to be any side effects but seems like the safest bet.

**Comment by victorhurdugaci** [comment]
We have a few things on our backlog:

1. Pack with runtime or allow the command to be pinned to a particular runtime
2. Pack with particular dependencies (that includes your suggestion)

**Comment by tugberkugurlu** [comment]
:+1: awesome, thanks for the update! I know the 1st one but do you have an issue number for the 2nd one that I can track?
