### ISSUE TITLE
Support uap10.0 Framework

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#2302]
I'm trying to update EF's use of `netcore50` to `uap10.0`, but dnu gives me this error.

> "uap10.0" is an unsupported framework

**Comment by davidfowl** [comment]
Hey, at least you get an error now :smile:

**Comment by bricelam** [comment]
BTW, what's with the `uap10.0`? Wouldn't the NuGet thing to do be `uwp100`?

**Comment by davidfowl** [comment]
NuGet actually supports version numbers. It's 10.0 to avoid ambiguity. 100 -> could be 1.0.0

**Comment by muratg** [comment]
@anurse

**Comment by anurse** [comment]
It's not even ambiguous: ). `uap100` is interpreted as `1.0.0`

#2677 adds support for uap10.0

**Comment by natemcmaster** [comment]
With #2677 "uap10.0" is recognized, but `dnu build` fails. Is this a separate issue?

```
Building Microsoft.Data.Sqlite for UAP,Version=v10.0
System.ArgumentException: preprocessorSymbols
   at Microsoft.CodeAnalysis.CSharp.CSharpParseOptions..ctor(LanguageVersion languageVersion, DocumentationMode documentationMode, SourceCodeKind kind, IEnumerable`1 preprocessorSymbols)
   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.CompileProject(CompilationProjectContext projectContext, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver)
   at Microsoft.Dnx.Compilation.CSharp.RoslynProjectCompiler.CompileProject(CompilationProjectContext projectContext, Func`1 referenceResolver, Func`1 resourcesResolver)
   at Microsoft.Dnx.Compilation.LibraryExporter.<>c__DisplayClass18_0.<ExportProject>b__0(CacheContext ctx)
```

**Comment by anurse** [comment]
Thats #2546, which I am currently fixing

**Comment by Maxwe11** [comment]
What state of this?
What #define symbol will be used for uap10.0 ?

**Comment by anurse** [comment]
I believe the define symbol is `UAP10_0`

**Comment by natemcmaster** [comment]
@anurse Unless I'm mistaken, adding this TFM does not mean DNX will actually compile for UAP. It merely passes this along to the nuspec. Correct?

**Comment by Maxwe11** [comment]
@davidfowl why this closed?
