### ISSUE TITLE
PathUtility causes UriFormatException on xplat

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/dnx#2306]
Because of a limitation in CoreClr (see https://github.com/dotnet/coreclr/issues/1268), `NuGet.PathUtility.GetRelativeUri()` throws UriFormatException on OS X/Linux.

**Implication:** `dnu build` fails!

Example:

```
$ dnu build

Building Microsoft.Data.Sqlite for .NETFramework,Version=v4.5
  Using Project dependency Microsoft.Data.Sqlite 1.0.0
    Source: /Users/namc/Developer/Microsoft.Data.Sqlite/src/Microsoft.Data.Sqlite/project.json

  Unable to resolve dependency fx/System.Data 4.0.0.0

  Unable to resolve dependency fx/mscorlib 

  Unable to resolve dependency fx/System 

  Unable to resolve dependency fx/System.Core 

  Unable to resolve dependency fx/Microsoft.CSharp 

System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at NuGet.PathUtility.GetRelativeUri(String path1, String path2)
   at NuGet.PathUtility.GetRelativePath(String path1, String path2, Char separator)
   at NuGet.PathUtility.GetRelativePath(String path1, String path2)
   at Microsoft.Framework.Runtime.ResourcePathUtility.GetResourceName(String projectFolder, String resourcePath)
```

`Path1: /Users/namc/Developer/Microsoft.Data.Sqlite/src/Microsoft.Data.Sqlite/`
`Path2: /Users/namc/Developer/Microsoft.Data.Sqlite/src/Microsoft.Data.Sqlite/Strings.resx`

**Comment by BrennanConroy** [comment]
This is being tracked by #1793

**Comment by muratg** [comment]
@BrennanConroy Please add http://github.org/dotnet/coreclr/issues/1268  to the tracking list and close this one as dup.
