### ISSUE TITLE
Issue in run debug web application

### ISSUE THREAD

**Issue by CarlosFreire** [aspnet/dnx#2327]
System.IO.FileLoadException
Could not load file or assembly 'ApplicationMVC' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef) 
at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList<String> diagnosticMessages) 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup() 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices() 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.get_ApplicationServices() 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.ApplicationStart(IHttpApplication application) 
at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.InvokeApplicationStart(IHttpApplication application)

**Comment by davidfowl** [comment]
Closing this, if it's still happening with rc1 update 1. Let me know
