### ISSUE TITLE
Path in dnx should not be sensitive on windows

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2330]
If my app is in folder HelloDNX and I run: `dnx -p Hellodnx run` I get this:

```
System.InvalidOperationException: Unable to resolve project 'Hellodnx' from C:\Users\pawelka\Documents\Visual Studio 2015\projects\HelloDNX\src\Hellodnx
   at Microsoft.Framework.Runtime.ApplicationHostContext..ctor(IServiceProvider serviceProvider, String projectDirectory, String packagesDirectory, String configuration, FrameworkName targetFramework, ICache cache, ICacheContextAccessor cacheContextAccessor, INamedCacheDependencyProvider namedCacheDependencyProvider, IAssemblyLoadContextFactory loadContextFactory, Boolean skipLockFileValidation)
   at Microsoft.Framework.Runtime.DefaultHost.Initialize(DefaultHostOptions options, IServiceProvider hostServices)
   at Microsoft.Framework.Runtime.DefaultHost..ctor(DefaultHostOptions options, IServiceProvider hostServices)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

This is a bit unexpected since -p indicates path to a project and paths on windows are case insensitive. Also throwing the stack trace at the user's face is a bit scary (and I don't think the stack trace is actually very helpful to the user).

**Comment by Xorcist77** [comment]
this also pertains to the current path as specified in your PowerShell session.

If the actual path is:
C:\Users\UserName\Projects\HelloWorld

but in Powershell you cd to:
C:\users\username\projects\helloworld

and then execute "dnx run" in that directory, you will get a similar error.

However if to cd to the path with the proper case, "dnx run" will work just fine.

**Comment by victorhurdugaci** [comment]
@troydai
