### ISSUE TITLE
dnx folder web fails on beta7-12274 coreclr x64

### ISSUE THREAD

**Issue by IRooc** [aspnet/dnx#2344]
When you run dnx outside the web projectfolder you recieve this error:
```
System.InvalidOperationException: Unable to resolve project 'test' from C:\projects\test
   at Microsoft.Framework.Runtime.ApplicationHostContext..ctor(IServiceProvider hostServices, String projectDirectory, String packagesDirectory, String configuration, FrameworkName targetFramework, IC
ache cache, ICacheContextAccessor cacheContextAccessor, INamedCacheDependencyProvider namedCacheDependencyProvider, IAssemblyLoadContextFactory loadContextFactory, Boolean skipLockFileValidation)
   at Microsoft.Framework.Runtime.DefaultHost.Initialize(RuntimeOptions options, IServiceProvider hostServices)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

```

So ```dnx websitefolder web``` fails but going into the websitefolder (c:\projects\test\websitefolder) and running ```dnx . web``` works fine.

I checked with clr and x86 runtimes but they fail also.
It worked correctly from outside the folder in the previous version 12264

EDIT: also fails on Mac with same runtime

**Comment by Kieranties** [comment]
Just hit this issue with beta7-12290.  `dnx . test` works fine, `dnx .\test\Project.Tests test` fails when running from project root folder.

Last working dnx I have locally is beta6-12256

**Comment by anurse** [comment]
The current syntax for running in a different folder is `dnx --appbase [path\to\other\folder] Microsoft.Dnx.ApplicationHost run ...`.

We are **totally** aware that this suck and is bad and terrible and no-good :). See #2316 :)

**Comment by anurse** [comment]
Closing this as we basically cover the underlying issue in #2316 and the workaround above works for now. Feel free to continue discussion or re-open if you have further comments! :)
