### ISSUE TITLE
TypeloadException VS CTP 2015, Windows 8

### ISSUE THREAD

**Issue by sandeepbassi** [aspnet/dnx#2354]
I have dnx version 1.0.0-bet7-11762 and i'm using Microsoft.Net.Http.Client 1.0.0-beta6-10093 and i am encountering the below exception.

Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.Fr
amework.Runtime.IRuntimeServices' from assembly 'Microsoft.Framework.Runtime.Abs
tractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly ass
embly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly ass
embly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
   at DomainManager.Main(Int32 argc, String[] argv)

**Comment by davidfowl** [comment]
You should update your packages to beta7 if you plan to use the beta7 dnx

**Comment by sandeepbassi** [comment]
Hi David, 

Could you please refer me to the package for Microsoft.Net.Http.Client that is compliant to beta7 

Thanx
Sandeep
