### ISSUE TITLE
Bad IL format when running on CoreCLR if project folder is named "coreclr" or "dnx"

### ISSUE THREAD

**Issue by simonech** [aspnet/dnx#2355]
i've been following the getting started tutorial (http://dotnet.github.io/core/getting-started/), but I'm facing an issue:
when I run on CoreCLR I get the error:

```
System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)

   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.Framework.Runtime.Loader.LoadContext.LoadFile(String path)
   at dnx.host.PathBasedAssemblyLoader.Load(AssemblyName assemblyName)
   at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
   at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Microsoft.Framework.Runtime.IAssemblyLoadContext.Load(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

if I switch to the full framework it works fine.

These are the versions I installed

```
C:\Users\user\Documents\Projects\coreclr>dnvm list

Active Version           Runtime Architecture Location
------ -------           ------- ------------ --------
       1.0.0-beta5       clr     x86          C:\Users\user\.dnx\runtimes
  *    1.0.0-beta7-12274 coreclr x86          C:\Users\user\.dnx\runtimes
```

**Comment by simonech** [comment]
Same error happening also on  1.0.0-beta5       coreclr x86

**Comment by simonech** [comment]
Found the problem: my folder was named `coreclr`... renamed to `coreclrsamples` and now it works :)

**Comment by muratg** [comment]
@troydai

**Comment by matra774** [comment]
I had the same problem. Renaming folder helps.

```
c:\Users\user1\Research\coreclrTest>dnvm list

Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
  *    1.0.0-beta7-12290 coreclr x64          win
```

**Comment by GramozKrasniqi** [comment]
thanks god i found it here that the folder name is the problem.

**Comment by per-samuelsson** [comment]
> thanks god i found it here that the folder name is the problem.

+1.

I've struggled this for hours today. I thought it was a joke when I found an issue with this title :smiley: 

This issue looks like that kind of thing that, on the surface, I'd just put into the backlog and count on that I'd never see it again. But seeing that in fact a few of us over a rather short time period hits the same thing, it might be an idea to put it higher up the queue. Especially if it should be a low hanging fruit.

**Comment by caleteeter** [comment]
+1.

This is also the case when the root folder is dnx.  :)

**Comment by leidegre** [comment]
Does anyone know why is this happening? (why does the folder name matter?)

**Comment by simonech** [comment]
This error is not happening anymore, maybe should be closed?
