### ISSUE TITLE
Provide better error message when "commit" is missing from repo.json

### ISSUE THREAD

**Issue by tillig** [aspnet/dnx#2416]
When you package your project with support for `dnu sources get` you can end up with a `repo.json` file that looks something like this:

```json
{
  "type": "git",
  "url": "https://github.com/autofac/Autofac",
  "commit": "35cb2095bbcf9e873a5ed5efcc6455c69a6f8ce3",
  "path": "src"
}
```

In a build server environment where the code is checked out and then pushed to the build agent (e.g., AppVeyor) there's no working copy, so the `repo.json` looks like this:

``` json
{
  "type": "git",
  "url": "https://github.com/autofac/Autofac",
  "commit": "",
  "path": "src"
}
```

You get no error message during the packaging step that this is happening.

Later, if you run `dnu sources get` on the package, you'll get an exception:

```
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.Framework.PackageManager.SourceControl.GitSourceControlProvider.CreateShortFolderName(IDictionary`2 snapshotInfo)
   at Microsoft.Framework.PackageManager.SourceControl.SourceCommand.Execute()
   at Microsoft.Framework.PackageManager.SourcesConsoleCommand.<>c__DisplayClass1_0.<RegisterGetSubcommand>b__1()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

This appears to be due to [a line in `GitSourceControlProvider` that tries to get a substring of the commit value but doesn't check to see if it's empty/null first](https://github.com/aspnet/dnx/blob/219871c6063d00f8297eeafe93266f1048f59a45/src/Microsoft.Dnx.Tooling/SourceControl/GitSourceControlProvider.cs#L127).

It'd be good to get a better error message if the commit isn't there; it'd be even better to somehow fail the packaging or issue a build warning to alert folks that things aren't as expected.

**Comment by jchannon** [comment]
I see the same issue with `Microsoft.AspNet.Authentication.Twitter` but had no clue why it threw that error

**Comment by davidfowl** [comment]
Feature was cut
