### ISSUE TITLE
Beta7-12302 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified

### ISSUE THREAD

**Issue by CarlosFreire** [aspnet/dnx#2426]
```
1>  C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\dnx.exe --appbase "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.Datos.Interfaz" "C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" pack "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.Datos.Interfaz" --configuration Debug --out "..\..\artifacts\bin\Cross2Business.Datos.Interfaz"
2>  C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\dnx.exe --appbase "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.POCO" "C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" pack "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.POCO" --configuration Debug --out "..\..\artifacts\bin\Cross2Business.POCO"
3>  C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\dnx.exe --appbase "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.Comun" "C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" pack "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.Comun" --configuration Debug --out "..\..\artifacts\bin\Cross2Business.Comun"
1>  System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.
1>  File name: 'Microsoft.DNX.PackageManager'
1>     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>     at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>     at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
1>     at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
1>     at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
1>     at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
1>     at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
1>  WRN: Assembly binding logging is turned OFF.
1>  To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
1>  Note: There is some performance penalty associated with assembly bind failure logging.
1>  To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by victorhurdugaci** [comment]
> 1>  C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\dnx.exe --appbase "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.Datos.Interfaz" "C:\Users\carlos.freire\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" pack "C:\Canales\Cross2Business\PlataformaWeb\C2B\src\Cross2Business.Datos.Interfaz" --configuration Debug --out "..\..\artifacts\bin\Cross2Business.Datos.Interfaz"

Is this a command that you are running or is it called by some script?

`Microsoft.Framework.PackageManager` was renamed to `Microsoft.Dnx.Tooling` as described in [this announcement](https://github.com/aspnet/Announcements/issues/51). I don't think we ever had a file name `Microsoft.DNX.PackageManager` (that looks like a combination of the old and new name)

**Comment by glennc** [comment]
@CarlosFreire If you update all your packages to a consistent version (all beta6 with the beta6 dnx for example) does this go away?

**Comment by jasoncavett** [comment]
I'm seeing this same issue on Beta 7 as well. I'm in Windows, running VS2015 and it's happening when I attempt to restore packages. This is the output from the Output panel.

```
C:\Users\JC\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\dnx.exe "C:\Users\JC\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" restore "Z:\Projects\web-cemeteries\obituaries" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.DNX.PackageManager'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

**Comment by victorhurdugaci** [comment]
You are not using the latest VS tooling. See this thread: https://github.com/aspnet/dnx/issues/2371

**Comment by jasoncavett** [comment]
Thanks @victorhurdugaci. I actually fixed it just a bit ago, but I didn't need to get new tooling. Instead, I had to delete out project.lock.json and then I had to manually run `dnu restore` from the command window. Once that was done, everything worked beautifully.

I'll look to update my tooling, though, as that is obviously a better way to do it. Thanks again!

**Comment by Shuliyey** [comment]
Hi 

this bug still exists in the beta8. 

dnu restore works. But visual studio 2015 still tries to call the below command

C:\Users\dye\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\dnx.exe "C:\Users\dye\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" restore "d:\visual studio 2015\Projects\Auto\src\Auto" -s "C:\Program Files (x86)\Microsoft Web Tools\DNU"

**Comment by Shuliyey** [comment]
Hi

Sorry I found out the problem, and the solution is here

https://github.com/aspnet/dnx/issues/2371

Basicly @mdekrey mentioned you have to install WebToolsExtension VS14

Giving this a try now
