### ISSUE TITLE
Project.lock.json locked during command line build

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2462]
```
Writing lock file C:\dev\git\dnx\test\Microsoft.Dnx.Runtime.Tests\project.lock.json
Information: [LoaderContainer]: Load name=System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
----------
System.IO.IOException: The process cannot access the file 'C:\dev\git\dnx\test\Microsoft.Dnx.Runtime.Tests\project.lock.json' because it is being used
 by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, Fil
eOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Dnx.Tooling.LockFileFormat.Write(String filePath, LockFile lockFile)
   at Microsoft.Dnx.Tooling.RestoreCommand.WriteLockFile(LockFile previousLockFile, String projectLockFilePath, Project project, List`1 graphItems, Pa
ckageRepository repository, IEnumerable`1 contexts)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass69_0.<<Execute>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__69.MoveNext()
----------
Restore failed
The process cannot access the file 'C:\dev\git\dnx\test\Microsoft.Dnx.Runtime.Tests\project.lock.json' because it is being used by another process.

NuGet Config files used:
    C:\Users\davifowl\AppData\Roaming\NuGet\NuGet.Config
    C:\dev\git\dnx\NuGet.Config

Feeds used:
    https://www.nuget.org/api/v2/
    https://www.myget.org/F/aspnetvnext/api/v2/
    https://www.myget.org/F/roslyn-nightly/
    https://www.myget.org/F/dotnet-corefx/
warn: Exit code 1 from cmd
verbose: Stack trace:
   at Viewc7e81e89f56c49828438bad39a78282a.DoRestore() in c:\Users\davifowl\AppData\Local\Temp\9b74f0d887a2487b8d106c45aa209eff-1.cs:line 430
```

**Comment by glennc** [comment]
When does this happen? Building anything?

**Comment by davidfowl** [comment]
Reproed from the command line when I run build.cmd on dnx
