### ISSUE TITLE
After changing a file, the project doesn't compile anymore

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/dnx#2498]
I've got a project with two `ICompileModule`s and I'm observing project build failures in CTRL+F5 IIS Express and in VS. Starting fresh from the command line always works. I'm running beta6.

When I change a normal source code file while IIS is running, I start getting errors in VS:
`An item with the same key has already been added.` and `The design time host build failed with the following error: An item with the same key has already been added`.
IIS Express doesn't deliver any content anymore with an internal server error (see below)

I can make compilation work once when I make a change to one of the `ICompileModule`s. Then CTRL+F5 or refreshing the browser gives me back a working IIS Express until I change again a normal source code file.

```
System.IO.FileLoadException: Could not load file or assembly 'App.Instrument' or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)
File name: 'App.Instrument' ---> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: An item with the same key has already been added.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.Runtime.DesignTimeHostCompiler.d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Framework.Runtime.DesignTimeHostProjectCompiler.CompileProject(ICompilationProject project, ILibraryKey target, Func`1 referenceResolver, Func`1 resourcesResolver)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.<>c__DisplayClass5_0.b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.<>c__DisplayClass2_0.b__0(ILibraryExportProvider r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.LibraryManager.GetLibraryExport(String name, String aspect)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
   at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.LoadContext.TryLoadAssembly(LoadContext context, AssemblyName assemblyName, Assembly& assembly)
   at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
---> (Inner Exception #0) System.InvalidOperationException: An item with the same key has already been added.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.Runtime.DesignTimeHostCompiler.d__7.MoveNext()<---

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList`1 diagnosticMessages)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.get_ApplicationServices()
   at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.ApplicationStart(IHttpApplication application)
   at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.InvokeApplicationStart(IHttpApplication application)


.NET Framework CLR version 4.0.30319.42000   |   DNX x86 version 1.0.0-beta6-12256   |   Microsoft.AspNet.Loader.IIS version 1.0.0-beta6-12090   |   IIS version 10.0.10117.0 (fbl_srv2_iis_dev(sujitn).150512-1839)   |   Windows 10.0.10240.0   |   Need help?
```

**Comment by Tragetaschen** [comment]
Correction: Refreshing the browser doesn't yet fix this after changing the `ICompileModule`. I need to do a CTRL+F5 in VS to again have a working environment.

**Comment by davidfowl** [comment]
This feature is currently pretty buggy overall and we'll given how far we are, we're at the point where we might either cut it or reduce the scope of what it does. Hopefully beta8 works a little better.

**Comment by Tragetaschen** [comment]
What can I do to make you keep it? Beer? Cake?
[An example](https://github.com/Tragetaschen/dbus-sharp/blob/asp-net/src/Dbus.Sharp/ClassGenerator.cs)  how to [avoid Assembly.Emit](https://github.com/Tragetaschen/dbus-sharp/blob/asp-net/src/Dbus.Sharp/TypeImplementer.cs) on an embedded platform?

Pretty please…

**Comment by Tragetaschen** [comment]
The error was actually on my end, because an `ICompileModule` is constructed once and then called multiple times in VS. Since this entire feature is under the radar until after RTM, I'm going to close this.

Looking forward for the (ideas behind) `ICompileModule` becoming a full thing!
