### ISSUE TITLE
ICompileModule broken in VS

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2499]
@davidfowl reported this. I'm working on a fix.

```
Information: [LoaderContainer]: Load name=Microsoft.Dnx.Runtime!preprocess
Error: [RoslynCompiler]: Failed loading meta assembly 'Microsoft.Dnx.Runtime':
 System.IO.FileLoadException: Could not load file or assembly 'f0468507-4f97-4441-85a1-149e4b53a1cc$Microsoft.Dnx.Runtime!preprocess' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
File name: 'f0468507-4f97-4441-85a1-149e4b53a1cc$Microsoft.Dnx.Runtime!preprocess' ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dnx.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoadContextFactory.LibraryAssemblyLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.TryLoadAssembly(LoadContext context, AssemblyName assemblyName, Assembly& assembly)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.<>c__DisplayClass10_0.<GetCompileModules>b__0(CacheContext _)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.GetCompileModules(CompilationTarget target)
   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.CompileProject(CompilationProjectContext projectContext, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver)
```

**Comment by anurse** [comment]
+@glennc @muratg @danroth27 @DamianEdwards

This should go in for beta7. It is a regression of a main scenario. I'm working on a fix now. This does not affect CI builds, so I suggest we **do not** block `release` branching on it. I can make the fix in release when we've branched. (Unless `release` branching is otherwise delayed until after I have a fix, in which case I'll make it on dev ;))
