### ISSUE TITLE
Can't Publish with dnu publish ( NotSupportedException) 

### ISSUE THREAD

**Issue by Tazer** [aspnet/dnx#2535]
Hello,

Running beta 6.

Trying to run dnu publish but just getting an error from System.IO.FileStream.Init

```
Copying to output path C:\Users\xxxx\AppData\Local\Temp\PublishTemp
System.NotSupportedException: The given path's format is not supported.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.Framework.PackageManager.Publish.PublishRoot.GenerateBatchFiles()
   at Microsoft.Framework.PackageManager.Publish.PublishRoot.Emit()
   at Microsoft.Framework.PackageManager.Publish.PublishManager.Publish()
   at Microsoft.Framework.PackageManager.PublishConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

So it's really hard to understand what's wrong and what.

**Comment by Tazer** [comment]
Solved it,

But the problem was that I had a command in my project.json that looked like this:

```
"migrate:down": "FluentMigrator.Runner.DNX --provider sqlserver2012  --task migrate:down",
```

dnu publish didnt like that.

**Comment by muratg** [comment]
Thanks Tazer!
