### ISSUE TITLE
Running dnu with an invalid packagesource results in errors

### ISSUE THREAD

**Issue by overeemm** [aspnet/dnx#2574]
If I run the dnu restore command with the beta6 version I get an error if there is an invalid (non existing) package feed configured. This is without any clear message indicating that the package feed is invalid.

Output:

```
c:\ExampleProject>dnu restore
Microsoft .NET Development Utility CLR-x64-1.0.0-beta6-12256

Restoring packages for c:\ExampleProject\artifacts\bin\Example.Project.Web\Debug\app\project.json
  CACHE https://www.nuget.org/api/v2/
  GET https://nuget.example.com/nuget/
Writing lock file c:\ExampleProject\artifacts\bin\Example.Project.Web\Debug\app\project.lock.json
Restore complete, 758ms elapsed
Restoring packages for c:\ExampleProject\src\Example.Project\project.json
  CACHE https://www.nuget.org/api/v2/
  GET https://nuget.example.com/nuget/
Writing lock file c:\ExampleProject\src\Example.Project\project.lock.json
Restore complete, 17ms elapsed
Restoring packages for c:\ExampleProject\src\Example.Project.Client\project.json
  CACHE https://www.nuget.org/api/v2/
  GET https://nuget.example.com/nuget/
Writing lock file c:\ExampleProject\src\Example.Project.Client\project.lock.json
Restore complete, 97ms elapsed
Restoring packages for c:\ExampleProject\src\Example.Project.Web\project.json
  CACHE https://www.nuget.org/api/v2/
  GET https://nuget.example.com/nuget/
Writing lock file c:\ExampleProject\src\Example.Project.Web\project.lock.json
Restore complete, 378ms elapsed
Restoring packages for c:\ExampleProject\src\Example.Project.Web\bin\Release\app\project.json
  CACHE https://www.nuget.org/api/v2/
  GET https://nuget.example.com/nuget/
Writing lock file c:\ExampleProject\src\Example.Project.Web\bin\Release\app\project.lock.json
Restore complete, 383ms elapsed
Restoring packages for c:\ExampleProject\tests\Example.Project.Tests\project.json
  CACHE https://www.nuget.org/api/v2/
  GET https://nuget.example.com/nuget/
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='xunit'
  GET https://nuget.example.com/nuget/FindPackagesById()?id='xunit'
Warning: FindPackagesById: xunit
  An error occurred while sending the request.
  GET https://nuget.example.com/nuget/FindPackagesById()?id='xunit'
Warning: FindPackagesById: xunit
  An error occurred while sending the request.
  GET https://nuget.example.com/nuget/FindPackagesById()?id='xunit'
Error: FindPackagesById: xunit
  An error occurred while sending the request.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='xunit.runner.dnx'
  GET https://nuget.example.com/nuget/FindPackagesById()?id='xunit.runner.dnx'
Warning: FindPackagesById: xunit.runner.dnx
  An error occurred while sending the request.
  GET https://nuget.example.com/nuget/FindPackagesById()?id='xunit.runner.dnx'
Warning: FindPackagesById: xunit.runner.dnx
  An error occurred while sending the request.
  GET https://nuget.example.com/nuget/FindPackagesById()?id='xunit.runner.dnx'
Error: FindPackagesById: xunit.runner.dnx
  An error occurred while sending the request.
----------
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'nuget.example.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.HttpSource.<GetAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.NuGetv2Feed.<FindPackagesByIdAsyncCore>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass69_0.<<Execute>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<Execute>d__69.MoveNext()
----------
Restore failed
An error occurred while sending the request.

NuGet Config files used:
    C:\Users\mov\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://www.nuget.org/api/v2/
    https://nuget.example.com/nuget/

c:\ExampleProject>
```

**Comment by daviatorstorm** [comment]
I have the same problem.

VS 2015 Community
NuGet 3.2.0

Current package source https://nuget.org/api/v2

**Comment by GeXiaoguo** [comment]
in my case changing the package source to https://www.nuget.org/api/v2/ fixed the problem
the wrong config files look like below
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="Package source" value="http://packagesource" />
