### ISSUE TITLE
coreclr publish tries to access packages in user directory

### ISSUE THREAD

**Issue by nicolasr75** [aspnet/dnx#2641]
I am having issues with using coreclr bundles published with Visual Studio (but probably the same with normal clr). When I have installed the runtime and all packages in {username}\.dnx, I can start my published project with kestrel and web commands from the commandline. When I don't have installed packages in the users home directory it fails with 

	System.IO.DirectoryNotFoundException: Das System kann den angegebenen Pfad nicht
	 finden. (Exception from HRESULT: 0x80070003)
	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAss
	emblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)

	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String asse
	mblyPath)
	   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assem
	blyName, IAssemblyLoadContext loadContext)
	   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
	   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName nam
	e, Func`2 factory)
	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyNam
	e assemblyName)
	   at Microsoft.Dnx.ApplicationHost.DefaultHost.GetEntryPoint(String application
     ...

although the bundle contains all packages! I then noticed the file

{publish-dir}\approot\src\MyApp\global.json

which by default seems to contain:

"packages": "packages"

When I change this to the actual path of the packages directory in my bundle, calling kestrel/web works without any error:

"packages": "{publish-dir}\approot\packages"

Do I misunderstand something?
I thought coreclr bundles should work self-contained on any system without global installation of packages?

**Comment by moozzyk** [comment]
If you want to create a self contained package you need to publish your app. You can do that from VS or from command line with the `dnu publish` command. When you publish your app it will include the runtime.

**Comment by nicolasr75** [comment]
Yes, that is what I did: published the project with VS and selected as target DNX version: dnx-coreclr-win-x64.1.0.0-beta8-15564. Then I copied the published bundle to another Win10 test system and tried to run it with either kestrel/web, result:

System.IO.DirectoryNotFoundException

Then I copied all my {username}\.dnx\packages\

to the test systems user directory and suddenly it works. Why does the self-contained bundle try to access packages in the users dnx installation and not use the packages that it already contains?

**Comment by davidfowl** [comment]
Seems like a bug. The app is self contained and should just run

**Comment by davidfowl** [comment]
@nicolasr75 Did you set any DNX environment variables on the target machine? Can you also run with DNX_TRACE=1 and paste that?

**Comment by nicolasr75** [comment]
C:\Users\Public\Documents\RSW\Test\MyApp>kestrel
	The default servicing root does not exist.
	Loaded module: dnx.win32.coreclr.dll
	Found export: CallApplicationMain
	Information: [DomainManager] Using CoreCLR
	Information: [LoaderContainer]: Load name=Microsoft.Dnx.ApplicationHost, Culture=neutral, PublicKeyToken=null
	Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Dnx.ApplicationHost, Culture=neutral, PublicKeyToken=null in 2ms
	Information: [Bootstrapper] Runtime Framework: DNXCore,Version=v5.0
	Information: [LoaderContainer]: Load name=Microsoft.Dnx.Compilation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
	Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Dnx.Compilation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in 0ms
	Information: [LoaderContainer]: Load name=Microsoft.Dnx.Compilation.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
	Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Dnx.Compilation.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in 0ms
	Information: [LoaderContainer]: Load name=Microsoft.Dnx.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
	Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Dnx.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in 1ms
	Information: [DefaultHost]: Project path: C:\Users\Public\Documents\RSW\Test\MyApp\approot\src\MyApp
	Information: [DefaultHost]: Project root: C:\Users\Public\Documents\RSW\Test\MyApp\approot\src\MyApp
	Information: [DefaultHost]: Project configuration: Release
	Information: [DefaultHost]: Packages path: C:\Users\Public\Documents\RSW\Test\MyApp\approot\src\MyApp\packages
	Information: [ServicingIndex]: Servicing index not found at C:\Program Files (x86)\Microsoft DNX\Servicing\index.txt
	Information: [Breadcrumbs] Breadcrumbs for servicing will not be written because the breadcrumbs folder (C:\ProgramData\Microsoft DNX\BreadcrumbStore) does not
	exist.
	Information: [LoaderContainer]: Load name=Microsoft.AspNet.Hosting, Culture=neutral, PublicKeyToken=null
	System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
	   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
	   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
	   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
	   at Microsoft.Dnx.ApplicationHost.DefaultHost.GetEntryPoint(String applicationName)
	   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
	   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
	   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironmentenv, FrameworkName targetFramework)
	   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
	   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

**Comment by davidfowl** [comment]
This line:

```
Information: [DefaultHost]: Project root: C:\Users\Public\Documents\RSW\Test\MyApp\approot\src\MyApp
```

Makes me feel like your `global.json` is missing. Do you have a `global.json` in your published layout?

**Comment by nicolasr75** [comment]
There is one in MyApp/approot

	{
	  "sdk": {
		"version": "1.0.0-beta8-15564"
	  },
	  "projects": [
		"src"
	  ],
	  "packages": "packages"
	}

and one in MyApp\approot\src\MyApp

	{
		"sdk": {
			"version": "1.0.0-beta8-15564"
		},
		"packages": "packages"
	}

When I change the latter one to

{
    "sdk": {
        "version": "1.0.0-beta8-15564"
    },
	"packages": "C:\\Users\\Public\\Documents\\RSW\\Test\\MyApp\\approot\\packages"
}

the error is gone, although it then dies because of missing libuv but that's a different topic...

**Comment by davidfowl** [comment]
You have 2 global.json files? Why?

**Comment by nicolasr75** [comment]
The second global.json came from playing with project groups/solutions in VS. Removing it solved the problem. Sorry for wasting your time, I should have tested this with a blank project...
