### ISSUE TITLE
coreclr linux/mac embedded resource >4k won't work

### ISSUE THREAD

**Issue by IRooc** [aspnet/dnx#2661]
When I embed a file that is larger than larger than 4k on linux /mac it throws an BadImageFormatException, 

reprosteps, create test.txt larger than 4100 bytes
project.json:

```
{
    "version": "1.0.0-*",
    "dependencies": {
        "Microsoft.AspNet.FileProviders.Embedded": "1.0.0-beta-*"
    },
    "commmands":{
        "run":"run"
    },

    "resource":"test.txt",

    "frameworks": {
        "dnx451": { },
        "dnxcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-*"
            }
         }
    }
}
```

then create this Program.cs

```
using System;
using System.IO;
using System.Reflection;
using Microsoft.AspNet.FileProviders;

namespace Proj2 {
    public class Program {

        public void Main(string[] args){
            var txt = FileContent();
            Console.WriteLine(txt);
        }


        public string FileContent() {
            var provider = new EmbeddedFileProvider(GetType().GetTypeInfo().Assembly, GetType().Namespace);

            var fileInfo = provider.GetFileInfo("test.txt");
            if (fileInfo.Exists) {
                using (var stream = fileInfo.CreateReadStream())
                {
                    StreamReader reader = new StreamReader(stream); 
                    return reader.ReadToEnd();
                }
            }
            return "not found";
        }
    }
}
```

if the test.txt file is smaller than 4100 bytes the program runs fine and shows the content, when it's larger than 4100 bytes the following stacktrace is shown:

```
System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B)
   at System.Reflection.RuntimeAssembly.GetResource(RuntimeAssembly assembly, String resourceName, UInt64& length, StackCrawlMarkHandle stackMark, Boolean skipSecurityCheck)
   at System.Reflection.RuntimeAssembly.GetManifestResourceStream(String name, StackCrawlMark& stackMark, Boolean skipSecurityCheck)
   at System.Reflection.RuntimeAssembly.GetManifestResourceStream(String name)
   at Microsoft.AspNet.FileProviders.EmbeddedFileProvider.EmbeddedResourceFileInfo.CreateReadStream()
   at Proj2.Program.FileContent()
   at Proj2.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

When running dnu build and opening the .dll with dotPeek the result shows only the first 4k in the assembly. When adding multiple files as resources and opening the first, after 4k the first bytes of the next file are added to the file.

**Comment by davidfowl** [comment]
Related bug https://github.com/dotnet/roslyn/issues/5052

**Comment by dougbu** [comment]
Our tracking bug is aspnet/External#33. Lower-level problem of interest is now dotnet/corefx#3258.
