### ISSUE TITLE
IApplicationEnvironment.ApplicationBasePath comes wrong

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/dnx#2781]
`IApplicationEnvironment.ApplicationBasePath` comes as *C:\Users\tugberk.ugurlu.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8-15618\bin\lib\Microsoft.Dnx.Tooling* for me on build when I tried to use it inside an `ICompileModule`. Here is the build log:

```
The default servicing root does not exist.
Loaded module: dnx.clr.dll
Found export: CallApplicationMain
Information: [DomainManager] Using Desktop CLR v4.5.1
Information: [LoaderContainer]: Load name=Microsoft.Dnx.Tooling
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Dnx.Tooling in 8ms

Information: [Bootstrapper] Runtime Framework: DNX,Version=v4.5.1
Microsoft .NET Development Utility CLR-x86-1.0.0-beta8-15618


Building AnalyzersCompileModule for DNX,Version=v4.5.1
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1
/
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1
/win7-x86
Information: [ServicingIndex]: Servicing index not found at C:\Program Files (x8
6)\Microsoft DNX\Servicing\index.txt
Information: [LibraryExporter]: Resolving references for 'AnalyzersCompileModule
'
Information: [LibraryExporter]: ExportProject(AnalyzersCompileModule, , DNX,Vers
ion=v4.5.1, Debug)
Information: [LibraryExporter]: GetProjectReference(Microsoft.Dnx.Compilation.CS
harp.RoslynProjectCompiler, AnalyzersCompileModule, DNX,Version=v4.5.1, )
Information: [LibraryExporter]: Resolving references for 'AnalyzersCompileModule
'
Information: [LibraryExporter]: Resolved 14 references for 'AnalyzersCompileModu
le' in 3ms
Information: [RoslynCompiler]: Compiling 'AnalyzersCompileModule'
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Algorithm
s, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Algorithm
s, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Algorithm
s, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Algorithm
s, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Primitive
s, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Primitive
s, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.FileSystem, Version=4.0.0.0,
 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.FileSystem, Version=4.0.0.0,
 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=AnalyzersCompileModule!preprocess
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1
/
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1
/win7-x86
Information: [LibraryExporter]: ExportProject(AnalyzersCompileModule, preprocess
, DNX,Version=v4.5.1, Debug)
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1
/
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1
/win7-x86
Information: [LibraryExporter]: GetProjectReference(Microsoft.Dnx.Compilation.CS
harp.RoslynProjectCompiler, AnalyzersCompileModule, DNX,Version=v4.5.1, preproce
ss)
Information: [LibraryExporter]: Resolving references for 'AnalyzersCompileModule
' preprocess
Information: [LibraryExporter]: Resolved 14 references for 'AnalyzersCompileModu
le' in 0ms
Information: [RoslynCompiler]: Compiling 'AnalyzersCompileModule!preprocess'
Information: [RoslynCompiler]: Compiled 'AnalyzersCompileModule!preprocess' in 3
5ms
Information: [CompilationContext]: Generating resources for AnalyzersCompileModu
le
Information: [CompilationContext]: Generated resources for AnalyzersCompileModul
e in 4ms
Information: [RoslynProjectReference]: Emitting assembly for AnalyzersCompileMod
ule
Information: [RoslynProjectReference]: Emitted AnalyzersCompileModule in 1572ms
msg:C:\Users\tugberk.ugurlu\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8-15618\bin\
lib\Microsoft.Dnx.Tooling\
Information: [LoaderContainer]: Load name=System.IO.FileSystem, Version=4.0.0.0,
 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.FileSystem, Version=4.0.0.0,
 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=Microsoft.CodeAnalysis.resources, Vers
ion=1.1.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35
Information: [LoaderContainer]: Load name=Microsoft.CodeAnalysis.resources, Vers
ion=1.1.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35
Information: [LoaderContainer]: Load name=Microsoft.CodeAnalysis.resources, Vers
ion=1.1.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
Information: [LoaderContainer]: Load name=Microsoft.CodeAnalysis.resources, Vers
ion=1.1.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
System.ArgumentException: Argument cannot be empty.
Parameter name: analyzers
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.VerifyAnalyzer
sArgumentForStaticApis(ImmutableArray`1 analyzers, Boolean allowDefaultOrEmpty)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.VerifyArgument
s(Compilation compilation, ImmutableArray`1 analyzers, CompilationWithAnalyzersO
ptions analysisOptions)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers..ctor(Compilat
ion compilation, ImmutableArray`1 analyzers, CompilationWithAnalyzersOptions ana
lysisOptions, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerExtensions.WithAnalyz
ers(Compilation compilation, ImmutableArray`1 analyzers, AnalyzerOptions options
, CancellationToken cancellationToken)
   at AnalyzersCompilationModule.BeforeCompile(BeforeCompileContext context) in
c:\dev\dnx-going-further\src\AnalyzersCompileModule\compiler\preprocess\Analyzer
sCompileModule.cs:line 24
   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.CompileProject(Compilation
ProjectContext projectContext, IEnumerable`1 incomingReferences, IEnumerable`1 i
ncomingSourceReferences, Func`1 resourcesResolver)
   at Microsoft.Dnx.Compilation.CSharp.RoslynProjectCompiler.CompileProject(Comp
ilationProjectContext projectContext, Func`1 referenceResolver, Func`1 resources
Resolver)
   at Microsoft.Dnx.Compilation.LibraryExporter.<>c__DisplayClass18_0.<ExportPro
ject>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<
Get>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acqui
re)
   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__
0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Obj
ect key, Func`2 factory)
   at Microsoft.Dnx.Compilation.LibraryExporter.ExportProject(ProjectDescription
 project, String aspect, LibraryExporter exporter)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetAllExports(LibraryDescription
 root, String aspect, Func`2 include)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetAllExports(String name, Strin
g aspect, Func`2 libraryFilter)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetAllExports(String name, Strin
g aspect)
   at Microsoft.Dnx.Tooling.BuildContext.ShowDependencyInformation(IReport repor
t)
   at Microsoft.Dnx.Tooling.BuildManager.BuildConfiguration(String baseOutputPat
h, IEnumerable`1 frameworks, List`1 allDiagnostics, String configuration)
   at Microsoft.Dnx.Tooling.BuildManager.BuildInternal(String projectPath)
   at Microsoft.Dnx.Tooling.BuildManager.Build()
   at Microsoft.Dnx.Tooling.BuildConsoleCommand.<>c__DisplayClass0_0.<Register>b
__1()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(St
ring[] args)
   at Microsoft.Dnx.Tooling.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment
env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, Framewo
rkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkNam
e targetFramework)
```

Here is the `ICompileModule`:

```csharp
public class AnalyzersCompilationModule : ICompileModule
{
    private readonly string _basePath;

    public AnalyzersCompilationModule(IApplicationEnvironment appEnv)
    {
        _basePath = appEnv.ApplicationBasePath;
    }

    public void BeforeCompile(BeforeCompileContext context)
    {
        string analyzerAssemblyPath = Path.Combine(_basePath, @"../../lib/DotNetDoodle.Analyzers.dll");
        Console.WriteLine("msg:" + _basePath);
        ImmutableArray<DiagnosticAnalyzer> diagnosticAnalyzers = new AnalyzerFileReference(analyzerAssemblyPath, FromFileLoader.Instance).GetAnalyzers(LanguageNames.CSharp);
        var compilation = context.Compilation.WithAnalyzers(diagnosticAnalyzers);
        ImmutableArray<Diagnostic> diagsnostics = compilation.GetAnalyzerDiagnosticsAsync().Result;

        foreach (var diagsnostic in diagsnostics)
        {
            context.Diagnostics.Add(diagsnostic);
        }
    }

    public void AfterCompile(AfterCompileContext context)
    {
    }
    
    private class FromFileLoader : IAnalyzerAssemblyLoader
    {
        public static FromFileLoader Instance = new FromFileLoader();

        public void AddDependencyLocation(string fullPath)
        {
        }

        public Assembly LoadFromPath(string fullPath)
        {
            return Assembly.LoadFrom(fullPath);
        }
    }
}
```

I am on 1.0.0-beta8-15618.

**Comment by davidfowl** [comment]
You shouldn't be using IApplicationEnvironment (which is actually correct in this case). If you want the context of the project being compiled then use the project context. The application context represents the runtime environment not the target compilation. Think of it as the information of the executable hosting the compiler.

**Comment by tugberkugurlu** [comment]
If that is the case, I think `IApplicationEnvironment` is a bad name to use here:disappointed:

Also, What is the `IRuntimeEnvironmet` is for then? And why would I ever want to get the `dnx-clr-win-x86.1.0.0-beta8-15618\bin\lib\Microsoft.Dnx.Tooling` path (which is the assembly that runs the build I assume)?

**Comment by davidfowl** [comment]
Nope it's correct. IRuntimeEnvironment gives you DNX information. It's not about what you want to get it's what's correct. In this cause vs is launching design time host (that's the application), you need to use the project context to get info about the project. It's a property of the compilation context.

**Comment by tugberkugurlu** [comment]
I see and fair enough. However, I still think it's confusing. Just my £0.02.

So, if I use `IApplicationEnvironment` inside the my project (e.g. getting it injected into `Startup` class), is it going to get me the path of the application? If not, what is the way to get project context injected? I wasn't able to find something like `IProjectEnvironment` or anything similar.
