### ISSUE TITLE
project.json parser can't handle unicode escape sequences

### ISSUE THREAD

**Issue by Flavien** [aspnet/dnx#2843]
I'm trying to have the Copyright character in my project.json file:

      "copyright": "Copyright \u00A9 2015",

however, this results in a build failure:

```
1>  Microsoft .NET Development Utility CLR-x86-1.0.0-beta7-15532
1>D:\path\project.json : error : Microsoft.Dnx.Runtime.FileFormatException: Index was out of range. Must be non-negative and less than the size of the collection.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : Parameter name: index
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at System.Text.StringBuilder.set_Chars(Int32 index, Char value)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonBuffer.ReadString()
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonBuffer.Read()
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonDeserializer.DeserializeObject(JsonToken head, JsonBuffer buffer)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonDeserializer.DeserializeInternal(JsonToken next, JsonBuffer buffer)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonDeserializer.Deserialize(TextReader reader)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Project.GetProjectFromStream(Stream stream, String projectName, String projectPath, ICollection`1 diagnostics)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    --- End of inner exception stack trace ---
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Tooling.BuildManager.BuildInternal(String projectPath)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Tooling.BuildManager.Build()
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Tooling.PackConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Tooling.Program.Main(String[] args)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : Parameter name: index
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at System.Text.StringBuilder.set_Chars(Int32 index, Char value)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonBuffer.ReadString()
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonBuffer.Read()
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonDeserializer.DeserializeObject(JsonToken head, JsonBuffer buffer)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonDeserializer.DeserializeInternal(JsonToken next, JsonBuffer buffer)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Json.JsonDeserializer.Deserialize(TextReader reader)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Project.GetProjectFromStream(Stream stream, String projectName, String projectPath, ICollection`1 diagnostics)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

**Comment by troydai** [comment]
Oh, Dam it. Assign to my self. Please help me to place it in the right milestone @muratg

**Comment by troydai** [comment]
Fixed in e874201acc19854caff9236b420b2864152659c0

**Comment by Flavien** [comment]
So that will be shipped as part of beta8?

**Comment by troydai** [comment]
No, sorry. Unfortunately it doesn't make into beta8. I hope it doesn't significantly impact your project. Thanks for the patience.
