### ISSUE TITLE
Linux could not load assembly if assembly have RID (runtime:coreclr-15724)

### ISSUE THREAD

**Issue by loqix** [aspnet/dnx#2845]
```
System.TypeInitializationException: The type initializer for 'ConsoleApp1.Program' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
 ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   at ConsoleApp1.Program.EnsureInitialization()
   at ConsoleApp1.Program..cctor()
   --- End of inner exception stack trace ---
   at ConsoleApp1.Program..ctor()
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

```C#
    public class Program
    {

        static internal void EnsureInitialization()
        {
#if DNXCORE50
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
#endif
        }

        static Program()
        {
            EnsureInitialization();
        }

        public void Main(string[] args)
        {
            AnonymousPipeServerStream stream = new AnonymousPipeServerStream();
            Console.WriteLine("end");
        }
    }
```

**Comment by muratg** [comment]
@anurse any ideas?

**Comment by anurse** [comment]
I'm going to need some more details to figure this out. @loqix can you attach:

* The content of `project.json` and `project.lock.json`
* The output of `dnx --version`

**Comment by loqix** [comment]
The latest version has no problem
