### ISSUE TITLE
Error when running user-secret

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/dnx#2872]
I'm following the guide at https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration. After installing and executing `user-secret` I get the following error.

```
C:\Users\sayedha\Documents\Visual Studio 2015\Projects\WebApplication1\src\WebApplication1> user-secret
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.ApplicationHost' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Framework.ApplicationHost'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

Here is the result of `dnvm list`

```
C:\Users\sayedha\Documents\Visual Studio 2015\Projects\WebApplication1\src\WebApplication1> dnvm list

Active Version     Runtime Architecture OperatingSystem Alias
------ -------     ------- ------------ --------------- -----
       1.0.0-beta7 clr     x64          win
  *    1.0.0-beta7 clr     x86          win
       1.0.0-beta7 coreclr x64          win
       1.0.0-beta7 coreclr x86          win
```

**Comment by victorhurdugaci** [comment]
Microsoft.Framework.ApplicationHost was renamed to Microsoft.Dnx.ApplicationHost

Are you running from Visual Studio?

**Comment by muratg** [comment]
@sayedihashimi Were you able to resolve this?  There seems to be version mismatch somewhere.

**Comment by muratg** [comment]
:watch:

**Comment by fubar-coder** [comment]
The Wiki is outdated. The correct install command is:
```dnu commands install Microsoft.Framework.SecretManager```

**Comment by muratg** [comment]
@fubar-coder thanks, fixed.

**Comment by CallMeLaNN** [comment]
I got the same here with `beta8`. Initially I got the same issue like OP. [I can't uninstall it. Then I force install the new one](https://github.com/aspnet/dnx/issues/3138) like:

    dnu commands install Microsoft.Framework.SecretManager --overwrite

However still receive this:

    System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Dnx.ApplicationHost' or one of its dependencies.

Note that it already renamed to `Dnx` instead of `Framework`.

**Comment by CallMeLaNN** [comment]
This steps works for me:

    dnvm use 1.0.0-beta8
    dnu commands install Microsoft.Framework.SecretManager -o
    dnu restore
    user-secret -h

The `Microsoft.Framework.SecretManager` package or `user-secret` command should be used in `1.0.0-beta8`. I forgot to switch back to `1.0.0-beta8` after using `SecretManager` for `1.0.0-beta5`.

**Comment by dontbesorry80** [comment]
Can Anyone help me with this. I can't get the secret-manager to work. 
My DNX version is 1.0.0-rc1-final.
The SecretManager seems to install correctly using the commands above.
The dnu restore also works.
I've ensured my global.json has the same dnx version.
However when I run user-secret -h I get the following error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Framework.SecretManager.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
   at Microsoft.Framework.SecretManager.Program..ctor(IRuntimeEnvironment runtimeEnv)
```

**Comment by davidfowl** [comment]
What version of the secret manager are you using?

**Comment by dontbesorry80** [comment]
Inside the package folder it says 1.0.0-beta8. I just ran the command above I didn't specify a version anywhere. Am I supposed to?

**Comment by muratg** [comment]
The new package name for the command is `Microsoft.Extensions.SecretManager`.  Please use that instead.

**Comment by dontbesorry80** [comment]
Bingo! Thank you SO much for the help.

**Comment by muratg** [comment]
Glad that it helped. I updated the wiki page to reflect the new package name as well.

Closing this one, but if folks hit more issues, please file a new one!

**Comment by chekkan** [comment]
I've followed the instructions above and installed the `Microsoft.Extensions.SecretManager`. However getting the error `critical: Command failed : Missing 'userSecretsId' in 'project.json'` when i run `user-secret list` command.
![image](https://cloud.githubusercontent.com/assets/217568/12875524/8818ba4c-cde4-11e5-9d05-d5e594c4e496.png)

**Comment by muratg** [comment]
@chekkan Like the error code suggests, you'll need to add a top level `userSecretsId` key in your project.json.  See an example [here](https://github.com/Eilon/ProjectKIssueList/blob/master/src/Hubbup.Web/project.json#L30)
