### ISSUE TITLE
Race condition in breadcrumbs

### ISSUE THREAD

**Issue by Tratcher** [aspnet/dnx#2876]
```
[Smoke:WebListener:CoreClr:x86] Unhandled Exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
[Smoke:WebListener:CoreClr:x86]    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
[Smoke:WebListener:CoreClr:x86]    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
[Smoke:WebListener:CoreClr:x86]    at System.Collections.Generic.List`1.Enumerator.MoveNext()
[Smoke:WebListener:CoreClr:x86]    at Microsoft.Dnx.Runtime.Servicing.Breadcrumbs.WriteAllBreadcrumbsInternal()
[Smoke:WebListener:CoreClr:x86]    at Microsoft.Dnx.Runtime.Servicing.Breadcrumbs.<>c.<WriteAllBreadcrumbs>b__16_0(Object state)
[Smoke:WebListener:CoreClr:x86]    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
[Smoke:WebListener:CoreClr:x86]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[Smoke:WebListener:CoreClr:x86]    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[Smoke:WebListener:CoreClr:x86]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Smoke:WebListener:CoreClr:x86]    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
This happened running the MusicStore functional tests. This is the second time I've seen it happen today.
@victorhurdugaci

**Comment by Tratcher** [comment]
Something has definitely regressed here, this caused Universe Tests to fail four times today in both dev and release. I also saw it once in a local build (ServerTests?).
/cc: @muratg

**Comment by muratg** [comment]
@victorhurdugaci Please investigate ASAP.
