### ISSUE TITLE
Dnu publish fails to copy relative file sources in CoreClr

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2958]
I was trying to fix some MusicStore tests on CoreClr and Linux combination where I hit this issue. 
I do not see this issue when using Mono though.

![image](https://cloud.githubusercontent.com/assets/6559784/10419202/d3cdafa6-7024-11e5-8393-3e4c421fb326.png)

Exception:

```
Using Project dependency WebApplication37 1.0.0 for DNXCore,Version=v5.0
  Copying source code from Project dependency WebApplication37
    Source /home/kiran/github/kichalla/dnurestorerepro/src/WebApplication37/project.json
    Target /tmp/reprocodeasfdsafdasfas/approot/src/WebApplication37
System.UnauthorizedAccessException: Access to the path '/test/FooLibrary' is denied.
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Dnx.Tooling.Publish.PublishProject.CopyRelativeSources(Project project)
   at Microsoft.Dnx.Tooling.Publish.PublishProject.EmitSource(PublishRoot root)
   at Microsoft.Dnx.Tooling.Publish.PublishProject.Emit(PublishRoot root)
   at Microsoft.Dnx.Tooling.Publish.PublishRoot.Emit()
   at Microsoft.Dnx.Tooling.Publish.PublishManager.Publish()
   at Microsoft.Dnx.Tooling.PublishConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Dnx.Tooling.Program.Main(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
```

Repro solution:
https://github.com/kichalla/dnurestorerepro

Repro command(mimicking the command that is used in MusicStore tests)..fix the following command as you need:

```
/home/kiran/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc1-15857/bin/dnu publish /home/kiran/github/kichalla/dnurestorerepro/src/WebApplication37 -o /tmp/reprocodeasfdsafdasfas --runtime dnx-coreclr-linux-x64.1.0.0-rc1-15857
```

**Comment by kichalla** [comment]
I see now that this issue repros even on Windows and CoreClr..so changing issue title...

It *works* on the 15879 version but not the later 15888 one.

![image](https://cloud.githubusercontent.com/assets/6559784/10471596/8977fb4c-71cc-11e5-90ac-0e7d06a8c9be.png)

**Comment by victorhurdugaci** [comment]
There seems to be a bug in music store that's disabled because of this issue. Is it still happening? Can we reenable or delete the test?
