### ISSUE TITLE
TargetInvocationException thrown when calling GetExport on a non referenced Lib using CompilationEngine from DTH

### ISSUE THREAD

**Issue by Jetski5822** [aspnet/dnx#2984]
I created a little test project so you can see the bug.

https://github.com/Jetski5822/DNXTargetInvoException

Essentially, when you try to call GetExport on a project that is not referenced (in the project.json file) using the Compilation Engine, a Target Invocation Exception is thrown. This only happens when firing up the system in Visual Studio.

```
            var applicationEnvironment = _serviceProvider.GetService<IApplicationEnvironment>();
            var runtimeEnvironment = _serviceProvider.GetService<IRuntimeEnvironment>();
            var assemblyLoadContextAccessor = _serviceProvider.GetService<IAssemblyLoadContextAccessor>();    

            var moduleContext = new ModuleLoaderContext(
                @"d:\TIEBug\ConsoleApp1\src\ClassLibrary1",
                applicationEnvironment.RuntimeFramework);

            var engine = new CompilationEngine(new CompilationEngineContext(
                applicationEnvironment,
                runtimeEnvironment,
                assemblyLoadContextAccessor.Default,
                new CompilationCache()));

            var exporter = engine.CreateProjectExporter(
                moduleContext.Project, 
                moduleContext.TargetFramework, 
                applicationEnvironment.Configuration);

            // Throws Target Invocation Exception here.
            var exports = exporter.GetExport(moduleContext.Project.Name);
```

```
System.Reflection.TargetInvocationException was unhandled
Message: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Additional information: Exception has been thrown by the target of an invocation.

at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
at System.Activator.CreateInstance(Type type, Object[] args)
at Microsoft.Dnx.Runtime.Common.DependencyInjection.ActivatorUtilities.<>c__DisplayClass4_0.<CreateFactory>b__0(IServiceProvider services)
at Microsoft.Dnx.Runtime.Common.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider services, Type type)
at Microsoft.Dnx.Compilation.CompilationEngine.GetCompiler(TypeInformation provider, IAssemblyLoadContext loadContext)
at Microsoft.Dnx.Compilation.LibraryExporter.<>c__DisplayClass17_0.<ExportProject>b__0(CacheContext ctx)
at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at System.Lazy`1.get_Value()
at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
at Microsoft.Dnx.Compilation.LibraryExporter.ExportProject(ProjectDescription project, String aspect)
at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(LibraryDescription library, String aspect)
at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name, String aspect)
at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name)
```

**Comment by anurse** [comment]
It's definitely possible there's something weird there. `Microsoft.Dnx.Compilation` and `Microsoft.Dnx.Runtime` are not designed to be used by applications at all (they were published due to accidental usage in other ASP.NET 5 projects and have been removed from newer versions). I would strongly discourage you from referencing those packages as binaries. If you want to take elements of the source and use them, that's more feasible, but those APIs are extremely volatile and only designed to work in the runtime code itself.

**Comment by Jetski5822** [comment]
What would you suggest using instead to load a project on the fly that is not referenced?

**Comment by anurse** [comment]
Right now, that's not a supported scenario. If you want to take some code from DNX to see if you can make it work, go for it, but we don't intend to support it for v1. If it's important to you, we'll look at it in future planning!

**Comment by Jetski5822** [comment]
Darn, I need to to support module loading in Orchard :(

**Comment by Jetski5822** [comment]
One thing I didnt mention is that when I run this through Kestrel from the command line, the code works fine. It only fails when F5ed through Visual Studio.
