### ISSUE TITLE
Update to 1.0.0-beta8 results in exception when running dnx 

### ISSUE THREAD

**Issue by jschwarty** [aspnet/dnx#2987]
Updated to beta8 via `dnvm upgrade` at command prompt.
Current project.json file looks like:

```json
{
  "version": "1.0.0-*",
  "webroot": "wwwroot",
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "packExclude": [
    "**.kproj",
    "**.user",
    "**.vspscc"
  ],
  "dependencies": {
    "Microsoft.AspNet.Diagnostics": "1.0.0-*",
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-*",
    "Microsoft.AspNet.Authentication": "1.0.0-*",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-*",
    "System.Net.Http": "4.0.0",
    "Microsoft.Framework.WebEncoders": "1.0.0-*",
    "Microsoft.Framework.Logging": "1.0.0-*",
    "Microsoft.Framework.Logging.Console": "1.0.0-*",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-*",
    "Microsoft.Framework.Configuration.Json": "1.0.0-*",
    "Microsoft.Framework.Runtime.Abstractions": "1.0.0-*",
    "Microsoft.AspNet.Hosting": "1.0.0-*",
    "Newtonsoft.Json": "6.0.6"
  },
  "commands": {
    "web": "Microsoft.AspNet.Hosting --config hosting.ini"
  },
  "frameworks": {
    "dnx451": {},
    "dnxcore50": {}
  }
}
```
Ran `dnu restore` from command prompt to get new project.lock.json file generated.
Then, from command prompt, running `dnx web` results in:

```
System.FormatException: Could not parse the JSON file. Error on line number '0': 'server=Microsoft.AspNet.Server.WebListener'. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: s. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Microsoft.Framework.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Framework.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Framework.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Framework.Configuration.Json.JsonConfigurationProvider.Load()
   at Microsoft.Framework.Configuration.ConfigurationBuilder.Add(IConfigurationProvider configurationProvider)
   at Microsoft.Framework.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder configurationBuilder, String path, Boolean optional)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: s. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Microsoft.Framework.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Framework.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
```
Attempting to run `dnx --debug web` from command prompt and attaching debugger in Visual Studio 2015 to the process results in debugger just exiting out (I am assuming this is because the exception is coming from dnx and not from my project code...?)

**Comment by victorhurdugaci** [comment]
Hosting tries to load `Microsoft.AspNet.Hosting.json`. https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Program.cs#L15

Do you have such a file? If yes, can you post it here?

**Comment by victorhurdugaci** [comment]
Here's how the "web" command should look like: https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/project.json#L44

**Comment by jschwarty** [comment]
So the config should now contain JSON then? I had a hosting.ini file that looked like:

```
server=Microsoft.AspNet.Server.WebListener
server.urls=http://localhost:5000
```

When I updated this to be:

```json
{
	"server" : "Microsoft.AspNet.Server.WebListener",
	"server.urls" : "http://localhost:5000"
}
```
it worked. Is there updated documentation yet for beta8 that shows an example of this?

**Comment by chrilith** [comment]
@jschwarty same for me. Had to convert it to JSON. Thanks!
