### ISSUE TITLE
Discovering tests fails due to design time host project compiler exception

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2992]
I am using the final beta8 WTE build and latest DNX.

Open MVC solution, open test explorer and do a 'build solution' and you should see following exception stack trace in the output window

```
------ Discover test started ------
------ Test started: Project: Microsoft.AspNet.Mvc.Abstractions.Test ------
Starting  Microsoft.Dnx.TestHost [C:\Users\kichalla\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15904\bin\dnx.exe --appbase "C:\github\mvc\test\Microsoft.AspNet.Mvc.Abstractions.Test" Microsoft.Dnx.ApplicationHost --port 32237 Microsoft.Dnx.TestHost --port 32422 --parentProcessId 18388]
Connected to Microsoft.Dnx.TestHost
Discovering tests in 'C:\github\mvc\test\Microsoft.AspNet.Mvc.Abstractions.Test\project.json'
Error discovering tests in 'C:\github\mvc\test\Microsoft.AspNet.Mvc.Abstractions.Test\project.json'. 
Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dnx.Compilation.DesignTime.DesignTimeHostProjectCompiler.CompileProject(CompilationProjectContext projectContext, Func`1 referenceResolver, Func`1 resourcesResolver)
   at Microsoft.Dnx.Compilation.LibraryExporter.<>c__DisplayClass17_0.<ExportProject>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.LibraryExporter.ExportProject(ProjectDescription project, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(LibraryDescription library, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name)
   at Microsoft.Dnx.Runtime.Compilation.RuntimeLibraryExporter.GetExport(String name)
   at Microsoft.Dnx.TestHost.TestServices.CreateTestServices(IServiceProvider applicationServices, Project project, ReportingChannel channel)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass2_0.<<Main>b__0>d.MoveNext()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
---> (Inner Exception #0) System.InvalidOperationException: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dnx.Compilation.DesignTime.DesignTimeHostProjectCompiler.CompileProject(CompilationProjectContext projectContext, Func`1 referenceResolver, Func`1 resourcesResolver)
   at Microsoft.Dnx.Compilation.LibraryExporter.<>c__DisplayClass17_0.<ExportProject>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.LibraryExporter.ExportProject(ProjectDescription project, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(LibraryDescription library, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name)
   at Microsoft.Dnx.Runtime.Compilation.RuntimeLibraryExporter.GetExport(String name)
   at Microsoft.Dnx.TestHost.TestServices.CreateTestServices(IServiceProvider applicationServices, Project project, ReportingChannel channel)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass2_0.<<Main>b__0>d.MoveNext()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
<---

========== Discover test finished: 0 found (0:00:03.8563568) ==========

```

@vijayrkn

**Comment by muratg** [comment]
This is a dup of https://github.com/aspnet/dnx/issues/2982

@troydai will be investigating.
