### ISSUE TITLE
DNU restore fails on Linux

### ISSUE THREAD

**Issue by Flavien** [aspnet/dnx#2995]
I am running ``dnu restore`` on Unbuntu 14.04, and I immediately get an exception:

```
root@e592256dc8e2:/openchain.server/approot/src/Openchain.Server# dnu restore
Loaded module: dnx.coreclr.so
Found export: CallApplicationMain
Information: [DomainManager] Using CoreCLR
Information: [LoaderContainer]: Load name=Microsoft.Dnx.Tooling, Culture=neutral, PublicKeyToken=null
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Dnx.Tooling, Culture=neutral, PublicKeyToken=null in 14ms
Information: [Bootstrapper] Runtime Framework: DNXCore,Version=v5.0
Information: [LoaderContainer]: Load name=System.Diagnostics.Process, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [PathBasedAssemblyLoader]: Loaded name=System.Diagnostics.Process, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in 0ms
Microsoft .NET Development Utility CoreClr-x64-1.0.0-beta8-15858

Information: [LoaderContainer]: Load name=Microsoft.Dnx.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Dnx.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in 1ms
Information: [LoaderContainer]: Load name=System.Xml.ReaderWriter, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [PathBasedAssemblyLoader]: Loaded name=System.Xml.ReaderWriter, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in 1ms
Information: [LoaderContainer]: Load name=System.Xml.XDocument, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [PathBasedAssemblyLoader]: Loaded name=System.Xml.XDocument, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in 0ms
Information: [LoaderContainer]: Load name=System.Text.RegularExpressions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [PathBasedAssemblyLoader]: Loaded name=System.Text.RegularExpressions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in 0ms
Information: [LoaderContainer]: Load name=System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [PathBasedAssemblyLoader]: Loaded name=System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in 0ms
Information: [LoaderContainer]: Load name=System.Net.Http, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [PathBasedAssemblyLoader]: Loaded name=System.Net.Http, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in 0ms
----------
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'libcurl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.HttpInitializer.EnsureCurlIsInitialized()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.libcurl..cctor()
   --- End of inner exception stack trace ---
   at Interop.libcurl.curl_version_info(Int32 curlVersionStamp)
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClient..ctor()
   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource..ctor(String baseUri, String userName, String password, Reports reports)
   at Microsoft.Dnx.Tooling.PackageFeedCache.CreatePackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
   at Microsoft.Dnx.Tooling.PackageFeedCache.<>c__DisplayClass1_0.<GetPackageFeed>b__0(PackageSource _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Dnx.Tooling.PackageFeedCache.GetPackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
   at Microsoft.Dnx.Tooling.RestoreCommand.AddRemoteProvidersFromSources(List`1 remoteProviders, List`1 effectiveSources, PackageFeedCache packageFeeds, SummaryContext summary)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
The type initializer for 'System.Net.Http.CurlHandler' threw an exception.

NuGet Config files used:
    /root/.config/NuGet/NuGet.Config
```

The root of the problem seems to be **Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.**

How can I get this to work?

**Comment by Flavien** [comment]
Disregard, I found the problem. I needed the package ``libcurl3-gnutls`` instead of ``libcurl3-dev``.

**Comment by linquize** [comment]
Yes, `libcurl3-gnutls`
