### ISSUE TITLE
Bootstrapping issue causing unit test failures

### ISSUE THREAD

**Issue by cesarbs** [aspnet/dnx#3014]
System.MissingMethodException : Method not found: 'Void Microsoft.Dnx.Compilation.CompilationProjectContext..ctor(Microsoft.Dnx.Compilation.CompilationTarget, System.String, System.String, System.String, System.String, System.String, System.String, System.Version, Boolean, Microsoft.Dnx.Compilation.CompilationFiles, Microsoft.Dnx.Runtime.ICompilerOptions)'.
   at Microsoft.Dnx.Compilation.CSharp.Tests.CompilationContextFacts.CreateMockProject()
   at Microsoft.Dnx.Compilation.CSharp.Tests.CompilationContextFacts.DefaultConstructorInitializeCorrectly() in C:\ba\2dd455456ad7132\test\Microsoft.Dnx.Compilation.CSharp.Tests\CompilationContextFacts.cs:line 20System.MissingMethodException : Method not found: 'Void Microsoft.Dnx.Compilation.CompilationProjectContext..ctor(Microsoft.Dnx.Compilation.CompilationTarget, System.String, System.String, System.String, System.String, System.String, System.String, System.Version, Boolean, Microsoft.Dnx.Compilation.CompilationFiles, Microsoft.Dnx.Runtime.ICompilerOptions)'.
   at Microsoft.Dnx.Compilation.CSharp.Tests.CompilationContextFacts.CreateMockProject()
   at Microsoft.Dnx.Compilation.CSharp.Tests.CompilationContextFacts.DefaultConstructorInitializeCorrectly() in C:\ba\2dd455456ad7132\test\Microsoft.Dnx.Compilation.CSharp.Tests\CompilationContextFacts.cs:line 20

**Comment by moozzyk** [comment]
@cesarbs - is this happening on CoreClr only by any chance?

**Comment by cesarbs** [comment]
No.
