### ISSUE TITLE
DNX error on run [Bug]

### ISSUE THREAD

**Issue by gvx111** [aspnet/dnx#3043]
after dnu restore
<pre>System.TypeLoadException: Could not load type 'Microsoft.Dnx.Runtime.PlatformServices' from assembly 'Microsoft.Dnx.Runtime.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)</pre>
dnx 1.0.0-rc1-15838

Please help someone I can't run application :|

**Comment by Codenator81** [comment]
Have the same problem. It is came from change in namespace Microsoft.Dnx.Runtime to Microsoft.Extensions.PlatformAbstractions. Try change it in your code and do dnu restore.
Same changes came late not sinhronized that way work on unstable little tricky. Just have patient and do 
```console
dnvm upgrade -u
dnu restore
```
If it not help wait 3-4 hour and try again. For now I don`t know different method.

**Comment by gvx111** [comment]
@Codenator81 thank you it works :)
