### ISSUE TITLE
Running RC1

### ISSUE THREAD

**Issue by gvx111** [aspnet/dnx#3066]
<pre>System.InvalidOperationException: No service for type 'Microsoft.Extensions.Plat
formAbstractions.IApplicationEnvironment' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequ
iredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequ
iredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] arg
s)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String
 applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment
env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, Bootstr
apperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, Bootstrapper
Context bootstrapperContext)</pre>
I have been updated all references.

**Comment by davidfowl** [comment]
@gvx111 Did you update the dnx as well?

**Comment by gvx111** [comment]
1.0.0-rc1-15838 @davidfowl

**Comment by davidfowl** [comment]
Is that the latest? Try updating it.

**Comment by gvx111** [comment]
1.0.0-rc1-15921   clr     x86 
1.0.0-rc1-15921   coreclr x86
I have updated but another error
<pre>
System.MissingMethodException: Method not found: 'Void Microsoft.Extensions.Configuration.ConfigurationBuilder..ctor(Microsoft.Extensions.Configuration.IConfigurationProvider[])'.
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass8_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()</pre>

**Comment by Codenator81** [comment]
Latest is dnx-clr-win-x86.1.0.0-rc1-15996
To get latest unstable:
```console
set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev
dnvm upgrade -u 
```

**Comment by gvx111** [comment]
Thank you.

**Comment by gvx111** [comment]
Thank you.

**Comment by endeffects** [comment]
Hi Guys,

i have the same problem and was not able to fix this with upgrade above.

dnvm list

  *    1.0.0-rc2-16138   clr     x86          win             default

project.json

    "dependencies": {
        "Microsoft.CSharp": "4.0.1-*",
        "Microsoft.AspNet.Mvc": "6.0.0-*",
        "Microsoft.AspNet.IISPlatformHandler": "1.0.0-*",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
        "Microsoft.AspNet.StaticFiles": "1.0.0-*",
        "Microsoft.ApplicationInsights.AspNet": "1.0.0-*",
        "Microsoft.Extensions.PlatformAbstractions": "1.0.0-*",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-*",
    },

    "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel"
    },

    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    },

global.json

{
    "sdk": {
        "version": "1.0.0-rc2-16128"
    }
}

dnx web

System.InvalidOperationException: No service for type 'Microsoft.Dnx.Runtime.IApplicationEnvironment' has been registered.
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
   at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Codenator81** [comment]
@endeffects Try to remove sdk section in global.json
and redo 
dnu restore

**Comment by endeffects** [comment]
Thanks, i've tried this in the past too without luck. I've cleared my whole library and runtime cache and it seems to work now.

1) Deleting content of following folders
	%USERPROFILE%\.dnx\bin\packages
	%USERPROFILE%\.dnx\packages
	%USERPROFILE%\.dnx\runtimes
2) set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev
4) dnvm upgrade 
5) dnvm upgrade -u 
6) updating NuGet.Config
7) dnu restore

**Comment by gpeipman** [comment]
I get this error when I publish my web application to Azure websites. Any idea what to do on Azure to get rid of this error?

**Comment by gpeipman** [comment]
If you are upgrading your web application from previous version then add the following line to startup class:

public static void Main(string[] args) => WebApplication.Run<Startup>(args);

**Comment by davidfowl** [comment]
@gpeipman Don't forget the emitEntryPoint: true in the project.json file.
