### ISSUE TITLE
PathTooLongException on "dnu restore"

### ISSUE THREAD

**Issue by henningst** [aspnet/dnx#3086]
I'm seing a PathTooLongException when npm is running "dnu restore --parallel".
```
F:\TeamCityAgent\BuildAgent\work\d64fea20c170fe95\DemoAts>.\build.cmd
Adding C:\Users\operations\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15996\bin to
process PATH
info: Build v2: False
info: Testing for command: node --version
v4.1.2
info:    command found (0 exit code)
info: Exec
info:   program: cmd
info:   commandline: /S /C "npm install "
info:   workingdir: F:\TeamCityAgent\BuildAgent\work\d64fea20c170fe95\DemoAts\sr
c\DemoAts
npm WARN package.json HRMTS@0.0.1 No README data
npm WARN package.json HRMTS@0.0.1 No license field.
info: Exec
info:   program: node
info:   commandline: "F:\TeamCityAgent\BuildAgent\work\d64fea20c170fe95\DemoAts\
bin\nodejs\node_modules\bower\bin\bower" install  --config.interactive=false
info:   workingdir: F:\TeamCityAgent\BuildAgent\work\d64fea20c170fe95\DemoAts\sr
c\DemoAts
info: Exec
info:   program: cmd
info:   commandline: /C dnu restore  --parallel
info:   workingdir: F:\TeamCityAgent\BuildAgent\work\d64fea20c170fe95\DemoAts
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-15996

----------
System.IO.PathTooLongException: The specified path, file name, or both are too l
ong. The fully qualified file name must be less than 260 characters, and the dir
ectory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPath
Length, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String origina
lUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`
1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String
directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.Find(String restoreDirector
y, IEnumerable`1& projectJsonFiles)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
The specified path, file name, or both are too long. The fully qualified file na
me must be less than 260 characters, and the directory name must be less than 24
8 characters.
fail: Exit code 1 from cmd
fail: Stack trace:
   at View5194434b883d4922bbf3946c7cfa51da.<RenderViewLevel0>b__c9() in c:\Users
\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 1005
8
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View5194434b883d4922bbf3946c7cfa51da.StartingTarget(String name) in c:\Use
rs\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 37
31
   at View5194434b883d4922bbf3946c7cfa51da.<RenderViewLevel0>b__88() in c:\Users
\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 4311

   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View5194434b883d4922bbf3946c7cfa51da.StartingTarget(String name) in c:\Use
rs\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 37
31
   at View5194434b883d4922bbf3946c7cfa51da.<RenderViewLevel0>b__89() in c:\Users
\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 4328

   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View5194434b883d4922bbf3946c7cfa51da.StartingTarget(String name) in c:\Use
rs\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 37
31
   at View5194434b883d4922bbf3946c7cfa51da.<RenderViewLevel0>b__8a() in c:\Users
\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 4345

   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View5194434b883d4922bbf3946c7cfa51da.StartingTarget(String name) in c:\Use
rs\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 37
31
   at View5194434b883d4922bbf3946c7cfa51da.<RenderViewLevel0>b__8b() in c:\Users
\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 4362

   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View5194434b883d4922bbf3946c7cfa51da.<RenderViewLevel0>b__83() in c:\Users
\operations\AppData\Local\Temp\2\064811a438184f3db19daee702b82c90-1.cs:line 4218

   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

```

It looks like the same issue as posted in this comment: https://github.com/aspnet/dnx/issues/1173#issuecomment-147069891

**Comment by henningst** [comment]
After looking a bit closer on this, it looks like this is a problem with Sake trying to install the npm module Gulp which has loads and loads of nested directories with dependent npm modules.
