### ISSUE TITLE
Microsoft.Extensions.PlatformAbstractions - A strongly-named assembly is required

### ISSUE THREAD

**Issue by Kieranties** [aspnet/dnx#3139]
Since the strong name changes I've been unable to run my dnx apps.

I have a simple command line app that deals with the `ILibraryManager`.  It's been updated to use `PlatformServices.Default.LibraryManager` instead of injecting the instance.

Now when calling `dnx run` I get the following error (runtime: 1.0.0-rc1-16048)

```
> dnx run
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0
, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. A strongly-named assembly is required. (
Exception from HRESULT: 0x80131044)
File name: 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
' ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
   at CodeAuthoringSample.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider service
Provider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

The packages in play are:

```
Package references:
  Microsoft.AspNet.FileProviders.Abstractions 1.0.0-rc1-15783
  Microsoft.AspNet.Hosting.Abstractions 1.0.0-rc1-15944
  Microsoft.AspNet.Http.Abstractions 1.0.0-rc1-15939
  Microsoft.AspNet.Http.Features 1.0.0-rc1-15939
  Microsoft.Extensions.Configuration 1.0.0-rc1-15812
  Microsoft.Extensions.Configuration.Abstractions 1.0.0-rc1-15812
  Microsoft.Extensions.Configuration.Binder 1.0.0-rc1-15812
  Microsoft.Extensions.Configuration.FileExtensions 1.0.0-rc1-15812
  Microsoft.Extensions.Configuration.Ini 1.0.0-rc1-15812
  Microsoft.Extensions.Configuration.Json 1.0.0-rc1-15812
  Microsoft.Extensions.Configuration.Xml 1.0.0-rc1-15812
* Microsoft.Extensions.DependencyInjection 1.0.0-rc1-15777
  Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-15777
* Microsoft.Extensions.Logging 1.0.0-rc1-15803
  Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-15803
* Microsoft.Extensions.Logging.Console 1.0.0-rc1-15803
  Microsoft.Extensions.OptionsModel 1.0.0-rc1-15791
  Microsoft.Extensions.PlatformAbstractions 1.0.0-rc1-16110
  Microsoft.Extensions.Primitives 1.0.0-rc1-15829
  Microsoft.Extensions.WebEncoders.Core 1.0.0-rc1-15939
  Newtonsoft.Json 6.0.6
```

**Comment by pranavkm** [comment]
The runtime version (16048) seems older than PlatformAbstractions (16110). Could you try updating the runtime to see if it fixes the issue?

**Comment by Kieranties** [comment]
Ah!  Of course, I've been using packages from the aspnetrelease feed, but hadn't updated `dnvm` to use the same.

Setting `env:DNX_UNSTABLE_FEED` to the correct feed and updated to runtime 1.0.0-rc1-16110 fixed the issue.  Many thanks
