### ISSUE TITLE
Problem with diacritical letters

### ISSUE THREAD

**Issue by rosieks** [aspnet/dnx#3143]
I just created new project and it looks like there are some problems with diacritical letters while restoring packages:

```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\Sławek\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\dnx.exe "C:\Users\Sławek\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "C:\Users\Sławek\documents\visual studio 14\Projects\ConsoleApplication9\ClassLibrary1" -s "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-beta8-15858
Restoring packages for C:\Users\S�awek\documents\visual studio 14\Projects\ConsoleApplication9\ClassLibrary1\project.json
Writing lock file C:\Users\S�awek\documents\visual studio 14\Projects\ConsoleApplication9\ClassLibrary1\project.lock.json
----------
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\S�awek\.dnx\packages\System.IO\4.0.0\System.IO.4.0.0.nupkg.sha512'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.Dnx.Tooling.Utils.LockFileUtils.CreateLockFilePackageLibrary(LockFilePackageLibrary previousLibrary, IPackagePathResolver resolver, IPackage package, String correctedPackageName)
   at Microsoft.Dnx.Tooling.RestoreCommand.WriteLockFile(LockFile previousLockFile, String projectLockFilePath, Project project, List`1 graphItems, PackageRepository repository, IProjectResolver projectResolver, IEnumerable`1 contexts)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
Could not find a part of the path 'C:\Users\S�awek\.dnx\packages\System.IO\4.0.0\System.IO.4.0.0.nupkg.sha512'.
NuGet Config files used:
    C:\Users\S�awek\AppData\Roaming\NuGet\nuget.config
Feeds used:
    C:\Program Files (x86)\Microsoft Web Tools\DNU
```

**Comment by Eilon** [comment]
@rosieks can you tell us the Unicode code points of these characters? That will help us reproduce the issue.

**Comment by pgrudzien12** [comment]
+1

I'm sure it will be ł letter. 

Unicode U+hex notation: U+0142

https://r12a.github.io/uniview/?charlist=%C5%82

**Comment by rosieks** [comment]
Exactly, it's U+0142 (ł)

**Comment by rosieks** [comment]
I just notice that I don't have such directory. DNX is looking for path:
`C:\Users\Sławek\.dnx\packages\System.IO\4.0.0\System.IO.4.0.0.nupkg.sha512`
and I have only such path:
`C:\Users\Sławek\.dnx\packages\System.IO\4.0.0.0\System.IO.4.0.0.0.nupkg.sha512`

So in that case I think that the only issue with ł letter is about displaying it in VS output

**Comment by davidfowl** [comment]
Delete your packages folder. Older versions of dnx didn't normalize the version and newer ones do.

**Comment by rosieks** [comment]
Thanks @davidfowl 
That helps.
