### ISSUE TITLE
`dnu publish` fails if project has `--lock`ed dependencies

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#3168]
1. `$env:DNX_Feed='https://www.myget.org/F/aspnetrc1/api/v2'`
2. Update `$env:AppData\NuGet\NuGet.Config` to enable just https://www.myget.org/F/aspnetrc1/api/v3/index.json and https://www.nuget.org/api/v2/. Ex. below.
3. `dnvm install -f 1.0.0-rc1-final`
4. `dnvm use 1.0.0-rc1-final`
5. Create an ASP.NET 5 Web Application using latest RC1 templates
6. Shut down VS
7. Remove all cached packages: `rimraf $env:USERPROFILE\.dnx\packages; rimraf C:\Users\dougbu\AppData\Local\dnu\cache`
8. Restore and lock the dependencies: `dnu restore --lock --quiet`
9. Publish: `mkdir C:\Temp\WebSite; dnu publish -o C:\Temp\WebSite --configuration Release --runtime active`
10. Observe failure:

```
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16147

Executing script 'prepublish' in project.json
...
Copying to output path C:\Temp\WebSite
Using Package dependency Microsoft.AspNet.Mvc.Core 6.0.0-rc1-final
Using Package dependency Microsoft.Extensions.WebEncoders 1.0.0-rc1-final
...
Using Project dependency MVC6_RC1_0 1.0.0 for DNX,Version=v4.5.1
  Copying source code from Project dependency MVC6_RC1_0
    Source C:\dd\projects\MVC6_RC1_0\src\MVC6_RC1_0\project.json
    Target C:\Temp\WebSite\approot\src\MVC6_RC1_0

Bundling runtime dnx-clr-win-x86.1.0.0-rc1-final
Error: Could not find a part of the path 'C:\Temp\WebSite\approot\packages\Microsoft.CSharp\4.0.1-beta-23509'.
```

Same issue occurs after locking the dependencies when publishing from VS to Azure, file system, ... Note repro steps are long primarily to eliminate stale packages on the system.

May relate to #2930.

---

Example setup

```
> dnu feeds list|sls -notmatch 'origin|disabled'

Feeds in use:
    C:\Users\dougbu\AppData\Local\NuGet\Cache
    https://www.myget.org/F/aspnetrc1/api/v3/index.json
    https://www.nuget.org/api/v2/
      Offical NuGet Source, enabled by default

NuGet Config files in use:
    C:\Users\dougbu\AppData\Roaming\NuGet\nuget.config
```

Note my `C:\Users\dougbu\AppData\Local\NuGet\Cache` folder contains no DNX packages.

**Comment by Flavien** [comment]
I noticed the same, ``dnu restore --lock`` fails:

``
System.IO.DirectoryNotFoundException: Could not find a part of the path '/opt/dnx/approot/packages/System.Diagnostics.Tracing/4.0.0'.
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()
   at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult)
   at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.Dnx.Tooling.Publish.PublishProject.PrunePackages(PublishRoot root)
   at Microsoft.Dnx.Tooling.Publish.PublishProject.PostProcess(PublishRoot root)
   at Microsoft.Dnx.Tooling.Publish.PublishRoot.Emit()
   at Microsoft.Dnx.Tooling.Publish.PublishManager.Publish()
   at Microsoft.Dnx.Tooling.PublishConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Dnx.Tooling.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
``
