### ISSUE TITLE
DNX_BUILD_KEY_FILE is ignored in RC1

### ISSUE THREAD

**Issue by emgarten** [aspnet/dnx#3245]
DNU is no longer using the environment variable DNX_BUILD_KEY_FILE in RC1.

Steps
1. Set the environment variable DNX_BUILD_KEY_FILE to the full path of a signing key
2. Build with DNU

Expected:
The output will be signed

Actual:
```
[21:53:13][Step 2/9] Error: Value cannot be null.
[21:53:13][Step 2/9] Parameter name: path2
[21:53:13][Step 2/9] Error: Full Exception: System.ArgumentNullException: Value cannot be null.
[21:53:13][Step 2/9] Parameter name: path2
[21:53:13][Step 2/9]    at System.IO.Path.Combine(String path1, String path2)
[21:53:13][Step 2/9]    at Microsoft.Dnx.Compilation.CSharp.CompilerOptionsExtensions.AddSigningOptions(CSharpCompilationOptions options, ICompilerOptions compilerOptions, String projectDirectory)
[21:53:13][Step 2/9]    at Microsoft.Dnx.Compilation.CSharp.CompilerOptionsExtensions.GetCompilationOptions(ICompilerOptions compilerOptions, String projectDirectory)
[21:53:13][Step 2/9]    at Microsoft.Dnx.Compilation.CSharp.CompilerOptionsExtensions.ToCompilationSettings(ICompilerOptions compilerOptions, FrameworkName targetFramework, String projectDirectory)
[21:53:13][Step 2/9]    at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.CompileProject(CompilationProjectContext projectContext, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver)
[21:53:13][Step 2/9]    at Microsoft.Dnx.Compilation.CSharp.RoslynProjectCompiler.CompileProject(CompilationProjectContext projectContext, Func`1 referenceResolver, Func`1 resourcesResolver)
[21:53:13][Step 2/9]    at Microsoft.Dnx.Compilation.LibraryExporter.<>c__DisplayClass17_0.<ExportProject>b__0(CacheContext ctx)
[21:53:13][Step 2/9]    at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
[21:53:13][Step 2/9]    at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
[21:53:13][Step 2/9]    at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
```

See also: https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Compilation.CSharp.Common/CompilerOptionsExtensions.cs#L98-L104

**Comment by moozzyk** [comment]
/cc @cesarbs 

I guess it should be:

` keyFile = Path.GetFullPath(Path.Combine(projectDirectory, keyFile));`

**Comment by muratg** [comment]
Are we doing this as part of DNU -> nuget merger?

**Comment by cesarbs** [comment]
I need a decision on whether to merge or close https://github.com/aspnet/dnx/pull/3247

**Comment by muratg** [comment]
Feel free to merge it (or ping @emgarten first), but I think it's possibly throwaway work if it's not going to be useful in the merger.

**Comment by emgarten** [comment]
This isn't part of DNU it changes how the key is applied during compilation. I would expect this to be needed for CLI also. 

The scenario here is: NuGet has a private key that is used by the CI. It's not public so we can't check it into source control. The current alternative to this env var is to set the path in the project.json file, however the path is only needed on the CI. There's no way to dynamically define this in project.json today.
