### ISSUE TITLE
SslStream.AuthenticateAsClientAsync method 4-parameter overload missing on rc2 on win

### ISSUE THREAD

**Issue by fsoikin** [aspnet/dnx#3271]
I first (mistakenly) [reported this issue in corefx](https://github.com/dotnet/corefx/issues/5064#issuecomment-165879146), but @davidsh suggested that this is a DNX packaging issue, and that I should file the issue here instead.

This started happening since rc2-16294, and still happens on yesterday's rc2-16317. And only on Windows (I am running Windows 10 x64).

Interestingly, only the [4-parameter overload](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/ref/System.Net.Security.cs#L102) is missing, while [the 1-parameter overload](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/ref/System.Net.Security.cs#L101) appears to be fine.

Details:

```
C:\i> ls


    Directory: C:\i


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/18/2015  10:28 AM            262 Program.cs
-a----       12/18/2015  10:27 AM            258 project.json
-a----       12/18/2015  10:27 AM         105977 project.lock.json


C:\i> cat .\project.json
{
        "compilationOptions": {
                "emitEntryPoint": true
        },

        "dependencies": {
                "System.IO": "4.0.11-beta-23409",
                "System.Runtime": "4.0.20-beta-23409",
                "System.Net.Security":  "4.0.0-beta-23409",
        },

        "frameworks": {
                "dnxcore50": { }
        }
}

C:\i> cat .\Program.cs
public static class Program {
   public static void Main(string[] args) {
      var s = new System.Net.Security.SslStream( new System.IO.MemoryStream() );
      s.AuthenticateAsClientAsync( null, null, System.Security.Authentication.SslProtocols.Ssl2, false );
   }
}

C:\i> dnvm use 1.0.0-rc2-16317 -r coreclr
Adding C:\Users\Fyodor\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc2-16317\bin to process PATH

C:\i> dnx run
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task System.Net.Security.SslStream.AuthenticateAsClientAsync(System.String, System.Security.Cryptography.X509Certificates.X509CertificateCollection, System.Security.Authentication.SslProtocols, Boolean)'.
   at Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

C:\i> dnvm use 1.0.0-rc2-16258 -r coreclr
Adding C:\Users\Fyodor\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc2-16258\bin to process PATH

C:\i> dnx run
System.ArgumentNullException: Value cannot be null.
Parameter name: targetHost
   at System.Net.Security.SslState.ValidateCreateContext(Boolean isServer, String targetHost, SslProtocols enabledSslProtocols, X509Certificate serverCertificate, X509CertificateCollection clientCertificates, Boolean remoteCertRequired, Boolean checkCertRevocationStatus, Boolean checkCertName)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c__DisplayClass26_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at Program.Main(String[] args) in C:\i\Program.cs:line 4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

C:\i>
```

Also, here's an interesting bit of trivia that might be related: package `System.Net.Security` of version 23516 (the latest one on [nuget](https://www.nuget.org/packages/System.Net.Security/4.0.0-beta-23516)) has an empty DLL under `net46`. The DLL is there, but doesn't contain any types.

This is why my test project uses previous version 23409. If I put 23516 in `project.json`, the program stops even compiling, complaining that type `SslStream` does not exist.

**Comment by fsoikin** [comment]
Update: still happening on rc2-16319.

**Comment by muratg** [comment]
I recommend testing this with dotnet CLI we're retiring dnx (and it's "runtime") in RC2. You can find some samples for running asp.net 5 apps with dotnet CLI [here](https://github.com/davidfowl/dotnetcli-aspnet5).

**Comment by xanather** [comment]
This is happening to me too.
