### ISSUE TITLE
Dependency restore problem in Ubuntu and Windows

### ISSUE THREAD

**Issue by j2ghz** [aspnet/dnx#3303]
If I put `"runtime.unix.System.Data.SqlClient": "4.0.0-beta-23516"` inside  `"dependencies": {` the app works on ubuntu, on windows there are errors like:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'List<T>' exists in both 'System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	IntranetGJAK.DNX 4.5.1	C:\Users\j200g_000\Documents\GitHubVisualStudio\IntranetGJAK\IntranetGJAK\Models\JSON\Blueimp-FileUpload.cs	17	Active
```
If I put `"runtime.unix.System.Data.SqlClient": "4.0.0-beta-23516"` inside  `"dnxcore50": {` the app works on windows, on ubuntu there's error:
```
File name: 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Data.SqlClient'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Microsoft.Data.Entity.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
   at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
09:39:22.042 [Error] [Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```
I've tried many other variants, like not having runtime.unix.* at all, hoping `"Microsoft.NETCore.Platforms": "1.0.1-*"` would help, but it didn't work (error in ubuntu).
It seems in the first case dnu restores `System.Data.SqlClient`, so ubuntu is ok, but windows gets double libraries. In the second it doesn't restore it (but it should on dnxcore50), so windows is ok, but ubuntu is missing it.

I use full dotnetfx 4.5 on windows, and dnxcore50 on ubuntu (coreclr, not mono)

All dependencies:
```
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "Serilog.Framework.Logging": "1.0.0-rc1-final-10075",
    "System.Data.SqlClient": "4.0.0-beta-23516",
    "Microsoft.NETCore.Platforms": "1.0.1-*"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
        "Serilog.Sinks.Literate": "1.2.0"
      }
    },
    "dnxcore50": {
      "runtime.unix.System.Net.Security": "4.0.0-beta-23516",
      "runtime.unix.System.Data.SqlClient": "4.0.0-beta-23516"
    }
  },
```

**Comment by j2ghz** [comment]
There was a mistake on my part, sorry
