### ISSUE TITLE
Access to "My Music" Denied When Trying to Add a Reference

### ISSUE THREAD

**Issue by notlkk** [aspnet/dnx#3349]
I'm trying out the new ASP.NET 5 RC1 template for Web API. When I try to add a reference to my own class library I get this weird error:

```
 Wrapping project 'EntityFramework' for '.NETFramework,Version=v4.5'
    Source C:\xxxx\source\packages\EntityFramework.5.0.0\lib\net45\EntityFramework.dll
    Target C:\xxxx\source\wrap\EntityFramework\project.json
  Adding project dependency 'EntityFramework.1.0.0-*'
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\xxxx\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe "C:\xxxx\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "C:\xxxx\source\MyWebApi" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231
----------
System.UnauthorizedAccessException: Access to the path 'C:\xxxx\Documents\My Music' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at Microsoft.Dnx.Tooling.PackageFolderFactory.<>c.<CreatePackageFolderFromPath>b__0_0(String dir)
   at Microsoft.Dnx.Tooling.PackageFolderFactory.<>c__DisplayClass0_0.<CreatePackageFolderFromPath>b__2(String x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dnx.Tooling.PackageFolderFactory.CreatePackageFolderFromPath(String path, Boolean ignoreFailedSources, Reports reports)
   at Microsoft.Dnx.Tooling.PackageFeedCache.CreatePackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
   at Microsoft.Dnx.Tooling.PackageFeedCache.<>c__DisplayClass1_0.<GetPackageFeed>b__0(PackageSource _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Dnx.Tooling.PackageFeedCache.GetPackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
   at Microsoft.Dnx.Tooling.RestoreCommand.AddRemoteProvidersFromSources(List`1 remoteProviders, List`1 effectiveSources, PackageFeedCache packageFeeds, SummaryContext summary)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
Access to the path 'C:\xxxx\Documents\My Music' is denied.
NuGet Config files used:
```

Why "My Music"?

**Comment by muratg** [comment]
What does your nuget.config file look like?

**Comment by notlkk** [comment]
I solved the problem with the following steps:

1. dnvm install latest
2. Go to where the project folder is and do "dnu restore"

It's weird and I don't really understand why it happened.

**Comment by muratg** [comment]
:+1:
