### ISSUE TITLE
Exception:Unable to resolve service for type 'Microsoft.Dnx.Compilation.ILibraryExporter' 

### ISSUE THREAD

**Issue by munyirik** [aspnet/dnx#3358]
I'm attempting to run an asp.net 5 server with dnx on my Raspberry Pi 2 (ARM) with Windows IoT Core. I ran into a problem when accessing the server detailed below -

**Repro steps:**
1. Installed arm coreclr with: dnvm install latest -r coreclr -arch arm -u
2. Created new asp.net 5 web application in VS (with no modifications of my own) and published with: dnu publish --out C:\projects\asp5 --runtime dnx-coreclr-win-arm.1.0.0-rc2-16357.
3. Copied the published files to RPi2 and ran the application.
4. Use browser to access the server.

**Result:**
(replaced IP address with x's)
[xx.xx.xx.xxx]: PS C:> .\asparm\approot\web.cmd
Hosting environment: Production
Now listening on: http://xx.xx.xx.xxx:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://xx.xx.xx.xxx:5000/
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method web.Controllers.HomeController.Index with arguments () - ModelState is Valid'
fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Unable to resolve service for type 'Microsoft.Dnx.Compilation.ILibraryExporter' while attempting
to activate 'Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService'.
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Dnx.Compilation.ILibraryExporter' while attempting to
activate 'Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService'.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain,
 ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain,
 ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain,
 ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain,
 ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider
)
         at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey
key, Func`3 valueFactory, TArg arg)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceTyp
e)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.AspNet.Mvc.Razor.Internal.MvcRazorMvcViewOptionsSetup.ConfigureMvc(IServiceProvider serviceProvider, MvcViewOptions op
tions)
         at Microsoft.AspNet.Mvc.Razor.Internal.MvcRazorMvcViewOptionsSetup.<>c__DisplayClass0_0.<.ctor>b__0(MvcViewOptions options)
         at Microsoft.Extensions.OptionsModel.ConfigureOptions`1.Configure(TOptions options)
         at Microsoft.Extensions.OptionsModel.OptionsManager`1.<>c.<get_Value>b__4_0(TOptions options, IConfigureOptions`1 setup)
         at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
         at Microsoft.Extensions.OptionsModel.OptionsManager`1.get_Value()
         at Microsoft.AspNet.Mvc.ViewEngines.CompositeViewEngine..ctor(IOptions`1 optionsAccessor)
      --- End of stack trace from previous location where exception was thrown ---

**Comment by KoalaBear84** [comment]
I'm also trying to run things on RPi2, and having the same problem. It looks like the current dnx runtimes are some sort of broken. But also locally it won't work on RC2.

It only works if I do `dnvm use 1.0.0-rc1-final`, and then indeed use RC1. But that will not work on the Pi because RC2 is the first one with ARM support I guess.

It looks like we need to wait for the RC2 final / dnx -> dotnet rename. Also Entity Framework RC2 branch is currently broken, unable to use EntityFramework.Commands.

**Comment by munyirik** [comment]
Thanks @KoalaBear84. I actually got it working yesterday on my RPi2 after using 1.0.0-rc1-final. If you give it a try it should work. Here's what I did to publish:

* Run: set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetmaster/api/v3 <- This will tell dnvm where to get arm rc1-final.
* Run: dnvm install 1.0.0-rc1-final -r coreclr -arch arm -u
* Publish with: dnu publish --out [your publish path] --no-source --runtime dnx-coreclr-win-arm.1.0.0-rc1-final
* After copying the published files to your device you also need to [copy libuv](https://github.com/aspnet/KestrelHttpServer/issues/216#issuecomment-176472061) to avoid another error.

**Comment by munyirik** [comment]
Also check that your project.json file is using rc1-final version of Kestrel.

**Comment by KoalaBear84** [comment]
Good to hear!

That's strange, I get this when running:

    C:\Users\User>dnvm install 1.0.0-rc1-final -r coreclr -arch arm -u
    Default unstable feed (https://www.myget.org/F/aspnetvnext/api/v2) is being overridden by the value of the DNX_UNSTABLE_FEED environment variable (https://www.myget.org/F/aspnetmaster/api/v3)
    Unable to find any runtime packages on the feed!
    At C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1:610 char:9
    +         throw "Unable to find any runtime packages on the feed!"
    +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (Unable to find ...es on the feed!:String) [], RuntimeException
        + FullyQualifiedErrorId : Unable to find any runtime packages on the feed!


It doesn't find 'any' runtime packages on the feed. It does see that I overriden the default unstable branch, which is good.

**Comment by KoalaBear84** [comment]
Ahh. Looks like my (?) dnvm does not work with "v3" API level or so.

This works:

    set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetmaster/api/v2

**Comment by KoalaBear84** [comment]
I had some progress. After publishing I copied everything to the Pi and got the following error when running the website `cmd /c web.cmd`:

    Failed to locate or load coreclr.dll

And indeed, `coreclr.dll` is not a file on disk:

    C:\Users\User\.dnx\runtimes\dnx-coreclr-win-arm.1.0.0-rc1-final

But the file `coreclr.dll` is part of `dnx-coreclr-win-arm.1.0.0-rc2-16357`

Could you check if you do have this?

I'm also curious if we could auto start a website when the Pi starts.. Hopefully there will be more information when RC2 comes out.

**Comment by munyirik** [comment]
Ah yes. I forgot to add that step. I copied the missing files (including coreclr.dll) in the bin directory from rc2-16357. Only the missing files. Can you try that?

**Comment by munyirik** [comment]
and this is the bin directory I mean -> <your publish folder>\approot\runtimes\dnx-coreclr-win-arm.1.0.0-rc1-final\bin

**Comment by KoalaBear84** [comment]
Ahh. I already tried that, but if I really copy ALL missing files only, it works. It starts. Cannot yet access it, even after `netsh advfirewall firewall add rule name=”DNX Web Server port” dir=in action=allow protocol=TCP localport=5000`, but that is not the problem anymore.

It's really 'hard' to get all this running, and getting to know all the tools and steps needed. I guess it will all get much better when RC2 and the "dotnet" tool is released, and the current unstable things get a little more stable.

Thanks!

**Comment by KoalaBear84** [comment]
Problem was that I had run it on `http://localhost:5000` and it should be `http://*:5000`. It is running now. :)

**Comment by munyirik** [comment]
Yup, I was just about to type that. I agree, it's really hard to get this running:-).

**Comment by mehmetafsinyuce** [comment]
Hello I installed 1.0.0.0-rc1-final arm when I deploy solution to raspberry pi2, I faced with this error "Failed to locate or load coreclr.dll" when I look at the "C:\Users\Afsin\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-final\bin" this file is missing too. It is also not working with newer versions of coreclr.dll (win-arm.1.0.0-rc2-16319,16357,16551) 

Please help ...

**Comment by moozzyk** [comment]
@mehmetafsinyuce  Did you include runtime when publishing?

**Comment by adwaitasolutions** [comment]
This work for me.
Right click on project and select "Use specific Runtime" and then select 1.0.0-rc1-final(make sure you have mentioned same on project.json file too). After this change everything worked

**Comment by NickFessel** [comment]
I was finally able to get this working by following the instructions from @munyirik and @KoalaBear84. Thanks!

**Comment by RasberryFan** [comment]
Hello together,
i also tried to setup a ASP.NET project on my new rasberry pi 3. I am running Windows Iot build 14262.
I used dnx 1.0.0-rc1-final and added the missing files as described above. But when i navigate to my project folder on the rasberry Pi,  dnx returns without a message.

![image](https://cloud.githubusercontent.com/assets/18216355/14212727/87e04fde-f834-11e5-89e8-f765b44672fe.png)
Has anyone an idea to solve this?

**Comment by KoalaBear84** [comment]
I didn't have this problem. Unfortunately also have no clue. Please look into the web.cmd file and see what it all 'does' and try to do that step-by-step if you see any warnings or errors. I agree, it should at least give any hint, warning or error.

**Comment by ghost** [comment]
@RasberryFan is the firewall on the Pi 3 configured to allow the port? I set my firewall to allow TCP port 5000.

**Comment by RasberryFan** [comment]
During the last days i spent some time to double check my configuration and i get the results shown in the table below. I used dnx 1.0.0-rc1-final and the procedures described above by KoalaBear and Mũnyĩrĩk.
![image](https://cloud.githubusercontent.com/assets/18216355/14328139/b98bf4c0-fc35-11e5-9e16-c30121f23922.png)

**Comment by Fisherijus** [comment]
Did anyone managed to run asp.net on pi3 with rc2? cause I am not able to install rc1-final as it says:
There are no runtimes matching the name dnx-coreclr-win-arm on feed
https://www.myget.org/F/aspnetvnext/api/v2.

**Comment by bogdandanielb** [comment]
I'm getting the same problem with 1.0.0-rc1-final for ARM   "Failed to locate or load coreclr.dll" and "Failed to start CLR Host" if I copy coreclr.dll from other DNX ARM builds.  I've tried the latest too with dotnet CLI (RC2 or preview1) but facing this issue: "host executable not available in dependencies, using host for current platform"  https://github.com/dotnet/cli/issues/317 .
Is there any complete DNX ARM build out there that works ?
@RasberryFan did you find a complete version of dnx arm 1.0.0-rc1-final ?

Thank you

**Comment by bogdandanielb** [comment]
I've managed to create a working solution with **dnx-coreclr-win-arm.1.0.0-rc1-final** by copying all missing files from the newer **dnx-coreclr-win-arm.1.0.0-rc2-16357**  as per @munyirik suggestions. Note that all missing files are required not just **coreclr.dll**. Also in the same bin folder I suggest copying **libuv.dll** from **\approot\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-rc1-final\runtimes\win10-arm\native** usually located in your published location. 
 I hope it helps
