### ISSUE TITLE
DNX uses wrong version of System.Text.Encodings.Web

### ISSUE THREAD

**Issue by xatabhk** [aspnet/dnx#3369]
Error message:

```
System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Text.Encodings.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Extensions.DependencyInjection.RoutingServiceCollectionExtensions.AddRouting(IServiceCollection services, Action`1 configureOptions)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services, Action`1 setupAction)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action`1 setupAction)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at tbweb.Startup.ConfigureServices(IServiceCollection services) in C:\temp\x86dos_asp5\src\tbweb\Startup.cs:line 77


System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040
```

**Comment by Eilon** [comment]
@xatabhk what version of everything are you using? DNX? dotnet-cli? What's in your project.json?

**Comment by muratg** [comment]
@xatabhk Please file another one if you're still having issues.
