### ISSUE TITLE
Debuging at dnx startup

### ISSUE THREAD

**Issue by pjbazin** [aspnet/dnx#3420]
I've got a startup exception when launching my webapp. How can I get more details on that error and in that case wich data type is causing the problem ?

Application startup exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList`1 diagnosticMessages)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()

**Comment by pjbazin** [comment]
I'm using runtime RC1 coreclr x64 on linux. The same project on Windows does not have the issue.
