### ISSUE TITLE
Package restore error messages are difficult to see, and include stack traces

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#452]
Various common errors in package restore cause exceptions that dump stack traces to the console (e.g. in VS's Output window). The errors need to be clearer, and colorized if possible (e.g. from regular command line).

Repro: Add a bogus reference to `project.json`, such as a NuGet package with an invalid version spec (e.g. `xyz123`).

You get something like this:

```
klr.exe Information: 0 : RootHost.Load name=Microsoft.Framework.PackageManager
klr.exe Information: 0 : RootHost Assembly.LoadFile(C:\Users\elipton\.kre\packages\kre-svr50-x86.1.0.0-alpha2\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll)
Restoring packages for c:\users\elipton\documents\visual studio next\Projects\WebApplication29\WebApplication29\project.json
klr.exe Information: 0 : RootHost.Load name=Microsoft.Framework.Runtime.resources
klr.exe Information: 0 : RootHost.Load name=Microsoft.Framework.Runtime.resources
klr.exe Information: 0 : RootHost.Load name=Microsoft.Framework.Runtime.resources
klr.exe Information: 0 : RootHost.Load name=Microsoft.Framework.Runtime.resources
----------
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: 'xyz123' is not a valid version string.
Parameter name: version
   at NuGet.SemanticVersion.Parse(String version)
   at Microsoft.Framework.Runtime.Project.PopulateDependencies(IList`1 results, JObject settings)
   at Microsoft.Framework.Runtime.Project.GetProject(String json, String projectName, String projectPath)
   at Microsoft.Framework.Runtime.Project.TryGetProject(String path, Project& project)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Framework.PackageManager.RestoreCommand.ExecuteCommand()
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass1.<Main>b__8()
---> (Inner Exception #0) System.ArgumentException: 'xyz123' is not a valid version string.
Parameter name: version
   at NuGet.SemanticVersion.Parse(String version)
   at Microsoft.Framework.Runtime.Project.PopulateDependencies(IList`1 results, JObject settings)
   at Microsoft.Framework.Runtime.Project.GetProject(String json, String projectName, String projectPath)
   at Microsoft.Framework.Runtime.Project.TryGetProject(String path, Project& project)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__1.MoveNext()<---
----------
Restore failed
One or more errors occurred.
Loaded Module: klr.net45.dll
Found DLL Export: CallApplicationMain
```

Related to https://github.com/aspnet/KRuntime/issues/451.

**Comment by davidfowl** [comment]
Not anymore!
