### ISSUE TITLE
Project.json doesn't support portable frameworks when including output from .csproj

### ISSUE THREAD

**Issue by dsplaisted** [aspnet/dnx#608]
To reference a portable project from an ASP.NET vNext project, you can drop a project.json file next to the portable .csproj, [as described here](https://github.com/aspnet/KRuntime/issues/325).

In this case, I would expect to be able to use the same framework name as NuGet uses for the lib folder.  But if I use something like "portable-net45+win8+wp8+k10", I get an error:

```
System.ArgumentException: The profile part of a portable target framework must not contain the '-' character.
Parameter name: profilePart
   at NuGet.VersionUtility.ValidatePortableFrameworkProfilePart(String profilePart)
   at NuGet.NetPortableProfile.Parse(String profileValue)
   at Microsoft.Framework.Runtime.Project.ParseFrameworkName(String targetFramework)
   at Microsoft.Framework.Runtime.Project.BuildTargetFrameworkNode(KeyValuePair`2 targetFramework)
   at Microsoft.Framework.Runtime.Project.BuildTargetFrameworksAndConfigurations(JObject rawProject)
   at Microsoft.Framework.Runtime.Project.GetProject(String json, String projectName, String projectPath)
   at Microsoft.Framework.Runtime.Project.TryGetProject(String path, Project& project)
   at Microsoft.Framework.Runtime.ApplicationHostContext.get_Project()
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.Initialize(String appPath, FrameworkName targetFramework, String configuration)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.Calculate()
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.DoProcessLoop()
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.ProcessLoop(Object state)
```

**Comment by gulbanana** [comment]
If this is not going to be a first class feature, then what is the supported way to build a system like this:

- common vbproj or csproj containing code that can run on .NET 4.6 or Core CLR
- frontend project.json containing an asp.net 5 library/app
- frontend vbproj or csproj containing a desktop, store, or phone library/app

The obvious way would be to make the common project a PCL, but is there any other

**Comment by davidfowl** [comment]
What doesn't work?

**Comment by gulbanana** [comment]
Here's a minimal solution demonstrating the scenario:
http://thomascastiglione.com/MultipleFrontends.zip

There are a couple of projects designed for different verticals, each referencing a common library which uses the Debug.WriteLine() api (available on all iterations of .NET). You'll see there's one compile error, from the ASP.NET 5 frontend - it isn't able to reference the project CommonLibrary. Trying to add it as a reference using visual studio fails, and this issue seems to be about doing the same thing via project.json.

**Comment by davidfowl** [comment]
This actually works fine and compiles for me. I had to add a reference to System.Runtime in the aspnet50 section but adding a reference in visual studio works.

**Comment by gulbanana** [comment]
Interesting. I'm using VS2015 ctp 5, and the Add Reference dialog brings up an error reading "The following projects are not supported as reference: CommonLibrary". I tried adding it by hand, producing this project.json file:
http://pastebin.com/tShnddcA

The error in that case is CS0103	The name 'CommonLibrary' does not exist in the current context

But if this is going to be supported by whatever means, that's fine- bugs in the moment don't matter.
