### ISSUE TITLE
Executing command files from kpm bundle output throws exception on CoreCLR

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnx#642]
For example: Create a web app and add a command to execute to use weblistener. 

Do a kpm pack. The pack output has a web.cmd. 

Now run the web.cmd from the kpm pack output using any desktop CLR. Runs fine. Try to run the same command after switching to coreclr (both x86/amd64 reproduces the issue)

On AMD64+CoreCLR here is the error:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: version1
   at NuGet.SemanticVersion.op_LessThan(SemanticVersion version1, SemanticVersion version2)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Framework.Runtime.WalkContext.<>c__DisplayClass3.<Walk>b__7(Node node, Boolean state)
   at Microsoft.Framework.Runtime.WalkContext.ForEach[TState](Node root, TState state, Func`3 visitor)
   at Microsoft.Framework.Runtime.WalkContext.Walk(IEnumerable`1 dependencyResolvers, String name, SemanticVersion version, FrameworkName frameworkName)
   at Microsoft.Framework.Runtime.DependencyWalker.Walk(String name, SemanticVersion version, FrameworkName targetFramework)
   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
```

On X86+CoreCLR here is the error:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: version1
   at NuGet.SemanticVersion.op_LessThan(SemanticVersion version1, SemanticVersion version2)
   at NuGet.SemanticVersion.op_GreaterThan(SemanticVersion version1, SemanticVersion version2)
   at NuGet.SemanticVersion.op_GreaterThanOrEqual(SemanticVersion version1, SemanticVersion version2)
   at Microsoft.Framework.Runtime.WalkContext.Tracker.<>c__DisplayClass0.<IsBestVersion>b__1(Item known)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Framework.Runtime.WalkContext.Tracker.IsBestVersion(Item item)
   at Microsoft.Framework.Runtime.WalkContext.<>c__DisplayClass3.<Walk>b__7(Node node, Boolean state)
   at Microsoft.Framework.Runtime.WalkContext.ForEach[TState](Node root, TState state, Func`3 visitor)
   at Microsoft.Framework.Runtime.WalkContext.Walk(IEnumerable`1 dependencyResolvers, String name, SemanticVersion version, FrameworkName frameworkName)
   at Microsoft.Framework.Runtime.DependencyWalker.Walk(String name, SemanticVersion version, FrameworkName targetFramework)
   at Microsoft.Framework.Runtime.DefaultHost.Initialize()
   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
```

**Comment by muratg** [comment]
@Praburaj is this still an issue?

**Comment by muratg** [comment]
@Praburaj Do we still have this issue on CoreCLR?

**Comment by Praburaj** [comment]
I can validate and update the bug.

**Comment by glennc** [comment]
@Praburaj Did you see if this was still an issue?

**Comment by Praburaj** [comment]
I can't validate this issue right now because basic apps are broken on coreclr. Will update as soon as that's working.
