### ISSUE TITLE
KPM Pack fails for "webroot" : ".",

### ISSUE THREAD

**Issue by naianacampos** [aspnet/dnx#751]
1. Create vNext WAP
2. Modify project.json : 
     "webroot" : ".",
3. for project above, try kpm pack
"C:\Users\fwtlaba\.kre\packages\kre-clr-x86.1.0.0-beta1-10541\bin\kpm.cmd" pack --runtime "C:\Users\fwtlaba\.kre\packages\kre-clr-x86.1.0.0-beta1-10541";"C:\Users\fwtlaba\.kre\packages\kre-clr-amd64.1.0.0-beta1-10541" --out "C:\Users\fwtlaba\AppData\Local\Temp\AspNetPublish\WebApplication10-90" --configuration Release 

[Observed]

files in kpm pack :
![fileswwwroot](https://cloud.githubusercontent.com/assets/9043282/4621445/696b691c-532b-11e4-90ca-518644e5debf.PNG)
![fileswwwroot2](https://cloud.githubusercontent.com/assets/9043282/4621444/67f6c9d2-532b-11e4-986f-4224e84c39b0.PNG)

command line:
![cmdline](https://cloud.githubusercontent.com/assets/9043282/4621447/6d97855c-532b-11e4-81bd-f1302cd1281c.PNG)

```
Copying contents of project dependency WebApplication10 to C:\Users\fwtlaba\AppData\Local\Temp\AspNetPublish\WebApplicat
ion10-90\.
  Source C:\Users\fwtlaba\Documents\Visual Studio 14\Projects\WebApplication10\src\WebApplication10
  Target C:\Users\fwtlaba\AppData\Local\Temp\AspNetPublish\WebApplication10-90\.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\fwtlaba\AppData\Local\Temp\AspNetPubli
sh\WebApplication10-90\approot\src\WebApplication10\k.ini'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShar
e share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileO
ptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.Framework.PackageManager.Packing.PackProject.PostProcess(PackRoot root)
   at Microsoft.Framework.PackageManager.Packing.PackRoot.Emit()
   at Microsoft.Framework.PackageManager.Packing.PackManager.Package()
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass2.<Main>b__10()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)

C:\Users\fwtlaba\Documents\Visual Studio 14\Projects\WebApplication10\src\WebApplication10>
```

[Expected]
successful publish

**Comment by muratg** [comment]
Closing this.  If this is still an issue, please reopen.
