### ISSUE TITLE
Error thrown occasionally by MVC view compiler when doing frequent Razor file changes

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#809]
Doing lots of edit CSHTML in VS, alt-tab back to browser and refresh, and I get this error in the browser occasionally. Got it twice in a few minutes the other day.

```
Microsoft.AspNet.Mvc.Razor.CompilationFailedException
Compilation for 'C:\src\GitHub\AspNet\MusicStore\src\MusicStore.Spa\Pages\Admin.cshtml' failed:
error CS0009: Metadata file '<in-memory assembly>' could not be opened -- Unable to read metadata file
at Microsoft.AspNet.Mvc.Razor.CompilationResult.get_CompiledType()
 
at Microsoft.AspNet.Mvc.Razor.CompilerCache.OnCacheMiss(RelativeFileInfo file, Boolean isInstrumented, Func<CompilationResult> compile)
 
at Microsoft.AspNet.Mvc.Razor.CompilerCache.GetOrAdd(RelativeFileInfo fileInfo, Boolean enableInstrumentation, Func<CompilationResult> compile)
 
at Microsoft.AspNet.Mvc.Razor.VirtualPathRazorPageFactory.CreateInstance(String relativePath)
 
at Microsoft.AspNet.Mvc.Razor.RazorViewEngine.CreateViewEngineResult(ActionContext context, String viewName, Boolean partial)
 
at Microsoft.AspNet.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName)
 
at Microsoft.AspNet.Mvc.Rendering.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean partial)
 
at Microsoft.AspNet.Mvc.Rendering.CompositeViewEngine.FindView(ActionContext context, String viewName)
 
at Microsoft.AspNet.Mvc.ViewResult.FindView(IViewEngine viewEngine, ActionContext context, String viewName)
 
at Microsoft.AspNet.Mvc.ViewResultBase.FindViewInternal(IViewEngine viewEngine, ActionContext context, String viewName)
 
at Microsoft.AspNet.Mvc.ViewResultBase.<ExecuteResultAsync>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeActionResult>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeActionResultFilter>d__1.MoveNext()
 
at Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeActionResultWithFilters>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Mvc.FilterActionInvoker.<InvokeAsync>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Mvc.ControllerActionInvoker.<InvokeAsync>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 
at Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Mvc.Routing.AttributeRoute.<RouteAsync>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware<TOptions>.<Invoke>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware<TOptions>.<Invoke>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware<TOptions>.<Invoke>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware<TOptions>.<Invoke>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Loader.IIS.KlrHttpApplication.<ProcessRequestAsyncImpl>d__1.MoveNext()
 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 
at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.<InvokeProcessRequestAsyncImpl>d__1.MoveNext()
 ```

**Comment by troydai** [comment]
VS + in-memory assembly + Random = Sounds like something in the DTH.

**Comment by glennc** [comment]
@troydai can you investigate this a bit further and see if you can identify a cause?

**Comment by troydai** [comment]
Got it.

**Comment by troydai** [comment]
Talked with @DamianEdwards. Told that this bug has been observed for a while. I'll close this one for now.
