### ISSUE TITLE
Commands should not display stack traces for normal user errors

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#864]
kpm.cmd and k.cmd often end with stack traces though the errors hit are hardly exceptional.  For example `kpm.cmd unsupported` displays
```
Specify --help for a list of available options and commands.
System.Exception: TODO: Error: unrecognized argument 'unsupported'
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.HandleUnexpecteArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
```
instead of simply providing the help information.

Similarly `k.cmd test` displays the following for a sample compilation error.
```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.Mvc.TagHelpers.Test' or one of its depend
encies. General Exception (Exception from HRESULT: 0x80131500)
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.Mvc.TagHelpers.Test' or one of its depend
encies. General Exception (Exception from HRESULT: 0x80131500)
File name: 'Microsoft.AspNet.Mvc.TagHelpers.Test' ---> Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException: C:
\dd\k\Mvc.1\test\Microsoft.AspNet.Mvc.TagHelpers.Test\SelectTagHelperTest.cs(310,66): error CS1003: Syntax error, '>' ex
pected
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(String name, IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(String name)
   at klr.host.LoaderContainer.Load(String name)
   at klr.hosting.RuntimeBootstrapper.<>c__DisplayClass0.<ExecuteAsync>b__8(AssemblyName assemblyName)
   at klr.hosting.RuntimeBootstrapper.<>c__DisplayClass0.<ExecuteAsync>b__11(Object sender, ResolveEventArgs a)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Runtim
eAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntro
spection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Runtime
Assembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntros
pection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, Ru
ntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIn
trospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.KRunner.Program.ExecuteAssembly(Object consoleLock, String assemblyName, CommandLine options)
```

The stack trace is not useful for these scenarios (unlike say an NRE in `klr.exe`) and displaying it is inconsistent with other commands.  For example `kpm.cmd build` does not display a stack trace for the same compilation error as above.

**Comment by muratg** [comment]
Let's decide what to do with this in Beta 7

**Comment by dougbu** [comment]
:birthday: :balloon: :tada: :dancers: ...

**Comment by muratg** [comment]
@dougbu I share those emotions :)

**Comment by davidfowl** [comment]
I think we'll need to go back and forth here. Hiding stack traces for load errors for example is a bad idea and we'll need to get more specific about what we hide exactly.

**Comment by JunTaoLuo** [comment]
reopening to hide stack trace for compilation errors as well.

**Comment by JunTaoLuo** [comment]
Merged to dev
